- geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/FilterConverter.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/ParquetReadWriteTest.scala
> GEOMESA-2106 Fixing parquet filtering on geometry attribute names

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloAuditService.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloEventReader.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloEventWriter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/TestWithDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/stats/usage/QueryStatTransformTest.scala
- geomesa-accumulo/geomesa-accumulo-jobs/pom.xml
- geomesa-accumulo/geomesa-accumulo-spark-runtime/pom.xml
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/audit/QueryEvent.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geoserver/ViewParams.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureReader.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaQueryRunner.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/cache/FilePersistence.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/cache/PropertiesPersistence.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/cache/FilePersistenceTest.scala
- geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/GeoMesaDataStoreServlet.scala
- geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/PersistentDataStoreServlet.scala
- geomesa-web/geomesa-web-data/pom.xml
- geomesa-web/geomesa-web-data/src/main/resources/applicationContext.xml
- geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/security/QueryAuditEndpoint.scala
- geomesa-web/geomesa-web-data/src/test/scala/org/locationtech/geomesa/web/security/QueryAuditEndpointTest.scala
- pom.xml
* Allowing filter by arrow query in web endpoint
* Changing storage of query hints to match udpated names
> GEOMESA-2090 Displaying Arrow hints in query audits

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloAuditService.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloEventReader.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloEventWriter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/TestWithDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/stats/usage/QueryStatTransformTest.scala
- geomesa-accumulo/geomesa-accumulo-jobs/pom.xml
- geomesa-accumulo/geomesa-accumulo-spark-runtime/pom.xml
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/audit/QueryEvent.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geoserver/ViewParams.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureReader.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaQueryRunner.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/cache/FilePersistence.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/cache/PropertiesPersistence.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/cache/FilePersistenceTest.scala
- geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/GeoMesaDataStoreServlet.scala
- geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/PersistentDataStoreServlet.scala
- geomesa-web/geomesa-web-data/pom.xml
- geomesa-web/geomesa-web-data/src/main/resources/applicationContext.xml
- geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/security/QueryAuditEndpoint.scala
- geomesa-web/geomesa-web-data/src/test/scala/org/locationtech/geomesa/web/security/QueryAuditEndpointTest.scala
- pom.xml
* Allowing filter by arrow query in web endpoint
* Changing storage of query hints to match udpated names
> 1.3 - GEOMESA-2090 Displaying Arrow hints in query audits

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/AccumuloGeoMesaStats.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/StatsCombiner.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/stats/StatsCombinerTest.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/AccumuloRunner.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/stats/AccumuloStatsConfigureCommand.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/stats/StatsConfigureCommand.scala
> GEOMESA-2091 Adding stats-iterator CLI tools

- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/json/JsonPathParser.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/json/JsonPathPropertyAccessor.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/json/KryoJsonSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/json/JsonPathFilterFunctionTest.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/json/JsonPathParserTest.scala
- geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndex.scala
- geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoMesaIndexPropertyTransformer.scala
> GEOMESA-2101 Handling quoted attributes in JsonPath parser

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloFeatureIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreStatsTest.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraFeatureIndex.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
> GEOMESA-1584 Optimized deletes for Filter.INCLUDE

- .gitignore
- docs/README.md
- docs/requirements.txt
* Added docs build requirements.txt
* Adjusted docs to use requirements file
* Added ignore for docs build python env (geomesa/.sphinx)
> GEOMESA-2119 Fix Geomesa Docs build

- docs/pom.xml
> GEOMESA-2125 Set and Bump Ant and Maven Ant Plugin Versions

- docs/tutorials/geomesa-hbase-on-cdh.rst
- docs/user/hbase/install.rst
Tutorial to deploy GeoMesa 1.3.X on CDH 5.X HBase
> Tutorial to deploy GeoMesa 1.3.X on CDH 5.X HBase

- docs/tutorials/geomesa-hbase-on-cdh.rst
- docs/tutorials/index.rst
- docs/user/hbase/install.rst
> GEOMESA-2127 Tutorial to deploy GeoMesa on CDH HBase (#1808)

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/bin/BinaryOutputEncoder.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/bin/BinaryOutputEncoderTest.scala
> GEOMESA-2128 Fixing BinaryOutputEncoder for Timestamp attributes

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/bin/BinaryOutputEncoder.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/bin/BinaryOutputEncoderTest.scala
> 1.3 - GEOMESA-2128 Fixing BinaryOutputEncoder for Timestamp attributes

- docs/user/filesystem/configuration.rst
- docs/user/filesystem/index.rst
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemDataStore.scala
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
> GEOMESA-2131 Closing FS writers after timeout to avoid OOM

- geomesa-fs/geomesa-fs-storage-api/src/main/java/org/locationtech/geomesa/fs/storage/api/FileSystemWriter.java
- geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/FilteringIterator.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/SimpleFeatureParquetWriter.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsIngestCommand.scala
> GEOMESA-2132 Parquet FS reader skip bad files instead of dying

- docs/user/hbase/configuration.rst
- docs/user/hbase/index.rst
- docs/user/hbase/usage.rst
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheTest.scala
* DataStore property 'hbase.config.paths' or system property 'geomesa.hbase.config.paths'
> GEOMESA-2120 Adding data store option for hbase config files

- geomesa-fs/geomesa-fs-hbase-spark-runtime/pom.xml
- geomesa-fs/geomesa-fs-hbase-spark-runtime/src/main/scala/org/locationtech/geomesa/ScalaDocs.scala
- geomesa-fs/pom.xml
> Added FSDS and HBase combined spark runtime

- geomesa-bigtable/geomesa-bigtable-datastore/pom.xml
- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableDataStore.scala
- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/index/BigtableFeatureIndex.scala
- geomesa-bigtable/geomesa-bigtable-datastore/src/test/scala/org/locationtech/geomesa/bigtable/BigTableIntegrationTest.scala
- geomesa-bigtable/geomesa-bigtable-spark-runtime/src/main/scala/org/locationtech/geomesa/ScalaDocs.scala
- geomesa-bigtable/geomesa-bigtable-spark/src/main/java/org/locationtech/geomesa/bigtable/spark/BigtableInputFormatBase.java
- geomesa-bigtable/geomesa-bigtable-spark/src/main/java/org/locationtech/geomesa/bigtable/spark/BigtableTableRecordReader.java
- geomesa-bigtable/geomesa-bigtable-spark/src/main/scala/org/locationtech/geomesa/bigtable/spark/BigtableExtendedScanSplit.java
- geomesa-bigtable/geomesa-bigtable-spark/src/main/scala/org/locationtech/geomesa/bigtable/spark/BigtableSparkRDDProvider.scala
- geomesa-bigtable/geomesa-bigtable-tools/src/main/scala/org/locationtech/geomesa/bigtable/tools/BigtableIngestCommand.scala
- geomesa-bigtable/geomesa-bigtable-tools/src/main/scala/org/locationtech/geomesa/bigtable/tools/BigtableRunner.scala
> GEOMESA-2135 Fixing bigtable tools classpath, license headers

- CONTRIBUTING.md
> GEOMESA-2136 Adding details on copyright to CONTRIBUTING.md

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloQueryEventTransform.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/audit/AccumuloQueryEventTransformTest.scala
> GEOMESA-2118 Fixing conversion of hits to Long (big data!)

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBasePlatform.scala
> GEOMESA-2126 Fixing HBase scans for ID queries

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala
> 1.3 - GEOMESA-2141 Fixing BIN join queries with transforms

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala
> GEOMESA-2141 Fixing BIN join queries with transforms

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpec.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
> 1.3 - GEOMESA-2144 Adding attribute type encoding for java.sql.Date

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpec.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
> GEOMESA-2144 Adding attribute type encoding for java.sql.Date

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloFeatureIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/encoders/IndexValueEncoder.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/IndexValueEncoderTest.scala
- geomesa-accumulo/geomesa-accumulo-raster/src/main/scala/org/locationtech/geomesa/raster/iterators/IteratorExtensions.scala
- geomesa-accumulo/geomesa-accumulo-raster/src/main/scala/org/locationtech/geomesa/raster/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
> GEOMESA-2114 Removing use of schemaVersion

- geomesa-accumulo/geomesa-accumulo-tools/bin/install-hadoop-accumulo.sh
- geomesa-bigtable/geomesa-bigtable-tools/bin/install-hadoop-hbase.sh
- geomesa-cassandra/geomesa-cassandra-tools/bin/install-cassandra-jars.sh
- geomesa-cassandra/geomesa-cassandra-tools/bin/install-tools-jars.sh
- geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh
- geomesa-hbase/geomesa-hbase-tools/bin/install-hadoop.sh
- geomesa-hbase/geomesa-hbase-tools/bin/install-hbase.sh
- geomesa-kafka/geomesa-kafka-tools/bin/install-kafka.sh
- geomesa-kafka/geomesa-kafka-tools/bin/install-loggers.sh
- geomesa-lambda/geomesa-lambda-tools/bin/install-kafka.sh
- geomesa-tools/bin/common-functions.sh
- geomesa-tools/bin/install-imageio-ext.sh
- geomesa-tools/bin/install-jai.sh
- geomesa-tools/bin/install-jline.sh
- geomesa-tools/bin/install-saxon.sh
> GEOMESA-2146 Remove namerefs for older bash versions

- docs/user/hbase/install.rst
> GEOMESA-2129 Document layout of hbase-conf jar

- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/ConverterIngest.scala
GEOMESA-2145 - Updated schema comparison to use the geotools DataUtilities.compare method
> GEOMESA-2145 - Ingest schema version checks consider index 'full' different from 'true'

- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
* Example failing test for future reference
* Does not close ticket
> GEOMESA-339 Example MultiLine CSV Failure

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/planning/QueryPlannerTest.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/CommonParams.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/ExplainCommand.scala
> GEOMESA-2142 Fixing --index flag in CLI export/explain

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
> GEOMESA-2147 HBase - adding check for existence of tables before deleting

- docs/user/hbase/install.rst
> GEOMESA-2148 Docs on Azure HDInsight HBase install

- docs/tutorials/spark.rst
> GEOMESA-2160 Fixing variable name in spark tutorial

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/DeltaWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/SimpleFeatureArrowIO.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/SimpleFeatureVector.scala
- geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/io/DeltaWriterTest.scala
- geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/io/SimpleFeatureArrowFileTest.scala
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/GeometryFields.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/GeometryVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractLineStringVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiLineStringVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiPointVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiPolygonVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractPointVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractPolygonVector.java
- geomesa-arrow/geomesa-arrow-jts/src/test/java/org/locationtech/geomesa/arrow/vector/GeometryVectorTest.java
> 1.3 - GEOMESA-2153 Fixing arrow queries for line strings

- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcess.scala
> 1.3 - GEOMESA-2156 Allowing for push-down sort indication in Arrow visitor

- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/bin/BinaryOutputEncoderTest.scala
> GEOMESA-2155 Synchronizing date format in BinaryOutputEncoderTest

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryHints.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/InMemoryQueryRunner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryRunner.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/planning/QueryPlannerTest.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcess.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureOrdering.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/iterators/SortingSimpleFeatureIterator.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/iterators/SortingSimpleFeatureIteratorTest.scala
* Query sort is set as a hint, and set to null
> GEOMESA-2156 Passing query sort to Arrow hints

- geomesa-utils/src/main/resources/org/locationtech/geomesa/utils/io/remote-prefixes.list
> GEOMESA-2154 Adding s3 to list of remote prefixes

- geomesa-accumulo/geomesa-accumulo-tools/README.md
- geomesa-accumulo/geomesa-accumulo-tools/src/test/resources/examples/city-mysql.conf
- geomesa-cassandra/geomesa-cassandra-tools/conf/application.conf
- geomesa-convert/geomesa-convert-all/src/test/scala/org/locationtech/geomesa/convert/URLConfigProviderTest.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
- geomesa-tools/conf/application.conf
- geomesa-tools/conf/sfts/geonames/reference.conf
- geomesa-tools/conf/sfts/gtd/reference.conf
- geomesa-tools/conf/sfts/nyctaxi/reference.conf
- geomesa-tools/examples/ingest/csv/example.conf
> GEOMESA-2170 Fixing YYYY->yyyy for java.time in provided converters

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/CachedLazyMetadata.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/metadata/CachedLazyMetadataTest.scala
> GEOMESA-2163 Handling for invalid catalog rows in getTypeNames

- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableDataStore.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseConnectionPool.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/GeoMesaHBaseInputFormat.scala
> GEOMESA-2121 Adding logging around HBase authentication

- geomesa-bigtable/geomesa-bigtable-tools/src/main/scala/org/locationtech/geomesa/bigtable/tools/BigtableIngestCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/HBaseDataStoreCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/data/HBaseCreateSchemaCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/data/HBaseDeleteCatalogCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/data/HBaseDeleteFeaturesCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/data/HBaseRemoveSchemaCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/export/HBaseExportCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/ingest/HBaseIngestCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/stats/HBaseStatsAnalyzeCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/stats/HBaseStatsBoundsCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/stats/HBaseStatsCountCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/stats/HBaseStatsHistogramCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/stats/HBaseStatsTopKCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/status/HBaseDescribeSchemaCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/status/HBaseExplainCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/status/HBaseGetSftConfigCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/status/HBaseGetTypeNamesCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/status/HBaseKeywordsCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/status/HBaseVersionRemoteCommand.scala
> GEOMESA-2167 Adding flag to disable remote filters for HBase CLI

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseBackedMetadata.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/utils/HBaseVersions.scala
> GEOMESA-2166 Adding support for Cloudera HBase 1.2

- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/java/org/locationtech/geomesa/fs/storage/api/PartitionSchemeUtils.java
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/java/org/locationtech/geomesa/fs/storage/interop/PartitionSchemeUtils.java
> GEOMESA-2182 Extend PartitionScheme Object to Java API

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/HBaseDataStoreCommand.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/BinAggregatingScan.scala
> GEOMESA-2181 HBase CLI remote filter flag fix

- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/Point2PointProcess.scala
- geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/Point2PointProcessTest.scala
> GEOMESA-2175 Point2PointProcess support for grouping by non-strings

- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
> GEOMESA-2186 Z3 UUID converter function

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreFactory.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraFeatureIndex.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
> GEOMESA-2179 CassandraDataStore default to strict bounding boxes

- docs/tutorials/geomesa-hbase-on-cdh.rst
- docs/user/filesystem/geoserver.rst
- docs/user/filesystem/index.rst
- docs/user/filesystem/usage.rst
- docs/user/nifi.rst
- docs/user/upgrade.rst
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemDataStore.scala
> GEOMESA-1972 Updating NiFi docs

- docs/tutorials/geomesa-quickstart-cassandra.rst
- docs/tutorials/index.rst
* Heatmaps don't work due to no server-side processing
> GEOMESA-2165 Removing Cassandra tutorial heatmap section

- geomesa-accumulo/geomesa-accumulo-tools/bin/install-hadoop-accumulo.sh
- geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh
- geomesa-hbase/geomesa-hbase-tools/bin/install-hadoop.sh
> GEOMESA-2187 Adding check for existing guava in install-* scripts

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreAlterSchemaTest.scala
- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/accumulo/index/AttributeIndexJob.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
> GEOMESA-1666 Enabling attribute index if required during schema update

- geomesa-filter/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/Convert2ViewerFunction.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/CurrentDateFunction.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/DateToLong.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/FastProperty.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/ProxyIdFunction.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/function/ProxyIdFunctionTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
* 'proxyId' CQL function will hash feature ID to an int
* Feature IDs encoded as UUIDs can be specified by 'geomesa.fid.uuid=true'
> GEOMESA-2184 ProxyId CQL function

- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/HBaseDataStoreCommand.scala
> GEOMESA-2209 Fixing HBase zookeeper param in m/r ingest

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
- geomesa-kafka/geomesa-kafka-utils/pom.xml
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/ThreadedConsumer.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaCacheLoader.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala
> GEOMESA-2204 Fixing Kafka consumer sleep while more data to read

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/AccumuloVersion.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/SchemaProperties.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/CachedLazyMetadata.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/CreateSchemaCommand.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/GeoMesaSystemProperties.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParam.scala
- geomesa-web/geomesa-web-data/pom.xml
> GEOMESA-2198 Checking for iterators on classpath during createSchema

- geomesa-tools/conf/.scala_repl_init
> GEOMESA-2205 Add geomesa header and version to scala-command

- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
> GEOMESA-2215 Restore SparkSQL predicate pushdown rules

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
* Converters now check for a non-null id and set Hints.USE_PROVIDED_ID
if found
> GEOMESA-2223 Use Provided FID in Converters

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloQueryEventTransform.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/audit/AccumuloQueryEventTransformTest.scala
> 1.3 - GEOMESA-2118 Fixing conversion of hits to Long

- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/main/resources/META-INF/services/org.locationtech.geomesa.convert.TransformerFunctionFactory
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
> GEOMESA-2229 Converter 'withDefault' transform for handling null values

- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
- geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLDataTest.scala
> GEOMESA-2221 Push down Spark filters in Catalyst where possible 

- pom.xml
> GEOMESA-2243 Upgrade surefire plugin

- geomesa-hbase/geomesa-hbase-tools/bin/install-hadoop.sh
> GEOMESA-2245 HBase - fixing guava version in CLI install script

- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
* Adds format/printf converter functions.
> GEOMESA-2218 Create printf converter transform

- geomesa-accumulo/geomesa-accumulo-tools/examples/ingest/avro/ingest_avro.sh
- geomesa-accumulo/geomesa-accumulo-tools/examples/ingest/csv/ingest_csv.sh
- geomesa-accumulo/geomesa-accumulo-tools/examples/ingest/json/ingest_json.sh
- geomesa-accumulo/geomesa-accumulo-tools/examples/ingest/xml/ingest_xml.sh
- geomesa-hbase/geomesa-hbase-tools/examples/ingest/avro/ingest_avro.sh
- geomesa-hbase/geomesa-hbase-tools/examples/ingest/csv/ingest_csv.sh
> GEOMESA-2232 Update examples with new executable

- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala
> GEOMESA-2236 hbase.conf.files params fails in spark

- build/cqs.tsv
- geomesa-accumulo/geomesa-accumulo-native-api/pom.xml
- geomesa-convert/geomesa-convert-osm/pom.xml
- geomesa-hbase/geomesa-hbase-native-api/pom.xml
- geomesa-native-api/pom.xml
- pom.xml
> GEOMESA-2238 - Minor dependency version updates

- build/cqs.tsv
- docs/user/spark/sparksql_functions.rst
- geomesa-spark/geomesa-spark-jts/pom.xml
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/GeometricConstructorFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/GeometricOutputFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/GeometricProcessingFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/SpatialRelationFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/GeometricConstructorFunctionsTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/SpatialRelationFunctionsTest.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLTypes.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeometricDistanceFunctions.scala
- geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLGeometricDistanceFunctionsTest.scala
- pom.xml
> GEOMESA-2230 Remove GeoTools dependencies in geomesa-spark-jts

- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/HBaseDataStoreCommand.scala
> GEOMESA-2249 HBase - adding security params to CLI tools

- geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa-accumulo
- geomesa-arrow/geomesa-arrow-tools/bin/geomesa-arrow
- geomesa-bigtable/geomesa-bigtable-tools/bin/geomesa-bigtable
- geomesa-cassandra/geomesa-cassandra-tools/bin/geomesa-cassandra
- geomesa-fs/geomesa-fs-tools/bin/geomesa-fs
- geomesa-hbase/geomesa-hbase-tools/bin/geomesa-hbase
- geomesa-lambda/geomesa-lambda-tools/bin/geomesa-lambda
> GEOMESA-2254 Fixing quoting of passed strings in CLI tools

- geomesa-accumulo/geomesa-accumulo-stats-gs-plugin/pom.xml
- geomesa-fs/geomesa-fs-gs-plugin/pom.xml
> GEOMESA-2255 FileSystem - Geoserver GML export fails with Saxon error

- docs/user/filesystem/architecture.rst
- geomesa-utils/src/main/resources/org/locationtech/geomesa/utils/io/remote-prefixes.list
> GEOMESA-2262 Add gs:// to list of remote prefixes

- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
- geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLDataTest.scala
> GEOMESA-2273 Fixing push-down spark sql date predicates

- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/AbstractIngestJob.scala
> GEOMESA-2275 Disable speculative execution during ingestion

- geomesa-tools/conf/sfts/gtd/reference.conf
> GEOMESA-2282 Fix GTD converter date format

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3IndexKeySpace.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
> GEOMESA-2280 Fixing unbounded secondary date attribute ranges

- docs/user/accumulo/data_management.rst
- docs/user/cassandra/index.rst
- docs/user/cassandra/index_config.rst
- docs/user/cli/export.rst
- docs/user/cli/index.rst
- docs/user/cli/ingest.rst
- docs/user/datastores/data.rst
- docs/user/datastores/index.rst
- docs/user/datastores/index_basics.rst
- docs/user/upgrade.rst
> GEOMESA-2277 Docs - version compatibility

- geomesa-spark/geomesa-spark-jts/src/main/scala/org/apache/spark/sql/jts/AbstractGeometryUDT.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/util/JavaAbstractGeometryUDT.scala
- geomesa-spark/geomesa_pyspark/src/main/python/geomesa_pyspark/spark.py
- geomesa-spark/geomesa_pyspark/src/main/python/setup.py
> GEOMESA-2176 Create python conversion for JTS Geometry instances

- geomesa-accumulo/geomesa-accumulo-spark/src/main/scala/org/locationtech/geomesa/spark/accumulo/AccumuloSpatialRDDProvider.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-jobs/src/main/scala/org/locationtech/geomesa/hbase/jobs/GeoMesaHBaseInputFormat.scala
- geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/HBaseSpatialRDDProvider.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala
- geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLDataTest.scala
> GEOMESA-2241 HBase Spark queries can drop part of FID

- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
- geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
> GEOMESA-2133 JsonPath converter treats missing elements as null

- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
> GEOMESA-2225 Fixing converter parseMap example in docs, adding unit test

- geomesa-index-api/pom.xml
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/InMemoryQueryRunner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/Reprojection.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geometry/Geometry.scala
> GEOMESA-2274 Supporting query reprojections

- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonFunctionFactory.scala
- geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
> GEOMESA-2212 JSON list converter - handle nulls

- docs/README.md
- docs/common.py
- docs/user/accumulo/configuration.rst
- docs/user/accumulo/install.rst
- pom.xml
> GEOMESA-2289 Change Recommended Accumulo/Hadoop versions

- docs/user/datastores/query_config.rst
- docs/user/datastores/query_planning.rst
> GEOMESA-2293 Fixing query planning import statement in docs

- build/cqs.tsv
- pom.xml
> GEOMESA-2294 Update ORC version to 1.4.4

- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemDataStore.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
> GEOMESA-2296 FSDS - check for reserved words on createSchema

- README.md
- build/README.md
* Removed section on scala 2.10 build, as it is no longer supported
> GEOMESA-2297 Add link to JIRA to main readme

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/AttributeFilterStrategy.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
> GEOMESA-2140 De-prioritize attribute not null queries

- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/utils/ParameterConverters.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/utils/ParameterConvertersTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/GeoMesaSystemProperties.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParam.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/DurationParsing.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/conf/GeoMesaPropertiesTest.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParamTest.scala
> GEOMESA-2311 Case-insensitive duration parsing

- build/cqs.tsv
- pom.xml
> GEOMESA-2301 Upgrade to typesafe config 1.3.3

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableDataStore.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/protobuf/GeoMesaProtoGenerator.proto
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseAggregator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseVersionAggregator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/utils/CoprocessorConfig.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/SchemaProperties.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/VersionRemoteCommand.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/SemanticVersion.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
> GEOMESA-1965 HBase remote coprocessor version

- docs/user/accumulo/ageoff.rst
- docs/user/accumulo/commandline.rst
- docs/user/datastores/runtime_config.rst
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/AccumuloRunner.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/data/AccumuloCompactCommand.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/uuid/Z3FeatureIdGenerator.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/uuid/Z3FeatureIdGeneratorTest.scala
* Fixes Z3 UUID byte merging sign errors
> GEOMESA-2308 Incremental Accumulo compaction command

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/index/SizeSeparatedBucketIndexSupport.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/BasicFeatureCache.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/EventTimeFeatureCache.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCache.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/EventTimeFeatureCacheTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheTest.scala
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/GeoIndex.java
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/BucketIndex.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/SizeSeparatedBucketIndex.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/index/SizeSeparatedBucketIndexTest.scala
* SizeSeparatedBucketIndex uses a size-separated index to store non-points
> GEOMESA-2316 Kafka - Support geometries with extents

- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureIterator.scala
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
- geomesa-fs/geomesa-fs-datastore/src/test/resources/log4j.xml
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/FileSystemThreadedReader.scala
> GEOMESA-2337 Fixing FSDS multi-threaded reads

- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/resources/META-INF/services/org.locationtech.geomesa.fs.storage.api.PartitionSchemeFactory
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/DateTimeScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/Z2Scheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/PartitionSchemeConfTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/PartitionSchemeTest.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/data/FsCreateSchemaCommand.scala
> GEOMESA-2342 Add XZ2 Support for the FileSystem DataStore

- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
> GEOMESA-2344 Allow for non-interactive Shapefile ingest

- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
> GEOMESA-2347 Fixing creation of $0 line in delimited text converter

- geomesa-convert/geomesa-convert-all/src/test/scala/org/locationtech/geomesa/convert/FindConvertersTest.scala
- geomesa-convert/geomesa-convert-common/src/main/resources/META-INF/services/org.locationtech.geomesa.convert.SimpleFeatureConverterFactory
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/CompositeConverter.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/CompositeTextConverterTest.scala
* Restored v1 class, as v2 composite caches API doesn't fit well with v1
> GEOMESA-2346 Fixing version 1 CompositeConverter loading

- build/README.md
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/TypeInference.scala
- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonConverterFactory.scala
- geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
> GEOMESA-2349 Fixing GeoJson ingest type inference

- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/GeoJsonParsing.scala
- geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
> GEOMESA-2348 GeoJson type inference - support 3D coordinates

- build/README.md
- geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/ingest/ShpIngestTest.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
- geomesa-convert/geomesa-convert-shp/src/main/scala/org/locationtech/geomesa/convert/shp/ShapefileConverterFactory.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/package.scala
> GEOMESA-2345 Allow for auto-reprojection of shapefiles on ingest

- docs/user/datastores/runtime_config.rst
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/OrSequentialEquality.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/factory/FastFilterFactory.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/factory/FastFilterFactoryTest.scala
> GEOMESA-2353 Threshold for using OR hash equality filter

- geomesa-convert/geomesa-convert-avro/src/main/scala/org/locationtech/geomesa/convert/avro/AvroConverter.scala
- geomesa-convert/geomesa-convert-avro/src/test/scala/org/locationtech/geomesa/convert/avro/AvroConverterTest.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/SimpleFeatureConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/TypeInference.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/Expression.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/ExpressionParser.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverter.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/CopyingInputStream.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/TextTools.scala
* Avro converter - set raw bytes as $0
* Allow for whitespace in function/try methods
* Allow for creating converters by name
* Filtering empty lines in XML converter multi-line mode
> GEOMESA-2355,GEOMESA-2356 Converter fixes

- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
* DelimitedTextConverter.magicParsing
> GEOMESA-2357 Ability to parse 'magic' delimited files

- docs/_static/css/theme_custom.css
- docs/common.py
- docs/tutorials/spark.rst
- docs/user/accumulo/install.rst
- docs/user/bigtable/install.rst
- docs/user/cassandra/install.rst
- docs/user/cli/ingest.rst
- docs/user/geoserver.rst
- docs/user/hbase/install.rst
- docs/user/lambda/install.rst
- docs/user/spark/index.rst
- docs/user/upgrade.rst
* Updated spark_version to 2.2.x or 2.3.x
* Added information on `--force` flag for ingest
> GEOMESA-2351 Docs - upgrade guide for 2.1

- build/cqs.tsv
- pom.xml
> GEOMESA-2354 - Upgrade to Commons-Compression version 1.16

- geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/ingest/ShpIngestTest.scala
- geomesa-convert/geomesa-convert-shp/src/main/scala/org/locationtech/geomesa/convert/shp/ShapefileConverter.scala
- geomesa-convert/geomesa-convert-shp/src/main/scala/org/locationtech/geomesa/convert/shp/ShapefileConverterFactory.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
> GEOMESA-2361 - Improve reprojection handling in Shapefile ingest

- geomesa-convert/geomesa-convert-shp/src/main/scala/org/locationtech/geomesa/convert/shp/ShapefileConverter.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/FsDataStoreCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
- geomesa-utils/src/main/resources/org/locationtech/geomesa/utils/io/remote-prefixes.list
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/PathUtils.scala
> GEOMESA-2362 Improve handling for Hadoop URL Factory registration

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverters.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-text/src/main/resources/META-INF/services/org.locationtech.geomesa.convert.SimpleFeatureConverterFactory
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterFactory.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
- geomesa-convert/geomesa-convert-xml/src/main/resources/META-INF/services/org.locationtech.geomesa.convert.SimpleFeatureConverterFactory
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverterFactory.scala
- geomesa-convert/geomesa-convert-xml/src/test/scala/org/locationtech/geomesa/convert/xml/XmlConverterTest.scala
* DelimitedTextConverter skip-lines
* XmlConverter line-mode
> GEOMESA-2365 Converters - regressions in v1 processInput and processSingleInput

- docs/user/kafka/index_config.rst
- docs/user/kafka/usage.rst
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/index/SizeSeparatedBucketIndexSupport.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheImpl.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/EventTimeFeatureCacheTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheTest.scala
> GEOMESA-2322 Kafka - allow for configurable SSI tier sizes

- geomesa-convert/geomesa-convert-shp/src/main/scala/org/locationtech/geomesa/convert/shp/ShapefileConverterFactory.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/AbstractIngest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/PathUtils.scala
> GEOMESA-2369 - Various logging improvements

- build/cqs.tsv
- docs/common.py
- docs/user/kafka/install.rst
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerVersions.scala
- geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStoreTest.scala
- pom.xml
* Compile version set to 2.0.0
* scala-logging bumped to 3.8.0, slf4j bumped to 1.7.25
> GEOMESA-2295 Support for Kafka 1.1/2.0

- docs/user/convert/parsing_and_validation.rst
- geomesa-convert/geomesa-convert-common/src/main/resources/base-converter-defaults.conf
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureValidator.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/test/resources/META-INF/services/org.locationtech.geomesa.convert.SimpleFeatureValidator$ValidatorFactory
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/SimpleFeatureValidatorTest.scala
- geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/ValidatorTest.scala
- geomesa-convert/geomesa-convert-xml/src/main/resources/xml-converter-defaults.conf
- geomesa-tools/src/test/resources/convert/csv-data.csv
- geomesa-tools/src/test/resources/convert/json-data.json
- geomesa-tools/src/test/resources/convert/tsv-data.csv
* Added SPI loading for extending validators
> GEOMESA-2318 Converters - default to validator based on indices used

- docs/user/datastores/runtime_config.rst
- docs/user/upgrade.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/SchemaProperties.scala
> GEOMESA-2373 Adding flag for skipping distributed version load

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBasePlatform.scala
- geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa-site.xml.template
> GEOMESA-2379 Parameterize caching in hbase scans

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStore.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraFeatureCollection.scala
> GEOMESA-2390 Cassandra - add hook for query process visitor

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/converters/JavaTimeConverterFactory.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/converters/ConverterFactoriesTest.scala
* Supports conversions from Instant, ZonedDateTime, LocalDateTime and LocalDate
> GEOMESA-2372 GeoTools converters for java 8 time classes

- geomesa-accumulo/geomesa-accumulo-tools/bin/install-hadoop-accumulo.sh
- geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh
- geomesa-hbase/geomesa-hbase-tools/bin/install-hadoop.sh
> GEOMESA-2385 Updating install scripts for htrace 4

- geomesa-convert/geomesa-convert-all/src/test/resources/log4j.xml
- geomesa-convert/geomesa-convert-all/src/test/resources/reference.conf
- geomesa-convert/geomesa-convert-all/src/test/resources/sft_testsft.conf
- geomesa-convert/geomesa-convert-all/src/test/resources/testing.conf
- geomesa-convert/geomesa-convert-all/src/test/scala/org/locationtech/geomesa/convert/URLConfigProviderTest.scala
- geomesa-convert/geomesa-convert-all/src/test/scala/org/locationtech/geomesa/convert/testing/CompositeTextConverterTest.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/ConverterConfigLoader.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverters.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/SimpleFeatureConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/composite/CompositeConverterFactory.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypeLoader.scala
* Load composite converters from reference on classpath
> GEOMESA-2399 Load Composite Converters by ref

- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemReader.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/test/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemWriterTest.scala
> GEOMESA-2398 Allow next() without hasNext() in Orc FSDS reader

- geomesa-fs/geomesa-fs-gs-plugin/pom.xml
> GEOMESA-2386 Adding WPS module to FileSystem gs-plugin

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaFeatureWriter.scala
> GEOMESA-2408 KafkaFeatureWriter - implement Flushable

- geomesa-accumulo/geomesa-accumulo-tools/bin/install-hadoop-accumulo.sh
> GEOMESA-2416 Install htrace3 and 4 for accumulo and hadoop

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableDataStore.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreFactory.scala
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemDataStoreFactory.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduDataStoreFactory.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStoreFactory.scala
* Supports easier configuration through NiFi
> GEOMESA-2269 Standardizing static access to data store parameters

- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/data/AccumuloCreateSchemaCommand.scala
- geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraCreateSchemaCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/data/FsCreateSchemaCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/data/HBaseCreateSchemaCommand.scala
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/data/KafkaCreateSchemaCommand.scala
- geomesa-kudu/geomesa-kudu-tools/src/main/scala/org/locationtech/geomesa/kudu/tools/data/KuduCreateSchemaCommand.scala
- geomesa-lambda/geomesa-lambda-tools/src/main/scala/org/locationtech/geomesa/lambda/tools/data/LambdaCreateSchemaCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/CommonParams.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/CreateSchemaCommand.scala
> GEOMESA-2410 CreateSchema command always overrides shared table user data

- geomesa-hbase/geomesa-hbase-tools/bin/bootstrap-geomesa-hbase-aws.sh
> GEOMESA-2422 Fix HBase AWS Bootstrap Upload Path for S3

- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/index/BigtableFeatureIndex.scala
- geomesa-bigtable/geomesa-bigtable-spark/src/main/scala/org/locationtech/geomesa/bigtable/spark/BigtableSparkRDDProvider.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBasePlatform.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseArrowTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseColumnGroupsTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/HBaseSpatialRDDProvider.scala
* Explain now shows original ranges plus grouped ranges
> GEOMESA-2412,GEOMESA-2413 HBase - group ranges by shard prefix

- docs/user/filesystem/architecture.rst
- docs/user/filesystem/commandline.rst
- docs/user/filesystem/configuration.rst
- docs/user/filesystem/example.rst
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageMetadata.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/FileMetadataTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/MethodProfiling.scala
* Make method profiling methods protected scope
> GEOMESA-2421 FSDS - recursively examine metadata folder for updates

- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/ingest/KafkaIngestCommand.scala
> GEOMESA-2428 Kafka CLI ingest doesn't accept file paths

- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/StringFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
> GEOMESA-2432 Add strip-based string functions

- geomesa-spark/geomesa_pyspark/src/main/python/setup.py
* GEOMESA-2445 Pyspark - remove pyspark requires
> GEOMESA-2445 Pyspark - remove pyspark requires

- geomesa-accumulo/geomesa-accumulo-tools/bin/install-hadoop-accumulo.sh
- geomesa-accumulo/geomesa-accumulo-tools/bin/setup-namespace.sh
- geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh
- geomesa-hbase/geomesa-hbase-tools/bin/install-hadoop.sh
- geomesa-tools/bin/common-functions.sh
* more find commands that need -L switch
> GEOMESA-2443 Add -L switch so that find will follow-links

- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/SparkVersions.scala
> GEOMESA-2426 Fixing Spark version errors with logical relations

- geomesa-accumulo/geomesa-accumulo-security/src/main/scala/org/locationtech/geomesa/accumulo/security/VisibilityFilterFunction.scala
- geomesa-accumulo/geomesa-accumulo-security/src/test/scala/org/locationtech/geomesa/accumulo/security/VisibilityFilterFunctionTest.scala
> 1.3 - GEOMESA-2439 VisibilityFilterFunction for attributes

- build/cqs.tsv
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
- geomesa-web/geomesa-web-data/pom.xml
- geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/analytics/AnalyticEndpoint.scala
- geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/security/QueryAuditEndpoint.scala
- geomesa-web/geomesa-web-stats/pom.xml
- geomesa-web/geomesa-web-stats/src/main/scala/org/locationtech/geomesa/web/stats/GeoMesaStatsEndpoint.scala
> GEOMESA-2420 - Cache converter transformers, update json4s

- geomesa-accumulo/geomesa-accumulo-tools/src/main/resources/org/locationtech/geomesa/accumulo/tools/ingest-libjars.list
- geomesa-bigtable/geomesa-bigtable-tools/src/main/resources/org/locationtech/geomesa/bigtable/tools/ingest-libjars.list
- geomesa-fs/geomesa-fs-tools/src/main/resources/org/locationtech/geomesa/fs/tools/ingest-libjars.list
- geomesa-hbase/geomesa-hbase-tools/src/main/resources/org/locationtech/geomesa/hbase/tools/ingest-libjars.list
- geomesa-kafka/geomesa-kafka-tools/src/main/resources/org/locationtech/geomesa/kafka/tools/ingest-libjars.list
- geomesa-kudu/geomesa-kudu-tools/src/main/resources/org/locationtech/geomesa/kudu/tools/ingest-libjars.list
> GEOMESA-2453 Include commons-text in ingest-libjars lists.

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/EnrichmentCache.scala
> GEOMESA-2459 Remove guava dependency in ResourceLoadingCache

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/tube/TubeSelectProcessTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDensityFilterTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBasePartitioningTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala
> GEOMESA-2444 Never calculate exact counts unless configured to do so

- geomesa-accumulo/geomesa-accumulo-tools/src/main/resources/org/locationtech/geomesa/accumulo/tools/ingest-libjars.list
- geomesa-bigtable/geomesa-bigtable-tools/src/main/resources/org/locationtech/geomesa/bigtable/tools/ingest-libjars.list
- geomesa-fs/geomesa-fs-tools/src/main/resources/org/locationtech/geomesa/fs/tools/ingest-libjars.list
- geomesa-hbase/geomesa-hbase-tools/src/main/resources/org/locationtech/geomesa/hbase/tools/ingest-libjars.list
- geomesa-kafka/geomesa-kafka-tools/src/main/resources/org/locationtech/geomesa/kafka/tools/ingest-libjars.list
- geomesa-kudu/geomesa-kudu-tools/src/main/resources/org/locationtech/geomesa/kudu/tools/ingest-libjars.list
> GEOMESA-2462 Include commons-lang3 in ingest-libjars

- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/iterators/PlaybackIteratorTest.scala
> GEOMESA-2465 Build - removing strict timing check in PlaybackIteratorTest

- docs/bin/build-and-mirror.sh
> GEOMESA-2483 Docs - Fix build-and-mirror to delete old pages

- geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa-accumulo
> GEOMESA-2480 Fixing zookeeper jar lookup in geomesa-accumulo script

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/factory/FastFilterFactory.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/CqlTransformFilter.scala
> GEOMESA-2488 Add try/catch and cql copying in CqlTransformFilter

- geomesa-accumulo/geomesa-accumulo-distributed-runtime/pom.xml
- geomesa-hbase/geomesa-hbase-distributed-runtime/pom.xml
> GEOMESA-2491 Relocate json-smart to fix Hadoop classpath errors with JsonPath

- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/GeometricConstructorFunctionsTest.scala
> GEOMESA-2492 Fix y value for literal st_makePoint

- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
> GEOMESA-2466 Verify SimpleFeatureType parsing handles quoted keys

- pom.xml
> GEOMESA-2498 Fix inclusion of orc+hive jar in FS distribution

- geomesa-accumulo/geomesa-accumulo-tools/src/main/resources/org/locationtech/geomesa/accumulo/tools/ingest-libjars.list
- geomesa-bigtable/geomesa-bigtable-tools/src/main/resources/org/locationtech/geomesa/bigtable/tools/ingest-libjars.list
- geomesa-fs/geomesa-fs-tools/src/main/resources/org/locationtech/geomesa/fs/tools/ingest-libjars.list
- geomesa-hbase/geomesa-hbase-tools/src/main/resources/org/locationtech/geomesa/hbase/tools/ingest-libjars.list
- geomesa-kafka/geomesa-kafka-tools/src/main/resources/org/locationtech/geomesa/kafka/tools/ingest-libjars.list
- geomesa-kudu/geomesa-kudu-tools/src/main/resources/org/locationtech/geomesa/kudu/tools/ingest-libjars.list
* Fixes classpath for distributed ingest
> GEOMESA-2499 Add si-units to ingest-libjars

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/TypeInference.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
> GEOMESA-2495 Fix empty column binding in type inference

- geomesa-convert/geomesa-convert-simplefeature/src/main/scala/org/locationtech/geomesa/convert/simplefeature/SimpleFeatureSimpleFeatureConverterFactory.scala
- geomesa-convert/geomesa-convert-simplefeature/src/test/scala/org/locationtech/geomesa/convert/simplefeature/SimpleFeatureSimpleFeatureConverterTest.scala
> GEOMESA-2485 Fix SimpleFeatureSimpleFeatureConverter field transforms

- geomesa-hbase/geomesa-hbase-jobs/src/main/scala/org/locationtech/geomesa/hbase/jobs/HBaseIndexFileMapper.scala
> GEOMESA-2496 Set HBase conf in bulk ingest job

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/SpatioTemporalFilterStrategy.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/planning/QueryPlannerTest.scala
> GEOMESA-2501 Handle dates equal to the epoch in spatio-temporal strategies

- docs/_static/css/theme_custom.css
- docs/_templates/footer.html
- docs/_templates/layout.html
- docs/common.py
- docs/requirements.txt
- docs/user/datastores/index_config.rst
> GEOMESA-2489 Documentation light theme

- docs/common.py
- docs/user/accumulo/index.rst
- docs/user/accumulo/install.rst
- docs/user/cassandra/index.rst
- docs/user/cassandra/install.rst
- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- docs/user/convert/json.rst
- docs/user/datastores/analytic_queries.rst
- docs/user/datastores/filter_functions.rst
- docs/user/datastores/index.rst
- docs/user/geojson.rst
- docs/user/hbase/index.rst
- docs/user/hbase/index_config.rst
- docs/user/hbase/install.rst
- docs/user/kafka/index.rst
- docs/user/kafka/install.rst
- docs/user/kudu/index.rst
- docs/user/kudu/install.rst
- docs/user/merged_view.rst
- docs/user/spark/index.rst
- docs/user/spark/sparksql_functions.rst
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/CurrentDateFunction.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/FastProperty.scala
> GEOMESA-2208,2449,2470,2481,2497 Various documentation updates

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/CqlTransformFilter.scala
> GEOMESA-2505 Remove caching from CqlTransformFilter

- docs/_static/css/theme_custom.css
- docs/conf.py
* Font changed to roboto
* Removed unused css rules
> GEOMESA-2506 Documentation blue theme

- geomesa-tools/bin/common-functions.sh
> GEOMESA-2515 Add -p to log dir creation

- geomesa-features/geomesa-feature-all/src/test/scala/org/locationtech/geomesa/features/SimpleFeatureSerializersTest.scala
- geomesa-features/geomesa-feature-avro/src/main/scala/org/locationtech/geomesa/features/avro/serialization/AvroUserDataSerialization.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/GenericMapSerialization.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/package.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/serialization/KryoUserDataSerialization.scala
> GEOMESA-2514 Serialize bytes, UUIDs, geometries, lists in user data

- geomesa-stream/geomesa-stream-datastore/src/main/scala/org/locationtech/geomesa/stream/datastore/StreamDataStore.scala
- geomesa-stream/geomesa-stream-generic/src/main/scala/org/locationtech/geomesa/stream/generic/GenericSimpleFeatureStreamSourceFactory.scala
> GEOMESA-2487 Update StreamDataStore to use converters2

- docs/tutorials/index.rst
- docs/user/datastores/index.rst
- docs/user/filesystem/index.rst
- docs/user/getting_started.rst
- docs/user/install.rst
- docs/user/introduction.rst
> GEOMESA-2508 Add getting started documentation

- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/VersionRemoteCommand.scala
> GEOMESA-2512 Fix version-remote command version validation

- geomesa-features/geomesa-feature-all/src/test/resources/log4j.xml
- geomesa-features/geomesa-feature-all/src/test/scala/org/locationtech/geomesa/features/SimpleFeatureSerializersTest.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/AbstractSimpleFeature.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/ScalaSimpleFeature.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/TwkbSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/impl/KryoFeatureDeserialization.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/json/KryoJsonSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/serialization/KryoUserDataSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializerTest.scala
> GEOMESA-2513 Catch errors in deserialization of corrupt data

- geomesa-tools/bin/common-functions.sh
Needs to be back ported to 2.1
> GEOMESA-2528 Need to add the geomesa.log.dir to GEOMESA_OPTS

- docs/user/convert/delimited_text.rst
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterFactory.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
* Use an empty value for quote to disable it
> GEOMESA-2520 Text converters - support disabling quote mode

- docs/user/filesystem/sql.rst
- docs/user/spark/providers.rst
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
- geomesa-fs/geomesa-fs-spark-runtime/src/test/scala/org/locationtech/geomesa/fs/spark/FSSparkProviderTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-api/src/main/java/org/locationtech/geomesa/fs/storage/api/StorageMetadata.java
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/MetadataFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageMetadata.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/CompactCommand.scala
- geomesa-tools/conf/log4j.properties
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/fs/LocalDelegate.scala
- pom.xml
* Using FileContext.utils() is orders of magnitudes slower with large
numbers of files
* Fix USE_PROVIDED_FID behavior for FSDS FeatureStore
* Add docs on setting user.timezone for spark sql
> GEOMESA-2524 Hand-walk FSDS metadata directory

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/DeltaWriter.scala
> GEOMESA-2526 Fix arrow sort on dictionary-encoded field

- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/GeometricConstructorFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/util/GeometryUtils.scala
* Also fix parameter names to reflect actual order of coordinates
> GEOMESA-2529 SparkSql - add waypoints to st_makeBbox

- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageMetadata.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/FileMetadataTest.scala
Signed-off-by: 段卫东 <misslzyan108@gmail.com>
> GEOMESA-2532 fix bug: user-data not support Chinese character

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryStrategyDeciderTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastComparisonOperator.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastPropertyIsEqualTo.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastPropertyName.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastTemporalOperator.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/factory/FastFilterFactory.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/factory/FastFilterFactoryTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
- geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/HBaseSpatialRDDProvider.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/InMemoryQueryRunner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryRunner.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
* Default geotools CompareFilterImpl performs lots of instanceof checks
that make it extremely slow
> GEOMESA-2530 Add fast comparison filters

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryFilterSplitterTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/visitor/FilterExtractingVisitor.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/Z3Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3IndexValues.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3IndexValues.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/SpatioTemporalFilterStrategy.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/FeatureStateFactory.scala
> GEOMESA-2402 Use one-sided date filters in z-range planning

- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageMetadata.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/FileMetadataTest.scala
add reload for clear the cache when do test cases . 
Signed-off-by: 段卫东 <misslzyan108@gmail.com>
> GEOMESA-2537 fix:FileMetadataTest will not test correctly

- build/cqs.tsv
- docs/user/filesystem/sql.rst
- docs/user/spark/providers.rst
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemReader.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/jobs/OrcSimpleFeatureInputFormat.scala
- pom.xml
* Update to orc from 1.4.4 -> 1.5.4
* Use FastFilterFactory to optimize fs query filters
> GEOMESA-2525 Read orc timestamps as UTC time

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
> GEOMESA-2535 Kafka - kill initial load on datastore.dispose()

- geomesa-spark/geomesa_pyspark/src/main/python/geomesa_pyspark/__init__.py
> GEOMESA-2554 defer registrations of shapely udt until pyspark is imported

- docs/user/merged_view.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/resources/META-INF/services/org.locationtech.geomesa.index.view.MergedViewConfigLoader
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/index/view/MergedDataStoreViewTest.scala
- geomesa-index-api/src/main/java/org/locationtech/geomesa/index/view/MergedViewConfigLoader.java
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedDataStoreView.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedDataStoreViewFactory.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/classpath/ServiceLoader.scala
* Implement `org.locationtech.geomesa.index.view.MergedViewConfigLoader`
and make available via SPI loading
> GEOMESA-2540 Provide SPI configuration for MergedDataStoreView

- geomesa-convert/geomesa-convert-all/src/test/scala/org/locationtech/geomesa/convert/testing/CompositeTextConverterTest.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/StringFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
> GEOMESA-2549 String contains for Composite Converters

- docs/user/cli/export.rst
- docs/user/cli/ingest.rst
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/CommonParams.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ConvertCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/utils/ParameterConverters.scala
> GEOMESA-2561 CLI option to override converter error mode

- geomesa-fs/geomesa-fs-tools/bin/geomesa-fs
- geomesa-lambda/geomesa-lambda-tools/bin/geomesa-lambda
> GEOMESA-2558 Remove zookeeper references in FSDS CLI script

- docs/user/convert/composite.rst
- docs/user/convert/index.rst
- docs/user/convert/json.rst
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/ParsingConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/composite/CompositeConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/composite/CompositeConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/Predicate.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/PredicateParser.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/TransformerFunction.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/transforms/ExpressionTest.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/transforms/PredicateTest.scala
- geomesa-convert/geomesa-convert-json/src/main/resources/META-INF/services/org.locationtech.geomesa.convert2.SimpleFeatureConverterFactory
- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonCompositeConverter.scala
- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonCompositeConverterFactory.scala
- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonConverter.scala
- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonConverterFactory.scala
- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonFunctionFactory.scala
- geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonCompositeConverterTest.scala
- geomesa-convert/geomesa-convert-simplefeature/src/main/scala/org/locationtech/geomesa/convert2/simplefeature/FeatureToFeatureConverterFactory.scala
* Allow for converter predicates to use `==`, `<` etc
> GEOMESA-2456 Composite JSON converter

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreUuidTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/CqlTransformFilter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/filters/CqlTransformFilterTest.scala
> GEOMESA-1803 Set feature ID in HBase filters

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverterFactory.scala
> GEOMESA-2522 Specify id or user data field in converter error messages

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/FilterTransformIterator.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/CqlTransformFilter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
> GEOMESA-2564 Lazily evaluate feature ID in remote filtering

- CONTRIBUTING.md
- docs/user/convert/function_usage.rst
- docs/user/convert/xml.rst
- geomesa-convert/geomesa-convert-avro/src/main/scala/org/locationtech/geomesa/convert/avro/AvroFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractCompositeConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/composite/CompositeConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/package.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/CastFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/CollectionFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/DateFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/Expression.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/ExpressionParser.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/GeometryFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/IdFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/MathFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/MiscFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/StringFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/TransformerFunction.scala
- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonFunctionFactory.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterFactory.scala
- geomesa-convert/geomesa-convert-xml/src/main/resources/META-INF/services/org.locationtech.geomesa.convert2.SimpleFeatureConverterFactory
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlCompositeConverter.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlCompositeConverterFactory.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverter.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverterFactory.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlFunctionFactory.scala
- geomesa-convert/geomesa-convert-xml/src/test/scala/org/locationtech/geomesa/convert/xml/XmlCompositeConverterTest.scala
* Adds 'xpath' converter function for use in predicates
* Literal expressions are now pre-evaluated during expression parsing
> GEOMESA-2544 Composite XML converter

- geomesa-spark/geomesa-spark-core/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSpark.scala
SpatialRDD#schema may include user-data
Signed-off-by: 段卫东 <misslzyan108@gmail.com>
> GEOMESA-2576 Include user data in SpatialRDD schemas

- geomesa-accumulo/geomesa-accumulo-tools/pom.xml
- geomesa-bigtable/geomesa-bigtable-tools/pom.xml
- geomesa-cassandra/geomesa-cassandra-tools/pom.xml
- geomesa-fs/geomesa-fs-tools/pom.xml
- geomesa-hbase/geomesa-hbase-tools/pom.xml
- geomesa-kafka/geomesa-kafka-tools/pom.xml
- geomesa-kudu/geomesa-kudu-tools/pom.xml
- geomesa-lambda/geomesa-lambda-tools/pom.xml
- geomesa-tools/pom.xml
- pom.xml
2nd branch to try and get a valid PR in (signing issues).
> fcr_switch_to_gt_epsg_wkt2

- geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh
ref: https://geomesa.atlassian.net/browse/GEOMESA-2583
> GEOMESA-2583 Update AWS Hadoop JARs

- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/MetadataFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageMetadata.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/CompactCommand.scala
> GEOMESA-2580 FSDS - create single metadata file during compaction

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreUuidTest.scala
* Test currently fails with .pendingUntilFixed
* https://osgeo-org.atlassian.net/browse/GEOT-6251
>  GEOMESA-2562 Test for multiple ECQL functions OR'd together

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
> GEOMESA-2587 Catch errors in distributed aggregating scans

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraQueryPlan.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/utils/CassandraBatchScan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/package.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/utils/HBaseBatchScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/AbstractBatchScan.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/utils/AbstractBatchScanTest.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduQueryPlan.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/utils/KuduBatchScan.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisQueryPlan.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/util/RedisBatchScan.scala
> GEOMESA-2568 Ensure cancelled scans terminate all threads

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/data/FileSystemDataStore.scala
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/data/FileSystemDataStoreFactory.scala
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/data/FileSystemStorageManager.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-api/src/main/scala/org/locationtech/geomesa/fs/storage/api/package.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/jobs/StorageConfiguration.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/FileBasedMetadataFactory.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/JdbcMetadataFactory.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/package.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/FilteringReader.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FileSystemConverterJob.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
> GEOMESA-2570 FSDS - Set namespace in simple feature types

- docs/user/accumulo/commandline.rst
- docs/user/accumulo/raster.rst
- docs/user/appendix/metrics.rst
- docs/user/blobstore.rst
- docs/user/geoserver.rst
- docs/user/native_api.rst
- docs/user/upgrade.rst
- geomesa-accumulo/geomesa-accumulo-native-api/src/main/scala/org/locationtech/geomesa/accumulo/nativeapi/AccumuloGeoMesaIndex.scala
- geomesa-hbase/geomesa-hbase-native-api/src/main/scala/org/locationtech/geomesa/hbase/nativeapi/HBaseGeoMesaIndex.scala
- geomesa-metrics/src/main/scala/org/locationtech/geomesa/metrics/config/MetricsConfig.scala
- geomesa-metrics/src/main/scala/org/locationtech/geomesa/metrics/reporters/AccumuloReporter.scala
- geomesa-metrics/src/main/scala/org/locationtech/geomesa/metrics/reporters/DelimitedFileReporter.scala
- geomesa-metrics/src/main/scala/org/locationtech/geomesa/metrics/servlet/AggregatedMetricsFilter.scala
- geomesa-metrics/src/main/scala/org/locationtech/geomesa/metrics/servlet/StatusExposingServletResponse.scala
- geomesa-native-api/src/main/java/org/locationtech/geomesa/api/DefaultSimpleFeatureView.java
- geomesa-native-api/src/main/java/org/locationtech/geomesa/api/GeoMesaIndex.java
- geomesa-native-api/src/main/java/org/locationtech/geomesa/api/GeoMesaQuery.java
- geomesa-native-api/src/main/java/org/locationtech/geomesa/api/IndexType.java
- geomesa-native-api/src/main/java/org/locationtech/geomesa/api/SimpleFeatureView.java
- geomesa-native-api/src/main/java/org/locationtech/geomesa/api/ValueSerializer.java
- geomesa-native-api/src/main/scala/org/locationtech/geomesa/api/BaseBigTableIndex.scala
> GEOMESA-2581 Deprecate raster, native API, blob store, metrics

- build/cqs.tsv
- docs/user/kafka/confluent.rst
- docs/user/kafka/data.rst
- docs/user/kafka/index.rst
- geomesa-features/geomesa-feature-avro/src/main/scala/org/locationtech/geomesa/features/avro/AvroSimpleFeatureUtils.scala
- geomesa-kafka/geomesa-kafka-confluent/pom.xml
- geomesa-kafka/geomesa-kafka-confluent/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentFeatureSerializer.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentGeoMessageSerializer.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentMetadata.scala
- geomesa-kafka/geomesa-kafka-confluent/src/test/resources/log4j.xml
- geomesa-kafka/geomesa-kafka-confluent/src/test/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-confluent/src/test/scala/org/locationtech/geomesa/kafka/confluent/EmbeddedConfluent.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/utils/GeoMessageSerializer.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-dist/pom.xml
- geomesa-kafka/geomesa-kafka-gs-plugin/pom.xml
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/RecordVersions.scala
- geomesa-kafka/pom.xml
- pom.xml
* New data store for Kafka Confluent topics
* Infer a SimpleFeatureType from the Confluent Avro Schema Registry
* Update to Kafka 2.1
Co-authored-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>
Signed-off-by: David Seapy <ddseapy@ccri.com>
> GEOMESA-2500 Kafka - Support for reading Confluent Avro-serialized topics

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraIndexAdapter.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/AttributeColumnMapper.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/IdColumnMapper.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/SharedAttributeColumnMapper.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/Z2ColumnMapper.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/Z3ColumnMapper.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/package.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
> GEOMESA-2588 Cassandra - Fix range endpoint inclusivity

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraAttributeIndex.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraFeatureIndex.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraIdIndex.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraTieredFeatureIndex.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraXZ2Index.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraXZ3Index.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraZ2Index.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraZ3Index.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/package.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
> GEOMESA-2588 Cassandra - range endpoints do not account for exclusivity

- docs/user/spark/pyspark.rst
- geomesa-spark/geomesa_pyspark/src/main/python/geomesa_pyspark/__init__.py
> GEOMESA-2433 add convenience method to initialize UDT/F from geomesa_pyspark (and document)

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/ThreadedConsumer.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaCacheLoader.scala
> GEOMESA-2590 Threaded kafka consumer class

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastPropertyName.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-tools/bin/install-kafka.sh
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerVersions.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/ThreadedConsumer.scala
* Fix Kafka interop for consumer poll
> GEOMESA-2594 Move confluent deps off factory classpath

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreAlterSchemaTest.scala
- geomesa-accumulo/geomesa-accumulo-raster/src/main/scala/org/locationtech/geomesa/raster/index/RasterEntry.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/DateTimeScheme.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBasePartitioningTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/partition/TimePartition.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/Point2PointProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/transform/DateOffsetProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/tube/TubeBuilder.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/ManagePartitionsCommand.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/date/DateUtils.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Stat.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/DateParsing.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/StringSerialization.scala
fix it . 
Signed-off-by: 段卫东 <misslzyan108@gmail.com>
> GEOMESA-2596 fix SparkUtils#row2Sf. convert sql.Date to util.Date

- geomesa-bigtable/geomesa-bigtable-datastore/pom.xml
- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableIndexAdapter.scala
- geomesa-bigtable/geomesa-bigtable-datastore/src/test/resources/hbase-site.xml
- geomesa-bigtable/geomesa-bigtable-dist/pom.xml
- geomesa-bigtable/geomesa-bigtable-spark-runtime/pom.xml
- geomesa-bigtable/geomesa-bigtable-spark/src/main/java/org/locationtech/geomesa/bigtable/spark/BigtableInputFormatBase.java
- geomesa-bigtable/pom.xml
Updating Geomesa to use the latest Cloud Bigtable client and resolve bugs due to the old version
> GEOMESA-2260 Update to latest Cloud Bigtable client

- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseStatsAggregatorTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/LocalQueryRunner.scala
> GEOMESA-2606 Fix client-side stats for transform schemas

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/TestWithDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureCollection.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureStore.scala
> GEOMESA-2616 Use cached SFT when reading/writing through a FeatureSource

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/validators/IndexValidatorFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/validators/SimpleFeatureValidator.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/validators/package.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/validators/SimpleFeatureValidatorTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/SafeClose.scala
* SimpleFeatureConverter extends Closeable
> GEOMESA-2615 Converters - provide lifecycle for validators

- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/utils/SFTAttributes.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala
- geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLColumnsTest.scala
> GEOMESA-2610 SparkSQL - support timestamp attributes

- geomesa-accumulo/geomesa-accumulo-spark-runtime/pom.xml
- geomesa-bigtable/geomesa-bigtable-spark-runtime/pom.xml
- geomesa-fs/geomesa-fs-spark-runtime/pom.xml
- geomesa-hbase/geomesa-hbase-spark-runtime/pom.xml
- geomesa-kudu/geomesa-kudu-spark-runtime/pom.xml
> GEOMESA-2633 Shade and relocate json4s in spark runtime JARs

- geomesa-jupyter/geomesa-jupyter-leaflet/src/main/scala/org/locationtech/geomesa/jupyter/Leaflet.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala
> GEOMESA-2640 SparkSQL - Fix schema comparison on save

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraBackedMetadata.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/CachedLazyBinaryMetadata.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/CachedLazyMetadata.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/metadata/CachedLazyMetadataTest.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduBackedMetadata.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/collection/CloseableIterator.scala
> GEOMESA-2649 Queries don't consistently hit all partitioned tables

- docs/common.py
- docs/user/accumulo/install.rst
- docs/user/bigtable/install.rst
- docs/user/cassandra/install.rst
- docs/user/filesystem/install.rst
- docs/user/geoserver.rst
- docs/user/hbase/install.rst
- docs/user/kafka/install.rst
- docs/user/kudu/install.rst
- docs/user/lambda/install.rst
- docs/user/redis/install.rst
- docs/user/upgrade.rst
> GEOMESA-2626 Docs - specify geoserver compatible versions

- docs/user/accumulo/install.rst
- docs/user/bigtable/install.rst
- docs/user/cassandra/install.rst
- docs/user/filesystem/install.rst
- docs/user/geoserver.rst
- docs/user/hbase/install.rst
- docs/user/kafka/install.rst
- docs/user/kudu/install.rst
- docs/user/lambda/install.rst
- docs/user/redis/install.rst
- docs/user/upgrade.rst
> GEOMESA-2626 Docs - specify exact geoserver version

- docs/user/datastores/analytic_queries.rst
> GEOMESA-2622 Docs - Fix incorrect density scan example

- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterFactory.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
> GEOMESA-2650 CLI - Fix auto ingest for exported CSV files

- docs/tutorials/geomesa-hbase-on-cdh.rst
- docs/tutorials/index.rst
> GEOMESA-2651 Docs - indicate compatible CDH version in HBase tutorial

- build/cqs.tsv
- pom.xml
> GEOMESA-2653 Fix jackson version for GeoServer 2.15 plugins

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloIndexAdapter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/TestWithDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureWriterTest.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/IndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduIndexAdapter.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisIndexAdapter.scala
> GEOMESA-2654 ModifyFeatures can fail due to timestamp collision

- build/cqs.tsv
- pom.xml
> GEOMESA-2657 Upgrade to Spring 5.1.1

- build/cqs.tsv
- pom.xml
> GEOMESA-2636 Upgrade metrics to 3.2.6

- geomesa-lambda/geomesa-lambda-datastore/pom.xml
- geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/EmbeddedKafka.scala
- geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStoreTest.scala
- geomesa-lambda/pom.xml
> Back-port update geomesa-lambda to kafka 2.1

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreSortTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureOrdering.scala
> GEOMESA-2619 Fix sort by an attribute that is not returned

- geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa-accumulo
- geomesa-arrow/geomesa-arrow-tools/bin/geomesa-arrow
- geomesa-bigtable/geomesa-bigtable-tools/bin/geomesa-bigtable
- geomesa-cassandra/geomesa-cassandra-tools/bin/geomesa-cassandra
- geomesa-fs/geomesa-fs-tools/bin/geomesa-fs
- geomesa-gt/geomesa-gt-tools/bin/geomesa-gt
- geomesa-hbase/geomesa-hbase-tools/bin/geomesa-hbase
- geomesa-kafka/geomesa-kafka-tools/bin/geomesa-kafka
- geomesa-kudu/geomesa-kudu-tools/bin/geomesa-kudu
- geomesa-lambda/geomesa-lambda-tools/bin/geomesa-lambda
- geomesa-redis/geomesa-redis-tools/bin/geomesa-redis
> GEOMESA-2662 CUSTOM_JAVA_OPTS should override GEOMESA_JAVA_OPTS

- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableDataStore.scala
- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableDataStoreFactory.scala
- geomesa-bigtable/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableIndexAdapter.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraBackedMetadata.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/IndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
* Standardize table name lengths in index-api
> GEOMESA-2664 Truncate long table names for Bigtable

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Modes.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/test/resources/log4j.xml
- geomesa-convert/geomesa-convert-parquet/src/test/resources/log4j.xml
- geomesa-convert/geomesa-convert-xml/src/test/resources/log4j.xml
> GEOMESA-2660 Log warning for unused/undefined converter fields

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/TypeInference.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/factory/FastFilterFactory.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/FilterSplitter.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geohash/GeohashUtils.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/converters/FastConverter.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/DescriptiveStats.scala
> GEOMESA-2673 - Performance - don't return from scala iterable methods

- build/calculate-cqs.sh
- build/cqs.tsv
- geomesa-stream/pom.xml
-Tested with Apache Camel components Kafka and AWS Kinesis
Signed-off-by: Matthew Foreman <mforeman@ccri.com>
> GEOMESA-2674 Update Camel to 2.24.1 for geomesa-stream

- geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa-accumulo
- geomesa-arrow/geomesa-arrow-tools/bin/geomesa-arrow
- geomesa-bigtable/geomesa-bigtable-tools/bin/geomesa-bigtable
- geomesa-cassandra/geomesa-cassandra-tools/bin/geomesa-cassandra
- geomesa-fs/geomesa-fs-tools/bin/geomesa-fs
- geomesa-gt/geomesa-gt-tools/bin/geomesa-gt
- geomesa-hbase/geomesa-hbase-tools/bin/geomesa-hbase
- geomesa-kafka/geomesa-kafka-tools/bin/geomesa-kafka
- geomesa-kudu/geomesa-kudu-tools/bin/geomesa-kudu
- geomesa-lambda/geomesa-lambda-tools/bin/geomesa-lambda
- geomesa-redis/geomesa-redis-tools/bin/geomesa-redis
- geomesa-tools/bin/common-functions.sh
- geomesa-web/geomesa-web-data/src/test/scala/org/locationtech/geomesa/web/security/QueryAuditEndpointTest.scala
> GEOMESA-2681 CLI - support custom args to scala console

- docs/user/accumulo/install.rst
- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- docs/user/datastores/analytic_queries.rst
- docs/user/geoserver.rst
- docs/user/kafka/install.rst
- docs/user/lambda/install.rst
* Document `dateToString` converter function
* Document Stat implementing classes
* Make GeoServer section on EPSG-HSQL clearer
> GEOMESA-2676,GEOMESA-2613,GEOMESA-2516 Documentation updates

- docs/user/upgrade.rst
- geomesa-accumulo/geomesa-accumulo-dist/pom.xml
- geomesa-archetypes/geomesa-archetypes-gs-plugin/pom.xml
- geomesa-arrow/geomesa-arrow-dist/pom.xml
- geomesa-arrow/geomesa-arrow-dist/src/main/assemblies/component.xml
- geomesa-bigtable/geomesa-bigtable-dist/pom.xml
- geomesa-cassandra/geomesa-cassandra-dist/pom.xml
- geomesa-fs/geomesa-fs-dist/pom.xml
- geomesa-gt/geomesa-gt-dist/pom.xml
- geomesa-hbase/geomesa-hbase-dist/pom.xml
- geomesa-kafka/geomesa-kafka-dist/pom.xml
- geomesa-kudu/geomesa-kudu-dist/pom.xml
- geomesa-lambda/geomesa-lambda-dist/pom.xml
- geomesa-redis/geomesa-redis-dist/pom.xml
- geomesa-web/pom.xml
- pom.xml
> GEOMESA-2675 Don't deploy install tgz artifacts to Maven Central

- docs/user/convert/parsing_and_validation.rst
- geomesa-convert/geomesa-convert-common/src/main/resources/base-converter-defaults.conf
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractCompositeConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/metrics/ConverterMetrics.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/package.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterFactory.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverter.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverterFactory.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
* Rate, parse duration, convert duration, feature date, feature latency
> GEOMESA-2647 Converters - publish default metrics

- docs/user/redis/configuration.rst
- docs/user/redis/index_config.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloIndexAdapter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloWritableFeature.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/FilterHelperTest.scala
- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/accumulo/index/AttributeIndexJob.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraIndexAdapter.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/serialization/KryoUserDataSerialization.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-jobs/src/main/scala/org/locationtech/geomesa/hbase/jobs/HBaseIndexFileMapper.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/IndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/WritableFeature.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/MetadataBackedStats.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/DistributedLocking.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduIndexAdapter.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/RedisDataStore.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/RedisDataStoreFactory.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisAgeOff.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisIndexAdapter.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisWritableFeature.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/package.scala
- geomesa-redis/geomesa-redis-datastore/src/test/scala/org/locationtech/geomesa/redis/data/RedisDataStoreIntegrationTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/FeatureExpiration.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
* Add FeatureExpiration sft config
* Add type parameter to FeatureWrapper
> GEOMESA-2667 Redis - per-feature time-to-live

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloIndexAdapter.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/GenericMapSerialization.scala
- geomesa-security/src/main/java/org/locationtech/geomesa/security/SecurityUtils.java
- geomesa-security/src/main/scala/org/locationtech/geomesa/security/package.scala
> GEOMESA-2685 Intern visibility strings to reduce GC/heap pressure

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureCollection.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedFeatureSourceView.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/MinMaxProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/SamplingProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/StatsProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/UniqueProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/knn/KNearestNeighborSearchProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/query/JoinProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/query/ProximitySearchProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/query/QueryProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/query/RouteSearchProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/transform/BinConversionProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/tube/TubeSelectProcess.scala
> GEOMESA-2684 Bypass decorating feature collections to optimize WPS calls

- build/cqs.tsv
- docs/user/convert/parsing_and_validation.rst
- geomesa-convert/geomesa-convert-metrics-cloudwatch/pom.xml
- geomesa-convert/geomesa-convert-metrics-cloudwatch/src/main/resources/META-INF/services/org.locationtech.geomesa.convert2.metrics.ReporterFactory
- geomesa-convert/geomesa-convert-metrics-cloudwatch/src/main/scala/org/locationtech/geomesa/convert/metrics/cloudwatch/CloudWatchReporterFactory.scala
- geomesa-convert/pom.xml
- pom.xml
Signed-off-by: Forrest Feaser <forrest.feaser@ccri.com>
> GEOMESA-2683 Converter Metrics - AWS CloudWatch

- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParam.scala
> GEOMESA-2687 Kafka - Fix lookup of deprecated read back param

- README.md
- build/README.md
> GEOMESA-2691 Docs - Update sbt repos in README

- docs/user/upgrade.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/attribute/AttributeIndexKey.scala
> GEOMESA-2686 Support for indexing Timestamp attributes

- README.md
- docs/user/filesystem/install.rst
- geomesa-fs/geomesa-fs-dist/pom.xml
- geomesa-fs/geomesa-fs-dist/src/main/assemblies/component.xml
- pom.xml
> GEOMESA-2578 FSDS - include wps jar in download

- docs/user/convert/parsing_and_validation.rst
- geomesa-convert/geomesa-convert-common/pom.xml
- geomesa-convert/geomesa-convert-common/src/main/resources/META-INF/services/org.locationtech.geomesa.convert2.validators.SimpleFeatureValidatorFactory
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/validators/CqlValidatorFactory.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/validators/CqlValidatorTest.scala
* Usage: `cql(bbox(geom,-75,-90,-45,90))`
> GEOMESA-2286 Converter CQL validator

- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/ThreadedConsumer.scala
> GEOMESA-2690 Provide callback for handling kafka consumer errors

- geomesa-features/geomesa-feature-all/src/main/scala/org/locationtech/geomesa/features/SimpleFeatureSerializers.scala
- geomesa-memory/geomesa-cqengine-datastore/pom.xml
- geomesa-memory/geomesa-cqengine-datastore/src/main/scala/org/locationtech/geomesa/memory/cqengine/datastore/GeoCQEngineFeatureStore.scala
- geomesa-memory/geomesa-cqengine-datastore/src/test/scala/org/locationtech/geomesa/memory/cqengine/datastore/GeoCQEngineDataStoreTest.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaDataSource.scala
* Clean up spark serialization classes and schema loading
> GEOMESA-2641 Return immutable features from CQEngineDataStore

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraBackedMetadata.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/IndexAdapter.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduBackedMetadata.scala
> GEOMESA-2692 Kudu - Fix metadata scans for index tables

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/GroupBy.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/GroupByTest.scala
> GEOMESA-2672 Stats - skip null GroupBy values

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/knn/KNearestNeighborSearchProcessTest.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/knn/KNNQuery.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/knn/KNearestNeighborSearchProcess.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/knn/NearestNeighbors.scala
- geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/knn/KnnProcessTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geometry/DistanceCalculator.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeometryUtils.scala
> GEOMESA-284 Support non-geomesa feature collections for KNN process

- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/sft/package.scala
> GEOMESA-1614 CLI - use feature name for spec lookup

- docs/user/index.rst
- docs/user/install.rst
>  GEOMESA-2694 Docs - Update links to back-end stores in install page

- docs/common.py
- docs/tutorials/geomesa-blobstore-exif.rst
- docs/tutorials/geomesa-blobstore.rst
- docs/tutorials/geomesa-examples-authorizations.rst
- docs/tutorials/geomesa-examples-featurelevelvis.rst
- docs/tutorials/geomesa-quickstart-accumulo.rst
- docs/tutorials/geomesa-quickstart-hbase.rst
- docs/tutorials/geomesa-quickstart-lambda.rst
- docs/tutorials/geomesa-quickstart-storm.rst
- docs/tutorials/geomesa-raster.rst
- docs/tutorials/geomesa-tubeselect.rst
- docs/tutorials/spark.rst
- docs/user/accumulo/index.rst
- docs/user/accumulo/install.rst
- docs/user/hbase/index.rst
- docs/user/hbase/install.rst
- docs/user/spark/index.rst
- docs/user/spark/jupyter.rst
- docs/user/spark/pyspark.rst
> GEOMESA-2695 Docs - indicate explicit supported versions

- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/export/FsExportCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/export/FsPlaybackCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsIngestCommand.scala
> GEOMESA-2700 Set FSDS CLI libjars

- docs/user/convert/premade/marinecadastre-ais.rst
- geomesa-tools/conf/sfts/marinecadastre-ais/README.md
- geomesa-tools/conf/sfts/marinecadastre-ais/reference.conf
Adding docs and new SFT & converter to support CSV format data from
Marine Cadastre.
> GEOMESA-2702 Marine Cadastre AIS Converter for New CSV Format

- geomesa-convert/geomesa-convert-all/src/test/scala/org/locationtech/geomesa/convert/URLConfigProviderTest.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/ConverterConfigResolver.scala
- geomesa-utils/src/main/resources/META-INF/services/org.locationtech.geomesa.utils.geotools.SimpleFeatureTypeProvider
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/ArgResolver.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/ConfigSftParsing.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SftArgResolver.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypeLoader.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SftArgResolverTest.scala
* Allow specifying sft if there are multiple present
> GEOMESA-2710 Converters - resolve substitutions in config parsing

- docs/user/datastores/runtime_config.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseVersionAggregator.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/BinAggregatingScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/DensityScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/StatsScan.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/RenderingGrid.scala
* This allows the scans to check for cancellation, instead of running on
> GEOMESA-2711 Set batch size for all distributed queries

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseConnectionPool.scala
> GEOMESA-2712 HBase - use path handling for loading additional config files

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
> GEOMESA-2704 HBase - add notifier for canceled coprocessor calls

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
Signed-off-by: Michael Chehreh <mchehreh@ccri.com>
> GEOMESA-2719 Support opengis Function as expression in QueryPlanner

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/AccumuloVersion.scala
> GEOMESA-2717 Accumulo - add reflection support for v1.9

- docs/user/filesystem/usage.rst
- docs/user/hbase/usage.rst
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/data/FileSystemDataStoreFactory.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/FsDataStoreCommand.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseConnectionPool.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/resources/custom-site.xml
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/HadoopUtils.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/fs/HadoopDelegate.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/io/HadoopUtilsTest.scala
* New data store parameters "hbase.config.xml" and "fs.config.xml"
> GEOMESA-2716 Support embedded hadoop configs in HBase and FSDS

- docs/user/spark/jupyter.rst
> GEOMESA-2721 Can now `pip install toree`

- docs/user/nifi.rst
- docs/user/upgrade.rst
> GEOMESA-2720 Update NiFi docs

- build/cqs.tsv
- geomesa-hbase/geomesa-hbase-datastore/pom.xml
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseBackCompatibilityTest.scala
- geomesa-hbase/pom.xml
- pom.xml
> GEOMESA-2724 Fix HBase protobuf version

- geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/FileStreamInputFormat.scala
> GEOMESA-2729 Catch errors when checking stream position in input formats

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/utils/GeoMesaHBaseCallBack.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseConnectionPool.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureReader.scala
* Make HBaseConnectionPool lazily initialize
> GEOMESA-2718 HBase - Add server-side coprocessor timeouts

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/package.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/utils/GeoMesaHBaseCallBack.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
> GEOMESA-2718 HBase - Add server-side coprocessor timeouts 

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloIndexAdapter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloQueryPlan.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloJoinIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreStatsTest.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraIndexAdapter.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseStatsAggregatorTest.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduIndexAdapter.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduQueryPlan.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisIndexAdapter.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisQueryPlan.scala
> GEOMESA-2728 Fix scan reduce for exclusive filter

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/attribute/AttributeIndexKeySpace.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
> GEOMESA-2733 Fix ranges for attribute index without secondary key

- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/GeoCQEngine.scala
Signed-off-by: Rodolfo Totaro <rodolfo_totaro@yahoo.it>
> GEOMESA-2736 Fix during Geoindex initialization

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseConnectionPool.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/HadoopUtils.scala
> GEOMESA-2734 HBase - periodically relogin from keytab

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/ConverterConfigLoader.scala
> GEOMESA-2739 Converters - always reload converters from classpath

- docs/user/nifi.rst
> GEOMESA-2740 NiFi - docs for adding converters to the classpath

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverterFactory.scala
- geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/ConfConversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/sft/SimpleFeatureSpecConfig.scala
> GEOMESA-2741 Converters - Fix quote handling for feature user data keys

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
> GEOMESA-2744 HBase - Use absolute timeout to prevent coprocessor retries

- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/MiscFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/transforms/ExpressionTest.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/transforms/MiscFunctionFactoryTest.scala
Signed-off-by: Walter Schultz <wschultz@ccri.com>
> GEOMESA-2745 Add intToBoolean transform function

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Histogram.scala
> GEOMESA-2746 Stats - Include bounds on Histogram json

- docs/user/hbase/install.rst
- geomesa-accumulo/geomesa-accumulo-tools/bin/install-hadoop-accumulo.sh
- geomesa-gt/geomesa-gt-tools/bin/install-hadoop.sh
- geomesa-hbase/geomesa-hbase-gs-plugin/assembly.xml
- geomesa-hbase/geomesa-hbase-gs-plugin/pom.xml
- geomesa-hbase/geomesa-hbase-tools/bin/install-hadoop.sh
- geomesa-hbase/geomesa-hbase-tools/bin/install-shaded-hbase-hadoop.sh
- geomesa-kafka/geomesa-kafka-tools/bin/install-kafka.sh
- geomesa-lambda/geomesa-lambda-tools/bin/install-kafka.sh
- pom.xml
> GEOMESA-2742 HBase - use hbase-shaded client jar in gs-plugin

- docs/user/upgrade.rst
> GEOMESA-2742 Upgrade guide for GeoServer HBase plugin changes

- build/copyright/mitre.txt
- docs/user/spark/spark_jts.rst
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/package.scala
- pom.xml
Add GeoTools functions as Spark UDFs
> GEOMESA-2747, Include GeoTools functions as UDF for Spark

- CONTRIBUTING.md
- README.md
- build/README.md
- docs/user/introduction.rst
> GEOMESA-2749 Update links to user/dev lists

- build/copyright/mitre.txt
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/package.scala
Signed-off-by: Jeff Gold <jgold@mitre.org>
> GEOMESA-2750 - Updated header legal info based on stakeholder input.

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/BackCompatibilityTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/legacy/Z3IndexV5.scala
> GEOMESA-2752 Fix before/after date queries against Z3 index for 2.2 or before

- geomesa-memory/geomesa-cqengine/pom.xml
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/AbstractGeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/BucketGeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/GeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/QuadTreeGeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/STRtreeGeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/GeoCQEngine.scala
- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/GeoIndexFactory.scala
- geomesa-memory/geomesa-cqengine/src/test/scala/org/locationtech/geomesa/memory/cqengine/utils/GeoCQEngineIndexChoiceTest.scala
- geomesa-memory/geomesa-cqengine/src/test/scala/org/locationtech/geomesa/memory/cqengine/utils/GeoCQEngineTest.scala
> GEOMESA-2759 Fix CQEngine test intermittent failures

- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonFunctionFactory.scala
- geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
> GEOMESA-2756 Fix jsonList converter function for null elements

- docs/README.md
- docs/user/datastores/runtime_config.rst
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/package.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
> GEOMESA-2757 Fix ilike attribute scans

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BaseAggregatingIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/StatsIterator.scala
- geomesa-arrow/geomesa-arrow-datastore/src/main/scala/org/locationtech/geomesa/arrow/data/ArrowDataStore.scala
- geomesa-arrow/geomesa-arrow-datastore/src/main/scala/org/locationtech/geomesa/arrow/data/ArrowFeatureStore.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/DeltaWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/SimpleFeatureArrowIO.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/package.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseAggregator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseStatsAggregator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseVersionAggregator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseArrowTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/StatsScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/LocalQueryRunner.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/planning/LocalQueryRunnerTest.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaQueryRunner.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/TransientStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/LambdaDataStoreTest.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcess.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/ArrowExporter.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/IteratorStackCount.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/IteratorStackCountTest.scala
- pom.xml
> GEOMESA-2760 Fix arrow distributed scan memory leak

- geomesa-accumulo/geomesa-accumulo-datastore/pom.xml
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BaseAggregatingIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseAggregator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseVersionAggregator.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
> GEOMESA-2762 Add try/catch around underlying scans in aggregators

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/ShardStrategy.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/api/ShardStrategyTest.scala
> GEOMESA-2763 Handle Int.MinValue hash in shard strategy

- geomesa-tools/bin/common-functions.sh
> GEOMESA-2768 Fix install jars scripts for Maven central redirects

- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
> GEOMESA-2713 Unit test for Timestamp attribute stat support

- docs/user/spark/spark_jts.rst
> GEOMESA-2765 Fix coordinate order in st_makePoint example

- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/DeltaWriter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureReader.scala
> GEOMESA-2773 Fix asynchronous close of delta arrow results

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureReader.scala
* Prevent missing audit due to errors in closing query
> GEOMESA-2774 Execute query audits in finally block

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseMergedDataStoreViewTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseTestRunnerTest.scala
> GEOMESA-2764 HBase - fix merged data store view arrow queries

- build/cqs.tsv
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/pom.xml
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/s3/S3ObjectTagObserver.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/s3/S3VisibilityObserver.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/s3/S3VisibilityObserverFactory.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/metadata/FileBasedMetadataTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/metadata/JdbcMetadataTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/partitions/PartitionSchemeConfTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/partitions/PartitionSchemeTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/s3/S3VisibilityObserverTest.scala
- pom.xml
> GEOMESA-2735 FSDS - support S3 object tags

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraIndexAdapter.scala
> GEOMESA-2782 Exclude serialized feature column from Cassandra primary key

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BaseAggregatingIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseBinAggregator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseVersionAggregator.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/BinAggregatingScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/DensityScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/StatsScan.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/RenderingGrid.scala
> GEOMESA-2778 Check for timeouts in highly selective aggregating scans

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BaseAggregatingIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/DensityIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/resources/log4j.xml
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseDensityAggregator.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseVersionAggregator.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/BinAggregatingScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/DensityScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/StatsScan.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/result/ArrowAdapter.scala
* Move Arrow cleanup into aggregate lifecycle
> GEOMESA-2791 Arrow - Accumulo scans close prematurely

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndexFactory.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/classpath/ServiceLoader.scala
> GEOMESA-2793 Fix Accumulo VFS service loading for join indices

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowScan.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/iterators/ArrowScanTest.scala
> GEOMESA-2798 Arrow - multi-file scan returns repeated results

- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeReader.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/io/SimpleFeatureArrowFileTest.scala
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/GeometryFields.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/WKBGeometryVector.java
- geomesa-arrow/geomesa-arrow-jts/src/test/java/org/locationtech/geomesa/arrow/vector/GeometryVectorTest.java
> GEOMESA-2878 Add 'Geometry' column support to the Arrow format

- geomesa-hbase/geomesa-hbase-tools/conf-filtered/dependencies.sh
> GEOMESA-2908 Fix typo in HBase dependency script.

- docs/user/nifi.rst
> GEOMESA-2904 GeoMesa-NiFi should write GeoAvro files by attribute name

- docs/user/datastores/index_config.rst
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/splitter/DefaultSplitter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/splitter/SplitPatternParser.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/conf/splitter/DefaultSplitterTest.scala
> GEOMESA-2777 Support negative numbers in the default table splitter

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureCollection.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/GroupBy.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Stat.scala
* Add optimized implementations for average, count, groupBy, sum and unique
> GEOMESA-2885 Optimize geotools feature visitors

- docs/user/kafka/index_config.rst
- docs/user/kafka/usage.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreParams.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/FeatureStateFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCache.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheImpl.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/EventTimeFeatureCacheTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheTest.scala
> GEOMESA-2912 Kafka dynamic feature expiration

- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/serialization/KryoUserDataSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializerTest.scala
Signed-off-by: Michael Chehreh <mchehreh@ccri.com>
> GEOMESA-2913 Support Kryo deserialization of old geotools hint keys

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/visitor/QueryPlanFilterVisitor.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/IteratorCache.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeaturePropertyAccessor.scala
> GEOMESA-2915 Fix classloading of property accessors in Accumulo

- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/DateFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/transforms/ExpressionTest.scala
> GEOMESA-2920 dateToMillis converter function

- docs/user/geojson.rst
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/json/JsonPathFilterFunction.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/json/JsonPathFilterFunctionTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/filter/FilterFunctions.scala
> GEOMESA-2919 Separate attribute from path expression in JsonPath function

- docs/user/datastores/index_config.rst
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s3/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryInterceptor.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
* Add guard method to QueryInterceptor lifecycle
> GEOMESA-1605 Temporal query guard

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowDeltaIteratorTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/features/TransformTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Transform.scala
> GEOMESA-2924 Fix quoted transform expressions parsing

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conversions/StringOps.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/sft/SimpleFeatureSpecParser.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/conversions/StringOpsTest.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
> GEOMESA-2929 Preserve spaces in persisted feature type user data

- .gitignore
- docs/user/datastores/index.rst
- docs/user/datastores/index_config.rst
- docs/user/datastores/query_interceptor.rst
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/S2Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/Z2Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s2/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s3/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z2/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryInterceptor.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/GraduatedQueryGuard.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/TemporalQueryGuard.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/package.scala
- geomesa-index-api/src/test/resources/reference.conf
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
- geomesa-tools/conf/application.conf
> GEOMESA-2921 Implement a graduated spatial-temporal query guard

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/ConfigLoader.scala
- geomesa-utils/src/test/resources/geomesa-fake.xml
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/conf/ConfigLoaderTest.scala
> GEOMESA-2927 Final tags in geomesa-site.xml should be optional

- build/cqs.tsv
- docs/pom.xml
- geomesa-arrow/geomesa-arrow-jts/pom.xml
- pom.xml
> GEOMESA-2930 Update ant and junit versions

- docs/user/datastores/query_interceptor.rst
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/FullTableScanQueryGuard.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/GraduatedQueryGuard.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/TemporalQueryGuard.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
- geomesa-tools/conf/application.conf
> GEOMESA-2928 Implement full table scan query guard

- build/cqs.tsv
- pom.xml
> GEOMESA-2916 Upgrade Avro version to 1.8.2

- docs/tutorials/geomesa-quickstart-nifi.rst
- docs/user/datastores/index_config.rst
- docs/user/nifi.rst
> GEOMESA-2917 Docs for NiFi record-based processors

- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/BatchWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/ConcatenatedFileWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/io/BatchWriterTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/planning/LocalQueryRunnerTest.scala
> GEOMESA-2932 Fix Arrow memory leaks

- docs/user/datastores/query_interceptor.rst
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryProperties.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s2/S2Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s3/S3Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z2/XZ2Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z2/Z2Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/FullTableScanQueryGuard.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/GraduatedQueryGuard.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/TemporalQueryGuard.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/package.scala
- geomesa-index-api/src/test/resources/reference.conf
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/planning/guard/GraduatedQueryGuardTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/planning/guard/TemporalQueryGuardTest.scala
- pom.xml
> GEOMESA-2933 Ensure temporal query guards only trigger for temporal indices

- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/impl/KryoFeatureSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializerTest.scala
> GEOMESA-2934 Fix kryo serialization errors expanding large buffers

- docs/user/nifi.rst
* Added brief description of the GeoAvroRecordSetWriter
> GEOMESA-2906 NiFi - Create GeoAvroRecordSetWriter

- docs/user/geoserver.rst
- docs/user/upgrade.rst
> GEOMESA-2936 Docs for 3.1.0

- geomesa-kudu/geomesa-kudu-dist/src/main/assemblies/component.xml
- geomesa-kudu/geomesa-kudu-spark-runtime/pom.xml
> GEOMESA-2940 Fix Kudu spark runtime jar classpath

- geomesa-accumulo/geomesa-accumulo-tools/conf-filtered/accumulo-env.sh
- geomesa-tools/common-env/hadoop-env.sh
> GEOMESA-2939 Fix CLI hadoop conf dir classpath

- docs/tutorials/geomesa-quickstart-hbase.rst
- geomesa-hbase/geomesa-hbase-dist/src/main/assemblies/component.xml
> GEOMESA-2941 Fix HBase CLI tools classpath

- build/copyright/ccri-dstl-2020.txt
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/json/JsonPathFilterFunctionTest.scala
- pom.xml
> GEOMESA-2944: Add unit test for jsonPath applied to an array

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/concurrent/CachedThreadPool.scala
> GEOMESA-2950 Fix CachedThreadPool derefernce of completed tasks

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaFeatureWriter.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala
> GEOMESA-2953 Fix FeatureWriter comparision of provided FID hints

- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportJob.scala
> GEOMESA-2955 Export job output to existing directory

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/utils/GeoMessageProcessor.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/BaseThreadedConsumer.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/BatchConsumer.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/ThreadedConsumer.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/collection/ConcurrentHashSet.scala
> GEOMESA-2947 Kafka listener with offset tracking

- docs/user/filesystem/commandline.rst
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-api/src/main/scala/org/locationtech/geomesa/fs/storage/api/PartitionScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/FileBasedMetadata.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/AttributeScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/CompositeScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/DateTimeScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/FlatScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/SpatialScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/XZ2Scheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/Z2Scheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/utils/StorageUtils.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/partitions/PartitionSchemeTest.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/FsRunner.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsGeneratePartitionFiltersCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/status/FsDescribeSchemaCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/status/FsGetPartitionsCommand.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/attribute/AttributeIndexKey.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/attribute/AttributeIndexKeySpace.scala
> GEOMESA-2954 Calculate FSDS filters corresponding to partitions

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/AccumuloGeoMesaStats.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreStatsTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/DistributedRunnableStats.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/GeoMesaStats.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/MetadataBackedStats.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/NoopStats.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/UnoptimizedRunnableStats.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedQueryRunner.scala
- geomesa-index-api/src/test/resources/log4j.xml
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaStats.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/stats/TransientStats.scala
> GEOMESA-2979 Pass QUERY_INDEX hint to stats and getCount

- geomesa-arrow/geomesa-arrow-dist/pom.xml
- geomesa-arrow/geomesa-arrow-dist/src/main/assemblies/component.xml
> GEOMESA-2982 GeoMesa-Arrow command line tools dependency fixes

- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseArrowTest.scala
> GEOMESA-2993 Unit test for HBase Arrow delta scans with coprocessors disabled

- geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-21-datastore/src/main/scala/org/locationtech/geomesa/kafka21/KafkaConsumerFeatureSource.scala
> Switch Kafka 2.1's getCountInternal to make the other implementations.

- pom.xml
> GEOMESA-2987 Exclude logging files from test jars

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloQueryPlan.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraQueryPlan.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/QueryPlan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduQueryPlan.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisQueryPlan.scala
> GEOMESA-2978 Add reduce step to explain logging

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/VisibilitiesTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
> GEOMESA-2990 Fix update writes that only modify visibility

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseArrowTest.scala
> GEOMESA-2993 Fix HBase Arrow delta scans with coprocessors disabled

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastDWithin.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
> GEOMESA-3004 Fix dwithin string filters

- geomesa-accumulo/geomesa-accumulo-spark-runtime-accumulo1/pom.xml
- geomesa-accumulo/geomesa-accumulo-spark-runtime-accumulo2/pom.xml
- geomesa-bigtable/geomesa-bigtable-spark-runtime/pom.xml
- geomesa-fs/geomesa-fs-spark-runtime/pom.xml
- geomesa-gt/geomesa-gt-spark-runtime/pom.xml
- geomesa-hbase/geomesa-hbase-spark-runtime-hbase1/pom.xml
- geomesa-hbase/geomesa-hbase-spark-runtime-hbase2/pom.xml
- geomesa-kudu/geomesa-kudu-spark-runtime/pom.xml
> GEOMESA-3008 Relocate pureconfig in spark-runtimes for Zeppelin

- docs/user/hbase/usage.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreParams.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreParams.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/utils/HBaseVersions.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
> GEOMESA-3002 Support HBase table namespaces

- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/DateTimeScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/partitions/PartitionSchemeTest.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsGeneratePartitionFiltersCommand.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/DateParsing.scala
> GEOMESA-2996 Fix FSDS covering partitions for montly partition scheme

- .github/workflows/build-and-test.yml
- README.md
- benchmarks/pom.xml
- build/README.md
- build/change-scala-version.sh
- build/cqs.tsv
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryFilterSplitterTest.scala
- geomesa-jupyter/geomesa-jupyter-vegas/pom.xml
- geomesa-kafka/geomesa-kafka-confluent/pom.xml
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/utils/GeoMessageSerializer.scala
- geomesa-kafka/geomesa-kafka-tools/conf-filtered/dependencies.sh
- geomesa-lambda/geomesa-lambda-tools/conf-filtered/dependencies.sh
- geomesa-stream/geomesa-stream-generic/pom.xml
- geomesa-stream/geomesa-stream-generic/src/main/scala/org/locationtech/geomesa/stream/generic/GenericSimpleFeatureStreamSourceFactory.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/clearspring/StreamSummary.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geohash/BoundingBoxGeoHashIterator.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geohash/GeohashUtils.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/uuid/Z3FeatureIdGenerator.scala
- pom.xml
Co-authored-by: Jim Hughes <jhughes@ccri.com>
> GEOMESA-2984 Support for Scala 2.12

- docs/common.py
- geomesa-accumulo/geomesa-accumulo-spark/src/main/scala/org/apache/spark/deploy/SparkHadoopUtilShim.scala
- geomesa-accumulo/geomesa-accumulo-spark/src/main/scala/org/locationtech/geomesa/spark/accumulo/AccumuloSpatialRDDProvider.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/SparkVersions.scala
> GEOMESA-2981 Spark 3.0 support

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/MetadataBackedStats.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/stats/MetadataBackedStatsTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/BinnedArray.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Histogram.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Histogram.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/BinnedArrayTest.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/HistogramTest.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/StatTest.scala
* Separate binning logic so we don't have to allocate an array to check bounds
> GEOMESA-2986 Check for histogram bins when creating stats

- geomesa-tools/conf-filtered/geomesa-env.sh
> GEOMESA-3011 Fix match for CLI dependency jars

- geomesa-tools/conf-filtered/geomesa-env.sh
> GEOMESA-3010 Make CLI dependency update use unique temp file

- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeWriter.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/export/ExportCommandTest.scala
> GEOMESA-3020 Fix Arrow CLI export with dictionaries and no feature IDs

- docs/user/filesystem/metadata.rst
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-api/src/main/scala/org/locationtech/geomesa/fs/storage/api/StorageMetadata.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/FileBasedMetadata.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/FileBasedMetadataFactory.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/JdbcMetadata.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/MetadataJson.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/metadata/package.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/metadata/FileBasedMetadataTest.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/PartitionInputFormat.scala
> GEOMESA-3014 Compact rendering of FSDS metadata files

- docs/user/datastores/analytic_queries.rst
- docs/user/upgrade.rst
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryHints.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/LocalQueryRunner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedQueryRunner.scala
> GEOMESA-2970 Deprecate Arrow multi-file and double pass scans

- docs/user/cli/ingest.rst
- geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/ingest/IngestCommandTest.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsIngestCommand.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/ingest/HBaseBulkIngestCommand.scala
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/ingest/KafkaIngestCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/LocalConverterIngest.scala
> GEOMESA-2995 Explicit support for tools ingest from stdin

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseConnectionPool.scala
- geomesa-hbase/geomesa-hbase-jobs/src/main/scala/org/locationtech/geomesa/hbase/jobs/GeoMesaHBaseInputFormat.scala
- geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/HBaseSpatialRDDProvider.scala
* Fix synchronization of multiple confs if there are multiple workers in a single JVM
* Fix resolution of _HOST in principal names
> GEOMESA-3013,GEOMESA-3009,GEOMESA-2998 Support Kerberos in HBase Spark

- docs/user/spark/sparksql_functions.rst
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/GeometricConstructorFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/GeometricConstructorFunctionsTest.scala
> GEOMESA-2960 Add st_geomFromGeoJSON Spark UDF

- .github/workflows/build-and-test-2-12.yml
- .github/workflows/build-and-test-2.11.yml
> GEOMESA-3028 Split Github actions for Scala 2.11 and 2.12

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseConnectionPool.scala
> GEOMESA-2903 Log HBase zookeeper connection

- geomesa-tools/conf-filtered/geomesa-env.sh
> GEOMESA-3023 Fix download of scala-console

- .github/workflows/build-and-test-2.11.yml
- .github/workflows/build-and-test-2.12.yml
> GEOMESA-3028 Fix GitHub actions trigger

- docs/user/filesystem/install.rst
- geomesa-fs/geomesa-fs-tools/conf-filtered/dependencies.sh
> GEOMESA-3001 Upgrade install version for httpclient

- geomesa-features/geomesa-feature-avro/src/main/scala/org/locationtech/geomesa/features/avro/serialization/AvroUserDataSerialization.scala
> GEOMESA-3030 Lower log level on Avro PROVIDED_FID warning

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/QueryPlan.scala
- geomesa-redis/geomesa-redis-datastore/src/test/scala/org/locationtech/geomesa/redis/data/RedisDataStoreTest.scala
> GEOMESA-3034 Redis - Fix explain logging exceptions

- docs/tutorials/geomesa-examples-gdelt.rst
- docs/tutorials/geomesa-quickstart-storm.rst
- docs/user/accumulo/install.rst
- docs/user/filesystem/install.rst
- docs/user/lambda/install.rst
- docs/user/process.rst
- geomesa-archetypes/geomesa-archetypes-gs-plugin/pom.xml
> GEOMESA-3045 Include wps jar in gs-plugins

- docs/user/kafka/index.rst
- docs/user/kafka/transactional_writes.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaFeatureWriter.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/EmbeddedKafka.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
> GEOMESA-3044 Support Kakfa transactional writes

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
> GEOMESA-3048 Add readiness check for Kafka DataStore Initial Loads

- docs/user/filesystem/commandline.rst
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/FsDataStoreCommand.scala
* Makes it easier to set JSON in the user data
> GEOMESA-3051 Don't split FSDS --storage-opt on commas

- geomesa-accumulo/geomesa-accumulo-spark-runtime-accumulo1/pom.xml
- geomesa-accumulo/geomesa-accumulo-spark-runtime-accumulo2/pom.xml
- geomesa-bigtable/geomesa-bigtable-spark-runtime/pom.xml
- geomesa-fs/geomesa-fs-spark-runtime/pom.xml
- geomesa-gt/geomesa-gt-spark-runtime/pom.xml
- geomesa-hbase/geomesa-hbase-spark-runtime-hbase1/pom.xml
- geomesa-hbase/geomesa-hbase-spark-runtime-hbase2/pom.xml
- geomesa-kudu/geomesa-kudu-spark-runtime/pom.xml
* Include guava
* Relocate jackson and paranamer
> GEOMESA-3060 Fix FSDS Spark runtime jar classpath for EMR

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreStatsTest.scala
Signed-off-by: Kristin Cowalcijk <morisama@yeah.net>
> GEOMESA-3076 Do inexact checking for cardinality values in minmax stat

- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/CollectionFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/GeometryFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/MathFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/transforms/ExpressionTest.scala
* Add transformListItems function
* Update math and geometry functions to work with lists
* Update min/max to work with any comparables (i.e. dates)
> GEOMESA-3066 Better support for lists in converter API

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/validators/IndexValidatorFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/validators/package.scala
* Include the invalid value in the message
> GEOMESA-3081 Improve converter validation messages

- docs/user/accumulo/commandline.rst
- docs/user/cli/ingest.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloIndexAdapter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloWritableFeature.scala
- geomesa-accumulo/geomesa-accumulo-jobs/pom.xml
- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/accumulo/index/AttributeIndexJob.scala
- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/accumulo/mapreduce/GeoMesaAccumuloFileOutputFormat.scala
- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/accumulo/mapreduce/package.scala
- geomesa-accumulo/geomesa-accumulo-tools/conf-filtered/dependencies.sh
- geomesa-accumulo/geomesa-accumulo-tools/src/main/resources/org/locationtech/geomesa/accumulo/tools/accumulo-libjars.list
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/AccumuloRunner.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/ingest/AccumuloBulkIngestCommand.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/ingest/AccumuloIngestCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/FileSystemCompactionJob.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/FsCompactCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FileSystemConverterJob.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsIngestCommand.scala
- geomesa-tools/pom.xml
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/CommonParams.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/utils/StorageJobUtils.scala
- pom.xml
* New 'bulk-ingest' tools command for writing and loading RFiles directly
> GEOMESA-2111 Bulk ingest for Accumulo

- docs/user/accumulo/install.rst
- docs/user/bigtable/install.rst
- docs/user/hbase/install.rst
- docs/user/lambda/install.rst
- geomesa-bigtable/geomesa-bigtable-tools/conf-filtered/dependencies.sh
- geomesa-fs/geomesa-fs-tools/conf-filtered/dependencies.sh
- geomesa-gt/geomesa-gt-tools/bin/install-hadoop.sh
- geomesa-gt/geomesa-gt-tools/conf-filtered/dependencies.sh
- geomesa-hbase/geomesa-hbase-tools/conf-filtered/dependencies.sh
* hadoop-client is an aggregator jar with no code
> GEOMESA-3082 Remove hadoop-client from CLI dependencies

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloJoinIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/DtgAgeOffIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/DtgAgeOffTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/DtgAgeOffFilter.scala
> GEOMESA-3062 DtgAgeOff Filter does not work properly with join indexes

- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/RelationUtils.scala
Signed-off-by: Kristin Cowalcijk <morisama@yeah.net>
> GEOMESA-3129 Fixed how weighted partition envelopes were calculated

- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/vector/SimpleFeatureVectorTest.scala
> GEOMESA-3137 Arrow - UUID attribute types cause queries to fail

- build/copyright/ccri-dstl-mitre.txt
- build/copyright/ccri-mitre.txt
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloClientConfig.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-convert/geomesa-convert-avro-schema-registry/src/test/scala/org/locationtech/geomesa/convert/avro/registry/AvroSchemaRegistryConverterTest.scala
- pom.xml
The fix for GEOMESA-3162 on the main branch, see #2824 for details.
> GEOMESA-3162: Geomesa client configuration file properly loaded (main branch)

- build/copyright/ccri-dstl-mitre.txt
- build/copyright/ccri-mitre.txt
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloClientConfig.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-convert/geomesa-convert-avro-schema-registry/src/test/scala/org/locationtech/geomesa/convert/avro/registry/AvroSchemaRegistryConverterTest.scala
- pom.xml
The fix for GEOMESA-3162 on the 3.2.x branch, see #2824 for details.
> GEOMESA-3162: Geomesa client configuration file properly loaded (3.2 backport)

- build/copyright/ccri-dstl-mitre.txt
- build/copyright/ccri-mitre.txt
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloClientConfig.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-convert/geomesa-convert-avro-schema-registry/src/test/scala/org/locationtech/geomesa/convert/avro/registry/AvroSchemaRegistryConverterTest.scala
- pom.xml
The fix for GEOMESA-3162 on the 3.3.x branch, see #2824 for details.
> GEOMESA-3162: Geomesa client configuration file properly loaded (3.3 backport)

- docs/user/kafka/data.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
* "kafka.topic.config" in feature type user data can be used to specify topic compaction, retention, etc
> GEOMESA-3179 Kafka topic configuration

- geomesa-accumulo/geomesa-accumulo-tools/conf-filtered/dependencies.sh
- geomesa-gt/geomesa-gt-tools/bin/install-hadoop.sh
- geomesa-hbase/geomesa-hbase-tools/conf-filtered/dependencies.sh
- geomesa-kafka/geomesa-kafka-tools/conf-filtered/dependencies.sh
- geomesa-lambda/geomesa-lambda-tools/conf-filtered/dependencies.sh
Fixed https://geomesa.atlassian.net/browse/GEOMESA-3182
Corrected the version check so the Jute jar is installed.
> Fix for GEOMESA-3182

- docs/requirements.txt
- docs/user/nifi/converters.rst
* Fix sphinx docs build requirements version
> GEOMESA-3189 Docs for NiFi metrics reporters

- docs/user/datastores/reserved_words.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/FeatureUtils.scala
> GEOMESA-3194 Remove 'location' from reserved words

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureCollection.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
* Move optimized feature writer methods up to MetadataBackedStore
> GEOMESA-3197 Cache feature types for Kafka feature store

- build/cqs.tsv
- docs/user/kafka/commandline.rst
- docs/user/kafka/confluent.rst
- geomesa-features/geomesa-feature-avro/src/main/scala/org/locationtech/geomesa/features/avro/AvroSimpleFeatureTypeParser.scala
- geomesa-kafka/geomesa-kafka-confluent/pom.xml
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentFeatureSerializer.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentGeoMessageSerializer.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentMetadata.scala
- geomesa-kafka/geomesa-kafka-confluent/src/test/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStoreFactoryTest.scala
- geomesa-kafka/geomesa-kafka-confluent/src/test/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-confluent/src/test/scala/org/locationtech/geomesa/kafka/confluent/EmbeddedConfluent.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaFeatureWriter.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/utils/GeoMessageSerializer.scala
- geomesa-kafka/geomesa-kafka-tools/bin/install-confluent-dependencies.sh
- geomesa-kafka/geomesa-kafka-tools/conf-filtered/confluent-dependencies.sh
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaDataStoreCommand.scala
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaParams.scala
- geomesa-tools/bin/install-dependencies.sh
- pom.xml
* Add install script for confluent dependencies
* Add confluent integration to CLI tools
* Update confluent date parsing to use java.time instead of joda
> GEOMESA-3206 Kafka - support writes to Confluent Schema Registry topics

- docs/user/postgis/commandline.rst
- docs/user/postgis/index_config.rst
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
* Set default pages-per-range to 128
> GEOMESA-3221 Add docs for PostGIS partition-upgrade command

- docs/user/spark/pyspark.rst
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeomesaPysparkFunctions.scala
- geomesa-spark/geomesa_pyspark/src/main/python/geomesa_pyspark/scala/functions.py
- geomesa-spark/geomesa_pyspark/src/main/python/geomesa_pyspark/scala/udf.py
* updates the geomesa pyspark documentation
* wraps geomesa nullableUDFs as UserDefinedFunctions
* adds utility functions for creating scala UDFs in pyspark
* adds python wrappers for the geomesa UDFs
> GEOMESA-3211 Add Geomesa UDF support in PySpark

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyStatsIteratorTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/EmptyIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/StrategyDecider.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
* Add empty index plan so we can still apply reduce steps during scan execution
> GEOMESA-3234 Fix stats queries with Filter.EXCLUDE

- .github/workflows/build-and-test-2.11.yml
- .github/workflows/build-and-test-2.12.yml
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/MiniCluster.scala
- pom.xml
* Fix log4j error in failsafe plugin config
> GEOMESA-3241 CI - make integration tests fail the build

- docs/user/introduction.rst
Currently GeoMesa SQL is only known community module, hope there'll be more of them in the future.
> Doc: Added a subsection for community modules

- docs/tutorials/geomesa-quickstart-nifi.rst
Provide links that demarcate GDELT v1 and v2 data.
> Update NiFi Quick Start Docs

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/RedisDataStoreFactory.scala
- geomesa-security/src/main/java/org/locationtech/geomesa/security/AuthorizationsProvider.java
- geomesa-security/src/main/scala/org/locationtech/geomesa/security/AuthUtils.scala
- geomesa-security/src/main/scala/org/locationtech/geomesa/security/filter/VisibilityFilterFunction.scala
- geomesa-security/src/main/scala/org/locationtech/geomesa/security/package.scala
* `AuthorizationsProvider.apply` -> `AuthUtils.getProvider`
* Current method causes MethodInstanceRef error in Java 9+
> GEOMESA-2639 Move auth provider apply method

- docs/_static/launch.svg
- docs/_templates/footer.html
* Icon sourced from https://iconduck.com/icons/9369/launch with Apache 2 license
> Documentation - add link to edit page

- docs/tutorials/broadcast-join.rst
- docs/tutorials/dwithin-join.rst
- docs/tutorials/geomesa-examples-authorizations.rst
- docs/tutorials/geomesa-examples-featurelevelvis.rst
- docs/tutorials/geomesa-quickstart-accumulo.rst
- docs/tutorials/geomesa-quickstart-lambda.rst
- docs/user/ds_views.rst
- docs/user/lambda/usage.rst
- docs/user/spark/core.rst
- docs/user/spark/providers.rst
- docs/user/spark/pyspark.rst
- docs/user/spark/sparksql.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/TestWithDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/export/AccumuloExportCommandTest.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStoreFactory.scala
* Fix accumulo.instance.name param in docs
> Documentation updates for 4.0

- docs/user/postgis/geoserver.rst
- docs/user/postgis/install.rst
- geomesa-archetypes/geomesa-archetypes-gs-plugin/pom.xml
- geomesa-gt/geomesa-gt-dist/pom.xml
- geomesa-gt/geomesa-gt-gs-plugin/pom.xml
- geomesa-gt/pom.xml
- pom.xml
* Required for partitioned query optimizations
> GEOMESA-3262 Add partitioned PostGIS gs-plugin

- docs/common.py
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2630
> Disable website tracking

- docs/user/postgis/usage.rst
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreFactory.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreParams.scala
- geomesa-gt/geomesa-gt-partitioning/src/test/resources/testcontainers/Dockerfile
- geomesa-gt/geomesa-gt-partitioning/src/test/resources/testcontainers/initdb.sh
- geomesa-gt/geomesa-gt-partitioning/src/test/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreTest.scala
* New `idle_in_transaction_session_timeout` data store param
> GEOMESA-3272 Postgis - Add idle transaction timeout

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloQueryPlan.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloPartitioningTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBasePartitioningTest.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisQueryPlan.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala_2.12/org/locationtech/geomesa/utils/collection/CloseableIterator.scala
* Fixes `geomesa.partition.scan.parallel`
> GEOMESA-3291 Fix implementation of parallel table scans

- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisPsDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/test/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreTest.scala
* Set correct sub-type hints in feature type user data
> GEOMESA-3301 Partitioned PostGIS - fix Avro export

- docs/user/datastores/analytic_queries.rst
- docs/user/datastores/query_interceptor.rst
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/guard/GraduatedQueryGuard.scala
- geomesa-index-api/src/test/resources/reference.conf
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/planning/guard/GraduatedQueryGuardTest.scala
- Configurable subsample percentage based on size
- Configurable subsample attribute name
- Mix duration and percentage/attribute guard modes
> GEOMESA-3311 Add subsampling to GraduatedQueryGuard

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloEventWriter.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/data/AddIndexCommand.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/DeltaWriter.scala
- geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/serde/Version1BackwardsCompatTest.scala
- geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/serde/Version3CompatTest.scala
- geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/serialization/SimpleFeatureDatumReaderTest.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/impl/LazyDeserialization.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseBackedMetadata.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/bin/BinSorter.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/ArgResolver.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/ByteArrays.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/LegacyYearZ3SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/LegacyZ3SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/Z3SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/zorder/sfcurve/ZN.scala
* These constructs are no longer supported in Scala 3
* See https://docs.scala-lang.org/scala3/guides/migration/incompat-dropped-features.html
> GEOMESA-3323 Remove do/whiles and early initializers

- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonConverterFactory.scala
- geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverterFactory.scala
* Remove unnecessary identity transforms
> GEOMESA-3347 Fix spurious warning for JSON type inference

- docs/user/kafka/commandline.rst
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaRunner.scala
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/ingest/KafkaPlaybackCommand.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/iterators/SimplePlaybackIterator.scala
- geomesa-utils-parent/geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/iterators/SimplePlaybackIteratorTest.scala
This is currently missing a few of the niceties I'd want, like a way to skip headers, but I think it's sufficient for an MVP implementation.
> GEOMESA-3353 Add geomesa-kafka playback command

- docs/user/accumulo/commandline.rst
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/ingest/AccumuloBulkCopyCommand.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
* Support for non-partitioned stores
* Support for resuming a failed run
> GEOMESA-3383 Accumulo - Bulk copy enhancements

- geomesa-accumulo/geomesa-accumulo-datastore/pom.xml
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/SchemaCopier.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/ingest/AccumuloBulkCopyCommand.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/stats/AccumuloQueryAuditCommand.scala
- geomesa-arrow/geomesa-arrow-tools/src/main/scala/org/locationtech/geomesa/arrow/tools/status/ArrowDescribeSchemaCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/status/FsDescribeSchemaCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/status/FsGetPartitionsCommand.scala
- geomesa-jobs/pom.xml
- geomesa-tools/common-env/log4j.properties
- geomesa-tools/pom.xml
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/package.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/DescribeSchemaCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/EnvironmentCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/GetTypeNamesCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/utils/DistributedCopy.scala
- geomesa-utils-parent/geomesa-hadoop-utils/pom.xml
- geomesa-utils-parent/geomesa-hadoop-utils/src/main/scala/org/locationtech/geomesa/utils/hadoop/DistributedCopyOptions.scala
* Make tools loggers use scalalogging
> GEOMESA-3383 Accumulo - Move core bulk copy logic out of CLI tools

- geomesa-metrics/geomesa-metrics-micrometer/src/main/scala/org/locationtech/geomesa/metrics/micrometer/MicrometerSetup.scala
- geomesa-metrics/geomesa-metrics-micrometer/src/main/scala/org/locationtech/geomesa/metrics/micrometer/RegistryFactory.scala
- geomesa-metrics/geomesa-metrics-micrometer/src/main/scala/org/locationtech/geomesa/metrics/micrometer/cloudwatch/CloudwatchFactory.scala
- geomesa-metrics/geomesa-metrics-micrometer/src/main/scala/org/locationtech/geomesa/metrics/micrometer/prometheus/PrometheusFactory.scala
* Permits using metrics without unused dependencies on the classpath
> GEOMESA-3400 Configurable Micrometer metrics - separate classloading

- docs/user/datastores/index_config.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
* `index.table.prefix` user data specifies the prefix to use
> GEOMESA-3415 Allow for custom index table prefixes

- docs/user/datastores/runtime_config.rst
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/converters/FastConverter.scala
* Add reloading cache for type conversions to mitigate transitory classpath issues
> GEOMESA-3416 Log more details when type conversion fails

- docs/tutorials/geomesa-quickstart-nifi.rst
- docs/user/nifi/examples.rst
- docs/user/nifi/install.rst
- docs/user/upgrade.rst
- pom.xml
* Enforce jdk.version for releases
> GEOMESA-3465 Update docs for NiFi 2

- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
Geomesa ticket:
https://geomesa.atlassian.net/browse/GEOMESA-3471
> GEOMESA-3471: partitioned postgis: SFT attribute userdata to include "index" flag

- docs/user/redis/commandline.rst
- geomesa-redis/geomesa-redis-tools/src/main/scala/org/locationtech/geomesa/redis/tools/RedisDataStoreCommand.scala
@elahrvivaz This was missed in 5.3.0. Let me know what additions need to be made.
> GEOMESA-3484-add-cluster-param

- docs/user/postgis/index_config.rst
- docs/user/upgrade.rst
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/package.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/CompactPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/DropAgedOffPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/MergeWriteAheadPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/RollWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/AnalyzeQueueTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/PartitionTables.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/PartitionTablespacesTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/SortQueueTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/UserDataTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/WriteAheadTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/test/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreTest.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
* Deprecate `partition_tablespaces` table
> GEOMESA-3503 Postgis - Support updating partition size through user data

- docs/user/postgis/index.rst
- docs/user/postgis/multi_tenancy.rst
- docs/user/postgis/usage.rst
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreFactory.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreParams.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/functions/LogCleaner.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/functions/TruncateToPartition.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/functions/TruncateToTenMinutes.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/package.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/AnalyzePartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/CompactPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/DropAgedOffPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/MergeWriteAheadPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionMaintenance.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/RollWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/DeleteTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/InsertTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/UpdateTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/WriteAheadTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/test/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreTest.scala
* New data store parameter `read_access_roles`
* Add schema qualifier to all functions
> GEOMESA-3506 Partitioned Postgis - Improve multi-tenancy on shared tables

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/ZLineTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
- geomesa-features/geomesa-feature-all/src/test/scala/org/locationtech/geomesa/features/SerializationTester.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeatureTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/GenerateParquetFiles.scala
- geomesa-hbase/geomesa-hbase-rpc/src/test/scala/org/locationtech/geomesa/hbase/rpc/filter/CqlTransformFilterTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/utils/bin/BinSorterTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/DensityProcessTest.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/stats/StatsHistogramCommandTest.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GenerateRichFeatureModels.scala
- geomesa-utils-parent/geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/bin/BinaryEncodeCallbackTest.scala
- geomesa-utils-parent/geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/index/SynchronizedQuadtreeTest.scala
- geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/Z2Test.scala
- geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/Z3Test.scala
> GEOMESA-3513 Kafka - Fix initial load on mixed empty and full topic partitions

- geomesa-spark/geomesa-spark-test-with-sedona/pom.xml
- geomesa-spark/geomesa-spark-test/pom.xml
* To include them in scoverage reports
> Switch Spark test modules to jar packaging
