pom.xml

Added verbose option, updated dateFormat, placed git.properties file in {project.build.outputDirectory}
Signed-off-by: Jake Kenneally <jdk2pq@ccri.com>

GEOMESA-772 Update git-commit-id-plugin configuration

---

README.md

Signed-off-by: Jake Kenneally <jdk2pq@ccri.com>

GEOMESA-827 Update README for 1.1.x releases/versions

---

geomesa-kafka/geomesa-kafka-datastore/README.md
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaDataStoreHelper.scala
geomesa-kafka/geomesa-kafka-geoserver-plugin/pom.xml
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/java/org/locationtech/geomesa/kafka/plugin/GeomesaKafkaProcess.java
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/java/org/locationtech/geomesa/kafka/plugin/GeomesaKafkaProcessFactory.java
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/resources/META-INF/services/org.geotools.process.ProcessFactory
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/resources/applicationContext.xml
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/scala/org/locationtech/geomesa/kafka/plugin/KafkaProcessFactory.scala
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/scala/org/locationtech/geomesa/kafka/plugin/ReplayKafkaDataStoreProcess.scala
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/scala/org/locationtech/geomesa/kafka/plugin/ReplayKafkaLayerReaperProcess.scala
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/test/resources/kafkaPluginTestApplicationContext.xml
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/test/scala/org/locationtech/geomesa/kafka/plugin/KafkaPluginSpringTest.scala

* Added WPS to create replay layer
* Added reaper process to delete replay layers a configurable number of hours after creation
* Updated Kafka Data Store readme
Signed-off-by: Michael Matz <mmatz@ccri.com>

GEOMESA-780 Kafka Data Store Replay

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureWriter.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoder.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/ReplayKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/LiveFeatureCacheTest.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/ReplaySnapshotFeatureCacheTest.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/SimpleFeatureMatchers.scala
geomesa-stream/geomesa-stream-datastore/src/main/scala/org/locationtech/geomesa/stream/datastore/StreamDataStore.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GridSnap.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/BucketIndex.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/QuadTreeFeatureStore.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/SpatialIndex.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/SynchronizedQuadtree.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/WrappedQuadtree.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/GridSnapTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/index/BucketIndexTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/index/QuadTreeFeatureStoreTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/index/SynchronizedQuadtreeTest.scala

* Also fixing potential NPE in BinaryOutputEncoder

GEOMESA-837 Switching Kafka DS to use bucket index instead of JTS quadtree

---

geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializer.scala
geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeatureTest.scala
geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializerTest.scala

GEOMESA-846  Allowing for appending of attributes to simple features types with kryo encoding

---

geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/LiveKafkaConsumerFeatureSourceTest.scala
geomesa-kafka/geomesa-kafka-geoserver-plugin/README.md
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/resources/org/locationtech/geomesa/kafka/plugin/KafkaDataStoreEditPanel.html
geomesa-kafka/geomesa-kafka-geoserver-plugin/src/main/scala/org/locationtech/geomesa/kafka/plugin/KafkaDataStoreEditPanel.scala

GEOMESA-850 Allowing configuration of kafka DS timeout

---

geomesa-accumulo/geomesa-accumulo-datastore/pom.xml
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/AccumuloVersion.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/TimestampRangeIterator.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapred/GeoMesaInputFormat.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapred/InputFormatBaseAdapter.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/GeoMesaInputFormat.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/InputFormatBaseAdapter.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/scalding/taps/AccumuloTap.scala
geomesa-plugin/src/main/scala/org/locationtech/geomesa/plugin/ui/GeoMesaDataStoresPage.scala
geomesa-tools/pom.xml
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/Utils.scala
pom.xml

GeoMesa artifacts should work for Accumulo 1.5 and 1.6.
To test the build against Accumulo 1.5, build with 'mvn clean install -Daccumulo-1.5'.

GEOMESA-866 Add support for Accumulo 1.6

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/accumulo.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureSource.scala

* Changes the default behavior to return full counts with getCount.

GEOMESA-893 Return correct counts by default

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeneralShapefileIngest.scala

Adds transactions to shapefile ingest for massive speed increase

GEOMESA-925 Speed up shapefile ingest

---

geomesa-convert/README.md
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
geomesa-convert/geomesa-convert-json/pom.xml
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonFunctionFactory.scala
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-json/src/test/resources/log4j.xml
geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala

GEOMESA-924 Adding wkt and geojson geometry object support

---

geomesa-tools/src/main/resources/org/locationtech/geomesa/tools/ingest-libjars.list

GEOMESA-1093 Adding sfcurve to libjars

---

docs/user/commandline_tools.rst
geomesa-tools/README.md
geomesa-tools/bin/geomesa
geomesa-tools/src/main/resources/org/locationtech/geomesa/tools/ingest-libjars.list
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/commands/IngestCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/ConverterIngest.scala

* Enables use of S3 for ingest in distributed mode
* Utilizes S3N FileSystem from Hadoop
Stacks on top of #804

 GEOMESA-1048 S3 for ingest

---

geomesa-tools/bin/geomesa

Signed-off-by: Jason Brown <jason.brown@ccri.com>

GEOMESA-1106 Reinstate hadoopDirs from PR805

---

README.md
build/README.md
pom.xml

GEOMESA-1117 Fixing artifact links

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/FeatureExporter.scala

GEOMESA-1121 FeatureExporter reports counts as an Int which can overflow

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/ConverterConfigLoader.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverters.scala

GEOMESA-1208 Log Converter/SFT SPI loading

---

geomesa-gs-plugin/geomesa-hbase-gs-plugin/README.md
geomesa-gs-plugin/geomesa-hbase-gs-plugin/pom.xml
geomesa-hbase/README.md
geomesa-hbase/geomesa-hbase-datastore/README.md
geomesa-hbase/geomesa-hbase-datastore/pom.xml
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureReader.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureSource.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/resources/hbase-site.xml
pom.xml

* Update HBase version to 1.1.5.
* For queries without spatial and fully-bounded temporal components,
falls back to a full table scan
* Basic documentation in the form of READMEs.
With significant contributions by James Hughes (jnh5y@ccri.com).

GEOMESA-1211 Update HBase support to HBase 1.1.5

---

README.md

GEOMESA-1218 Bump dev version to 1.2.3

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/BinnedArray.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/RangeHistogram.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/BinnedArrayTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/RangeHistogramTest.scala

GEOMESA-1216 Fixing binned array bounds/merge

---

geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaDataStoreSchemaManager.scala

Signed-off-by: Alex Tatusko <atatusko@ccri.com>

GEOMESA-1192 Fix KafkaDataStore's getTypeNames method

---

docs/user/installation_and_configuration.rst
geomesa-gs-plugin/geomesa-accumulo-gs-plugin/README.md
geomesa-tools/bin/install-hadoop-accumulo.sh
pom.xml

GEOMESA-1225 Install Recommended Hadoop and Accumulo Jars

---

docs/user/commandline_tools.rst
geomesa-tools/README.md
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/GetSftCommand.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala

GEOMESA-978 Encode SFTs in TypeSafe Config

---

docs/_static/css/theme_custom.css
docs/common.py
docs/developer/index.rst
docs/index.rst
docs/tutorials/index.rst
docs/user/index.rst

* Change background of admonition boxes so they are more readable
* Make highlighted text sections off-white
* Fix colors of table rows

GEOMESA-1222 Docs: fix CSS styling issues

---

docs/tutorials/geomesa-examples-authorizations.rst

GEOMESA-1222 Clarifying service provider requirements

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFilterTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/package.scala

edit: this needs to stack on top of the stats PR - I'll wait until that is merged to rebase.

GEOMESA-1228 Fixing CQL functions in queries

---

geomesa-compute/src/main/scala/org/locationtech/geomesa/compute/spark/GeoMesaSpark.scala
geomesa-compute/src/test/scala/org/locationtech/geomesa/compute/spark/GeoMesaSparkTest.scala

GEOMESA-1240 Allow initialization of multiple datastores in spark

---

docs/user/commandline_tools.rst
geomesa-tools/README.md
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/stats/StatsCommand.scala

GEOMESA-1236 Changing stats exact flag to '--no-cache'

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/stats/StatsEnumerateCommand.scala

GEOMESA-1234 Enumeration stat secondary sorting

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/BinnedArray.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/BinnedArrayTest.scala

GEOMESA-1233 Fixing unequal string bounds length

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/stats/StatsHistogramCommand.scala

GEOMESA-1235 Fixing key and counts for histogram ascii map

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/BinLineStringTest.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/common/KeywordParamSplitter.scala

GEOMESA-1244 Attempting to fix BinLineStringTest

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala

GEOMESA-1246 Fixing converter error logging

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala

GEOMESA-1231 Expose Zookeeper timeout as a System property

---

geomesa-dist/pom.xml
geomesa-dist/src/main/assemblies/component.xml

GEOMESA-1259 Add geomesa-process jar to dist

---

geomesa-tools/emr4/README.md

GEOMESA-1261 Replace carriage returns with newlines

---

geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/JobUtils.scala
geomesa-tools/bin/geomesa
geomesa-tools/conf/application.conf
geomesa-tools/examples/ingest/csv/example.conf
geomesa-tools/examples/ingest/json/example_multi_line.conf
geomesa-tools/src/main/assemblies/component.xml
geomesa-tools/src/main/resources/org/locationtech/geomesa/tools/ingest-libjars.list
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/ingest/AbstractIngestJob.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/classpath/ClassPathUtils.scala

GEOMESA-1266 Fix libjars, prioritize guava 17 for mapred

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/GeoMesaMetadata.scala
pom.xml

GEOMESA-1268 Removing guava cache putAll call for guava 11 compatibility

---

geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/JobUtils.scala
geomesa-tools/src/main/assemblies/component.xml
geomesa-tools/src/main/resources/org/locationtech/geomesa/tools/ingest-libjars.list

GEOMESA-1270 Revert Guava 17 MapReduce usage

---

geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/KafkaDataStoreTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/QuadTreeFeatureStore.scala

GEOMESA-1255 Fixing kafka data store spatial AND filtering

---

geomesa-process/README.md

GEOMESA-1260 Document GeoMesa Process deployment

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/RecordIdxStrategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/DensityIteratorTest.scala

GEOMESA-1271 Adding density iterator to record strategy

---

docs/tutorials/_static/geomesa-examples-gdelt/heatmap.sld
docs/tutorials/_static/geomesa-quickstart-storm/heatmap.sld
geomesa-tools/README.md

Push any doc change to this branch before the release

Testing fixes for 1.2.3 release

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala

GEOMESA-1273 Fixing handling of partially out-of-world geometries

---

docs/user/installation_and_configuration.rst
geomesa-gs-plugin/geomesa-accumulo-gs-plugin/README.md
geomesa-tools/bin/install-hadoop-accumulo.sh

GEOMESA-1279 Install stats dependencies

---

docs/user/installation_and_configuration.rst
docs/user/jobs.rst

Moves runtime installation before command-line tools install.

GEOMESA-1269 Docs: Accumulo runtime required for ingest

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/accumulo.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/index.scala

GEOMESA-1280 Fixing evaluation of exact count query hint

---

README.md
geomesa-process/src/main/scala/org/locationtech/geomesa/process/Point2PointProcess.scala
geomesa-process/src/test/scala/org/locationtech/geomesa/process/Point2PointProcessTest.scala

This is an important client fix.

GEOMESA-1285 Always set SFT on P2P results

---

geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStore.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala

Signed-off-by: Tadashi Igarashi <tadashi.simepar@gmail.com>

Fix SimpleFeatureType mapping to Cassandra types

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFilterTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala

GEOMESA-1292 Fixing assignment of geometry as an indexed attribute

---

geomesa-tools/src/test/resources/examples/example1.conf
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/GeoMesaSchemaValidator.scala

GEOMESA-712 Throwing exception on reserved words in schema

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureSource.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/JoinProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/unique/UniqueProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/resources/process/join.xml
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/JoinProcessTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoder.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoderTest.scala
geomesa-process/README.md
geomesa-process/src/main/scala/org/locationtech/geomesa/process/ProcessFactory.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/FeatureExporter.scala

I rebased on master and it wouldn't let me re-open the old PR, so this replaces #961 

GEOMESA-1256 WPS join process for querying two different schemas

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/QueryPlanner.scala

We might want to hold off on merging this for 1.2.3 - it changes the CQL, so the ECQL.toFilter might break in some cases. It didn't happen in any of our unit tests, but might be good to have it in a snapshot for a while before being released.

GEOMESA-1245 Using BindingFilterVisitor to improve filter evaluation times

---

geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaProducerFeatureStore.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/ReplayKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/KafkaDataStoreSchemaManagerTest.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/KafkaDataStoreTest.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/LiveKafkaConsumerFeatureSourceTest.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/ReplayKafkaConsumerFeatureSourceTest.scala

Note: not all unit tests pass in master currently - this fixes some tests but not all.
This should adhere better to the geotools API, but that might cause issues for current users who expect the previous behavior.

GEOMESA-1249 Fixing kafka data store appending feature writer

---

geomesa-raster/src/main/scala/org/locationtech/geomesa/raster/wcs/GeoMesaCoverageFormat.scala

GEOMESA-1295 Fix GeoMesaCoverageFormat's accepts methods

---

docs/user/convert.rst
docs/user/data_management.rst
geomesa-convert/geomesa-convert-avro/src/main/scala/org/locationtech/geomesa/convert/avro/AvroSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-avro/src/test/scala/org/locationtech/geomesa/convert/avro/AvroSimpleFeatureConverterTest.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/CompositeConverter.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
geomesa-convert/geomesa-convert-fixedwidth/src/main/scala/org/locationtech/geomesa/convert/fixedwidth/FixedWidthConverters.scala
geomesa-convert/geomesa-convert-fixedwidth/src/test/scala/org/locationtech/geomesa/convert/fixedwidth/FixedWidthConverterTest.scala
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XMLConverter.scala
geomesa-convert/geomesa-convert-xml/src/test/scala/org/locationtech/geomesa/convert/xml/XMLConverterTest.scala
geomesa-tools/conf/application.conf
geomesa-tools/examples/ingest/csv/example.csv

GEOMESA-1196 Setting of user data in converters

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreDeleteTest.scala

GEOMESA-914 Verifying deletion of non-point geometries

---

geomesa-compute/pom.xml
geomesa-utils/pom.xml

GEOMESA-1307 Remove fastutil from the build

---

docs/user/index.rst
docs/user/spark.rst
geomesa-compute/src/main/scala/org/locationtech/geomesa/compute/spark/GeoMesaSpark.scala

GEOMESA-1301 Allow sft initialization in Spark without a context restart

---

geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/ScalaSimpleFeature.scala

GEOMESA-1311 Not copying backing array on ScalaSimpleFeature.getAttributes

---

docs/bin/build-and-mirror.sh
docs/bin/import-module-readme.sh
docs/common.py
docs/user/metrics.rst
docs/user/modules.rst
docs/user/process.rst
docs/user/raster.rst
docs/user/utils.rst
geomesa-tools/conf/sfts/gdelt/README.md
geomesa-tools/conf/sfts/geolife/README.md
geomesa-tools/conf/sfts/gtd/README.md
geomesa-tools/conf/sfts/osm-gpx/README.md
geomesa-tools/conf/sfts/tdrive/README.md

* Update versions in docs build scripts.

GEOMESA-1301 Minor docs fixes for 1.2.4.

---

README.md
geomesa-kafka/geomesa-kafka-09-datastore/pom.xml
geomesa-kafka/geomesa-kafka-datastore/pom.xml
pom.xml

GEOMESA-1144 Remove vecmath

---

geomesa-tools/conf/application.conf

GEOMESA-1323 Example attr level vis ingest

---

geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala

Bumped up the Cassandra Data Store timeout from 30s to 1200s

[GEOMESA-1102] Increase Cassandra and Kafka timeouts for builds

---

geomesa-web/geomesa-web-install/pom.xml

GEOMESA-1315 - Attach the web-install-assembly to the profile's build

---

CONTRIBUTING.md

Adds brief description of using the License Maven plugin.

GEOMESA-1317 Document adding new copyright license files

---

docs/user/data_management.rst
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/GeoMesaMetadataStats.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/StatsBasedEstimator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/Z3Table.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3DensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3Iterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/Z3FeatureIdGenerator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/ZIntervalTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/Z3IteratorTest.scala
geomesa-blobstore/geomesa-blobstore-api/src/main/scala/org/locationtech/geomesa/blob/api/handlers/BlobStoreFileHandler.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureSource.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureWriterAppend.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/package.scala
geomesa-native-api/src/main/scala/org/locationtech/geomesa/api/AccumuloGeoMesaIndex.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Frequency.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Stat.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/StatSerializer.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Frequency.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Histogram.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/FrequencyTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/Z3FrequencyTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/Z3HistogramTest.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/BinnedTime.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/Z3SFC.scala
geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/BinnedTimeTest.scala
geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/Z3Test.scala

Note: stacks on top of #971, please consider only last commit(s).

GEOMESA-1188 Configurable interval for z3 dates

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/StatsBasedEstimator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreStatsTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Histogram.scala

Note: stacks on top of #978, please only consider last commit(s)

GEOMESA-1331 Fixing histogram out-of-bounds exception in stats estimation

---

build/cqs.tsv
geomesa-web/geomesa-web-core/pom.xml
geomesa-web/geomesa-web-core/src/main/resources/applicationContext.xml
geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/GeoMesaSwagger.scala
geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/SpringScalatraBootstrap.scala
geomesa-web/geomesa-web-stats/pom.xml
geomesa-web/geomesa-web-stats/src/main/resources/applicationContext.xml
geomesa-web/geomesa-web-stats/src/main/scala/org/locationtech/geomesa/web/stats/GeoMesaStatsEndpoint.scala
geomesa-web/pom.xml

Signed-off-by: Alex Tatusko <atatusko@ccri.com>

GEOMESA-1302 Added Swagger documentation to the stats REST API

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/usage/UsageStatWriter.scala

GEOMESA-1349 Fixing writing of query stats

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/usage/GeoMesaUsageStats.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/usage/QueryStat.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/usage/RasterQueryStat.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/usage/UsageStat.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/usage/UsageStatWriter.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/stats/usage/UsageStatWriterTest.scala
geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/analytics/StatsEndpoint.scala

GEOMESA-1347 Soft delete functionality for usage stats

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/filter/BoundsFilterVisitorTest.scala
geomesa-filter/src/main/java/org/locationtech/geomesa/filter/HotfixExtractBoundsFilterVisitor.java
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/visitor/BoundsFilterVisitor.scala

because @jnh5y  likes to share codez

Bounds hotfix

---

geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaProducerFeatureStore.scala

GEOMESA-1359 Fix KafkaDataStore addFeatures

---

docs/user/commandline_tools.rst
geomesa-tools/README.md
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/EnvironmentCommand.scala

Signed-off-by: Charles Kelly <charles.kelly@ccri.com>

GEOMESA-1262 List sft and converters

---

geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/PathHandlingServletRequest.scala
geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/SpringScalatraBootstrap.scala
geomesa-web/geomesa-web-stats/src/main/scala/org/locationtech/geomesa/web/stats/GeoMesaStatsEndpoint.scala

GEOMESA-1369 Fixing scalatra path handling

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/ProjectVersionIterator.scala
geomesa-utils/pom.xml
geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa.properties
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/GeoMesaProperties.scala

GEOMESA-1267 Checking for iterator versions on getSchema

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
geomesa-tools/conf/sfts/twitter/reference.conf

GEOMESA-1374 Concat varargs and mkstring in converters

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/GeoMesaMetadata.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/GeoMesaTable.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/XZ3Table.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/Z3Table.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/QueryFilterSplitter.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/QueryStrategyDecider.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/Strategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/XZ3IdxStrategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/XZ2IdxStrategyTest.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZ3SFC.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZSFC.scala
geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/XZ3SFCTest.scala

GEOMESA-1370 XZ3 Spatio-temporal Index

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/Z2Table.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/Z3Table.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/filter/TestFilters.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/DensityIteratorTest.scala

GEOMESA-1163 Fixing decomposition of polygons into z-index

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapred/GeoMesaOutputFormat.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/GeoMesaOutputFormat.scala

GEOMESA-1378 Fixing serialization of feature IDs in m/r output

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala

GEOMESA-1380 Throwing exception on tilde in feature name

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/GeoMesaSchemaValidator.scala

GEOMESA-1385 Allow for override of reserved words in schema

---

README.md
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/BinEncoder.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/DensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyDensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/tube/TubeBuilder.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/Z3FeatureIdGenerator.scala
geomesa-tools/conf/sfts/twitter/reference.conf
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geohash/GeohashUtils.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/BinnedArray.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Frequency.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Histogram.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Frequency.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Histogram.scala

Note: this bug is likely to creep back in unless we are super-vigilant about not calling getCentroid. Probably it should be fixed in geotools.

GEOMESA-1384 Verifying calls to geometry.getCentroid

---

README.md
geomesa-compute/pom.xml
geomesa-compute/src/test/scala/ExampleSparkScript.scala
geomesa-compute/src/test/scripts/ExampleSparkScript.scala

GEOMESA-1396 RichCountMinSketch doesn't work with Spark classloaders

---

geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/KafkaDataStoreTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geohash/GeohashUtils.scala

* Fixing kafka data store test - methods were not executing

GEOMESA-1388 Copying geometry in GeoHashUtils.getInternationalDateLineSafeGeometry

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/GeoMesaMetadataStats.scala

GEOMESA-1415 Using distributed count with XZ indices

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/GeoMesaSchemaValidator.scala

GEOMESA-1411 Indicating override option in reserved word error

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/GeoMesaMetadataStats.scala

GEOMESA-1414 Using system property for initial scheduling of stats compaction

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/GeoMesaMetadataStats.scala

GEOMESA-1405 Allowing ingestion without a distributed runtime jar installed

---

docs/user/installation_and_configuration.rst

GEOMESA-1419 Docs: update references to libs dir for tools

---

docs/tutorials/geomesa-examples-gdelt.rst
docs/tutorials/geomesa-quickstart-storm.rst
docs/user/installation_and_configuration.rst

GEOMESA-863 Docs: add geomesa-process installation instructions

---

geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/ScalaSimpleFeature.scala
geomesa-jobs/src/main/java/org/locationtech/geomesa/jobs/interop/mapred/FeatureWriterJob.java
geomesa-jobs/src/main/java/org/locationtech/geomesa/jobs/interop/mapreduce/FeatureWriterJob.java
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/ingest/AutoIngestAvro.scala

GEOMESA-1418 Copying user data in avro auto ingestion

---

docs/bin/build-and-mirror.sh

GEOMESA-1282 Docs: generalize build_and_mirror.sh script

---

docs/user/installation_and_configuration.rst
geomesa-tools/bin/download-data.sh
geomesa-tools/bin/geomesa
geomesa-tools/bin/geomesa-common.sh
geomesa-tools/bin/geomesa-env.sh
geomesa-tools/bin/geomesa-kafka
geomesa-tools/bin/install-hadoop-accumulo.sh
geomesa-tools/bin/install-imageio-ext.sh
geomesa-tools/bin/install-jai.sh
geomesa-tools/bin/install-jline.sh
geomesa-tools/bin/install-kafka.sh
geomesa-tools/conf/geomesa-env.sh
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/AccumuloParams.scala

Removed duplicate code, added geomesa-env configuration, added geomesa-common, added error handling to wget -O calls, added JAVA_OPTS support, changed GEOMESA_HOME warning output, updated all if statements to double brackets.

GEOMESA-1181 Cleanup command line tools scripts

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/GeoMesaMetadataStats.scala

GEOMESA-1424 StatUpdater - only writing stats if there have been observations

---

geomesa-tools/bin/geomesa
geomesa-tools/conf/geomesa-env.sh

Added the option to allow toggling the hadoop classpath configuration to better support CDH installs.

GEOMESA-1185 Better classpath setting with CDH

---

geomesa-tools/bin/geomesa-common.sh
geomesa-tools/bin/install-hadoop-accumulo.sh
geomesa-tools/bin/install-imageio-ext.sh
geomesa-tools/bin/install-jai.sh
geomesa-tools/bin/install-jline.sh
geomesa-tools/bin/install-kafka.sh

All command line tools scripts now accept [Enter] for the indicated default value when prompting the user for input.

GEOMESA-1425 Accept [Enter] in read prompts

---

geomesa-tools/conf/log4j.properties

I'm not sure if this is the correct way to address this issue but it should redirect any errors thrown by BinnedArrays to the geomesa log.

GEOMESA-1320 Command line blasts terminal with errors on ingest

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaProducerFeatureStore.scala

GEOMESA-1436  Don't log features at INFO in kafka10

---

build/cqs.tsv
geomesa-kafka/geomesa-kafka-datastore/pom.xml
pom.xml

GEOMESA-1439 Adding kafak 8,9 data stores to default build

---

geomesa-gs-plugin/geomesa-kafka-gs-plugin/pom.xml
geomesa-kafka/geomesa-kafka-dist/geomesa-kafka-08-dist/pom.xml
geomesa-kafka/geomesa-kafka-dist/geomesa-kafka-09-dist/pom.xml
geomesa-kafka/geomesa-kafka-dist/geomesa-kafka-10-dist/pom.xml
geomesa-kafka/geomesa-kafka-dist/pom.xml
pom.xml

* Making kafka provided in dist to correspond with kafka 8

GEOMESA-1440 Adding kafka dist, gs-plugins to normal build

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala

GEOMESA-549 Unit test for Filter.EXCLUDE

---

geomesa-accumulo/geomesa-accumulo-compute/pom.xml

GEOMESA-1446 Remove duplicate artifact declaration

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala

GEOMESA-906 Unit test for Filter.INCLUDE AND *

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeTableTest.scala

GEOMESA-500 Unit test to validate BETWEEN date attribute filters

---

docs/user/geoserver.rst
geomesa-accumulo/geomesa-accumulo-datastore/src/test/resources/log4j.xml
geomesa-accumulo/geomesa-accumulo-tools/conf/log4j.properties
geomesa-blobstore/geomesa-blobstore-accumulo/src/test/resources/log4j.xml
geomesa-kafka/geomesa-kafka-tools/conf/log4j.properties
geomesa-native-api/src/test/resources/log4j.xml

GEOMESA-1448 Fixing explain logger configs

---

docs/user/geoserver.rst
geomesa-blobstore/geomesa-blobstore-accumulo/src/test/resources/log4j.xml
geomesa-native-api/src/test/resources/log4j.xml
geomesa-tools/conf/log4j.properties

1.2 - GEOMESA-1448 Fixing explain logger configs

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastPropertyName.scala

* Note: will run a full table scan

GEOMESA-702 Support for 'exists' predicate

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/ProjectVersionIterator.scala
geomesa-accumulo/geomesa-accumulo-tools/src/main/resources/org/locationtech/geomesa/tools/geomesaVersion.properties
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/AccumuloParams.scala
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/AccumuloRunner.scala
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/AccumuloVersionCommand.scala
geomesa-tools-common/pom.xml
geomesa-tools-common/src/main/resources/org/locationtech/geomesa/tools/geomesaVersion.properties
geomesa-tools-common/src/main/scala/org/locationtech/geomesa/tools/common/commands/VersionCommand.scala
geomesa-utils/pom.xml
geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa.properties
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/GeoMesaProperties.scala

GEOMESA-1348 Adding distributed runtime version to tools command

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi

GEOMESA-1459 Kafka 0.8 datastore missing META-INF/services

---

geomesa-accumulo/geomesa-accumulo-tools/src/main/resources/org/locationtech/geomesa/tools/ingest-libjars.list

GEOMESA-1469 Add htrace to libjars

---

docs/bin/import-module-readme.sh
docs/bin/import-tutorial-readme.sh
docs/user/geoserver.rst

* Removed 4 instances of /opt/devel/

GEOMESA-1398 Remove doc references to /opt/devel/

---

docs/user/geoserver.rst

Added clarification not in the geoserver docs about time enabled layers.

GEOMESA-502 Document Time-Enabled Layers in GeoServer docs

---

docs/user/accumulo_datastore.rst
docs/user/data_management.rst
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/XZConfigurationTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZSFC.scala

1.2 - GEOMESA-1358 Configurable precision for XZ indices

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/QueryPlan.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/BatchMultiScanner.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/util/BatchMultiScannerTest.scala
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/FeatureExporter.scala
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/Utils.scala
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/ExportCommand.scala

GEOMESA-1467 Multithreading join scans in BatchMultiScanner

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/QueryPlan.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/BatchMultiScanner.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/util/BatchMultiScannerTest.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/FeatureExporter.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/Utils.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/ExportCommand.scala

1.2 - GEOMESA-1467 Multithreading join scans in BatchMultiScanner

---

geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/GeoMesaDataStoreServlet.scala
geomesa-web/geomesa-web-data/src/main/resources/applicationContext.xml

GEOMESA-1468 Encrypting persisted data store passwords in geomesa-web

---

geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/GeoMesaDataStoreServlet.scala
geomesa-web/geomesa-web-data/src/main/resources/applicationContext.xml

1.2 - GEOMESA-1468 Encrypting persisted data store passwords in geomesa-web

---

docs/user/accumulo_datastore.rst
docs/user/data_management.rst
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/XZConfigurationTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZSFC.scala

GEOMESA-1358 Configurable precision for XZ indices

---

build/cqs.tsv
geomesa-utils/pom.xml
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Stat.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/StatParser.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/BasicParser.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/StatTest.scala
pom.xml

GEOMESA-1375 Rewriting stats parsing in parboiled

---

geomesa-accumulo/geomesa-accumulo-tools/pom.xml
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/ingest/AbstractIngest.scala

Progress bar (just the bar) now scales on ingest. If the info string length increases the bar shrinks dynamically.

GEOMESA-1046 Fix progress bar scaling on ingest

---

geomesa-web/geomesa-web-stats/src/main/scala/org/locationtech/geomesa/web/stats/GeoMesaStatsEndpoint.scala

* Added a "noCache" parameter for the stats REST API methods
Signed-off-by: Alex Tatusko <atatusko@ccri.com>

GEOMESA-1466 Enable querying against live data for the stats REST API

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala

GEOMESA-1472 Transformers functionMap needs to be synchronized

---

geomesa-accumulo/geomesa-accumulo-tools/pom.xml
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/ingest/AbstractIngest.scala

Fixed the provided jline dependency

Remove jline provided dependency for progressbar

---

geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/AccumuloRunner.scala

* Additional this change provides feedback to the user regarding setting the instance ID.

GEOMESA-1485 Increase Accumulo Instance ID lookup to 5s

---

.travisbuild.sh
build/README.md
docs/common.py
docs/tutorials/geomesa-quickstart-hbase.rst
docs/tutorials/geomesa-quickstart-kafka.rst
geomesa-archetypes/geomesa-archetypes-gs-plugin/README.md
geomesa-hbase/geomesa-bigtable-dist/src/main/assemblies/component.xml
geomesa-hbase/geomesa-hbase-dist/src/main/assemblies/component.xml
geomesa-process/README.md
pom.xml

* Updates the HBase distribution to use the correct README.md.
* Updates Travis to run the HBase profile by default.

GEOMESA-1484 Fix HBase profile

---

geomesa-accumulo/geomesa-accumulo-gs-plugin/README.md

Updated docs to refect new vesions of accumulo and hadoop jars.

GEOMESA-1061 Update jar docs for hadoop/accumulo

---

build/cqs.tsv
geomesa-accumulo/geomesa-accumulo-compute/src/main/scala/org/locationtech/geomesa/compute/spark/GeoMesaSpark.scala
geomesa-accumulo/geomesa-accumulo-datastore/pom.xml
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureSource.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/GeoMesaMetadata.scala
geomesa-accumulo/geomesa-accumulo-jobs/src/main/resources/org/locationtech/geomesa/jobs/default-libjars.list
geomesa-accumulo/geomesa-accumulo-raster/src/main/scala/org/locationtech/geomesa/raster/data/AccumuloRasterStore.scala
geomesa-accumulo/geomesa-accumulo-tools/src/main/resources/org/locationtech/geomesa/tools/ingest-libjars.list
geomesa-features/geomesa-feature-avro/pom.xml
geomesa-features/geomesa-feature-avro/src/main/scala/org/locationtech/geomesa/features/avro/AvroSimpleFeatureFactory.scala
geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/serde/Version1ASF.scala
geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/serde/Version2ASF.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaDataStoreSchemaManager.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaDataStoreSchemaManager.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaDataStoreSchemaManager.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/pom.xml
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/main/scala/org/locationtech/geomesa/kafka/LiveFeatureCacheCQEngine.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/main/scala/org/locationtech/geomesa/kafka/LiveFeatureCacheGuava.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/test/scala/org/locationtech/geomesa/kafka/LiveFeatureCacheBenchmarkTest.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/test/scala/org/locationtech/geomesa/kafka/LiveFeatureCacheCQEngineTest.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/test/scala/org/locationtech/geomesa/kafka/MockTicker.scala
geomesa-native-api/src/main/scala/org/locationtech/geomesa/api/AccumuloGeoMesaIndex.scala
geomesa-stream/geomesa-stream-datastore/src/main/scala/org/locationtech/geomesa/stream/datastore/StreamDataStore.scala
pom.xml

GEOMESA-1333 Replace guava caches with caffeine

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/attribute/AttributeQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryStrategyDeciderTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/StatsBasedEstimator.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/package.scala

GEOMESA-1489 Short-circuit queries with disjoint predicates

---

docs/common.py
docs/user/geoserver.rst
docs/user/installation_and_configuration.rst

(After review I will cherry-pick to 1.3.0-m1 docs branch.)

GEOMESA-1486 Fix Kafka links in installation docs.

---

geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/ingest/AbstractIngestJob.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/classpath/ClassPathUtils.scala

Add the ability to add items to class path by using the system variable geomesa.convert.scripts.path

GEOMESA-1404 Classpath Additions to MapReduce Ingest

---

build/cqs.tsv
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/CloseableIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreAlterSchemaTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/json/JsonPathParser.scala
geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/json/JsonPathParserTest.scala
geomesa-geojson/geomesa-geojson-api/pom.xml
geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndex.scala
geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoJsonIndex.scala
geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/query/GeoJsonQuery.scala
geomesa-geojson/geomesa-geojson-api/src/test/resources/log4j.xml
geomesa-geojson/geomesa-geojson-api/src/test/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndexTest.scala
geomesa-geojson/geomesa-geojson-api/src/test/scala/org/locationtech/geomesa/geojson/query/GeoJsonQueryTest.scala
geomesa-geojson/geomesa-geojson-gs-plugin/pom.xml
geomesa-geojson/geomesa-geojson-rest/pom.xml
geomesa-geojson/geomesa-geojson-rest/src/main/resources/applicationContext.xml
geomesa-geojson/geomesa-geojson-rest/src/main/scala/org/locationtech/geomesa/geojson/servlet/GeoJsonServlet.scala
geomesa-geojson/geomesa-geojson-rest/src/test/resources/curl-test.txt
geomesa-geojson/geomesa-geojson-rest/src/test/resources/log4j.xml
geomesa-geojson/geomesa-geojson-rest/src/test/scala/org/locationtech/geomesa/geojson/servlet/GeoJsonServletTest.scala
geomesa-geojson/pom.xml
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/cache/FilePersistence.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/classpath/PathUtils.scala
geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/GeoMesaDataStoreServlet.scala
geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/SpringScalatraBootstrap.scala
geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/analytics/StatsEndpoint.scala
geomesa-web/pom.xml
pom.xml

~~note: stacks on top of #1102~~
* New module geomesa-geojson
* Scala API - GeoJsonIndex/GeoJsonGtIndex
* Rest API - GeoJsonServlet

GEOMESA-1449 GeoJson Support

---

geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndex.scala

Fixing compile merge

---

build/cqs.tsv
geomesa-convert/geomesa-convert-json/pom.xml
geomesa-features/geomesa-feature-kryo/pom.xml
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/json/JsonPathPropertyAccessor.scala
geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/json/JsonPathPropertyAccessorTest.scala
pom.xml

~~note: stacks on top of #1122 ~~

GEOMESA-1406 JSON path accessors for string attributes

---

README.md
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/ConfigLoader.scala

Signed-off-by: Chris Eichelberger <cne1x@ccri.com>

Updated the README.md development version and some exception text.

---

geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa-site.xml.template

GEOMESA-1506 Removed default query timeout 

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/StatsBasedEstimator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIdxStrategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/XZ2IdxStrategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/XZ3IdxStrategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/Z2IdxStrategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategy.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryStrategyDeciderTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/package.scala

1.2.6 - GEOMESA-1489 Short-circuit queries with disjoint predicates (#1175)

---

.travisbuild.sh
geomesa-accumulo/geomesa-accumulo-datastore/pom.xml
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/id/RecordQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/package.scala
geomesa-hbase/geomesa-bigtable-tools/src/main/resources/org/locationtech/geomesa/bigtable/tools/ingest-libjars.list
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureWriter.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseAttributeIndex.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseIdIndex.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseXZ2Index.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseXZ3Index.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ3Index.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
geomesa-hbase/geomesa-hbase-tools/src/main/resources/org/locationtech/geomesa/hbase/tools/ingest-libjars.list
geomesa-index-api/pom.xml
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/AttributeIndex.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/IdIndex.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/IndexAdapter.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ2Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ3Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z2Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z3Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/AttributeFilterStrategy.scala

~~note: stacks on top of #1179~~
* Only support 'full' indices

 GEOMESA-1492 Abstract GeoMesa attribute index and HBase implementation

---

geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/audit/QueryEvent.scala
geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/analytics/StatsEndpoint.scala

GEOMESA-1507 Adding bin filtering to saved query servlet

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/usage/QueryStat.scala
geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/analytics/StatsEndpoint.scala

1.2 - GEOMESA-1507 Adding bin filtering to saved query servlet

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/usage/QueryStat.scala
geomesa-web/geomesa-web-data/src/main/scala/org/locationtech/geomesa/web/analytics/StatsEndpoint.scala

1.2.6 - GEOMESA-1507 Adding bin filtering to saved query servlet

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala

GEOMESA-1481 Fixing buffer size in bin line strings export

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala

1.2 - GEOMESA-1481 Fixing buffer size in bin line strings export

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala

1.2.6 - GEOMESA-1481 Fixing buffer size in bin line strings export

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala

GEOMESA-1512 Fixing intersection of complex polygons in FilterHelper

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala

1.2 - GEOMESA-1512 Fixing intersection of complex polygons in FilterHelper

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala

~~Note: stacks on top of #1189~~

1.2.6 - GEOMESA-1512 Fixing intersection of complex polygons in FilterHelper

---

geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/ThreadManagement.scala

~~Note: stacks on top of #1184~~

GEOMESA-1508 Using exiting executor for query thread timeout reaper

---

geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonFunctionFactory.scala
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpec.scala

GEOMESA-971 JSON Converters for maps, long, float

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/GeoMesaBatchWriterConfig.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/Suffixes.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/text/SuffixesTest.scala

so we can use it elsewhere. note i pulled off the shelf some suffixes class i had but we can keep the old mem parsing if desired. i had some logging in it

GEOMESA-1515 Suffixes helper

---

geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala

GEOMESA-1516 FilterHelper.logger ambiguity w/ Scala 2.10

---

build/cqs.tsv
pom.xml

GEOMESA-1517 Excluding asm from json-path dependency

---

geomesa-hbase/geomesa-bigtable-dist/src/main/assemblies/component.xml
geomesa-hbase/geomesa-hbase-dist/src/main/assemblies/component.xml

GEOMESA-1522 Add geomesa-site.xml.template to hbase/bigtable distros

---

geomesa-accumulo/geomesa-accumulo-tools/bin/install-hadoop-accumulo.sh

* install-hadoop-accumulo now installes the htrace jar properly depending on accumulo version
* Error checking added for version numbers. Version numbers must be of the form x.x.x to be valid.

GEOMESA-1511 Fixed htrace install issue

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreDeleteTest.scala
geomesa-cassandra/geomesa-cassandra-datastore/pom.xml
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraBackedMetaData.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraContentState.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStore.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreFactory.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraFeatureStore.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala

GEOMESA-1474 Cassandra: store SFT specification in a metadata table

---

.travisbuild.sh

GEOMESA-1532 Move CQ Check failure notification to bottom of build log

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-accumulo/geomesa-accumulo-raster/src/main/scala/org/locationtech/geomesa/raster/data/AccumuloRasterStore.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/package.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/QueryPlanner.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/StrategyDecider.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureReader.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/MonitoringFeatureReader.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/MethodProfiling.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/MethodProfilingTest.scala

GEOMESA-1527 Deduplicating common parts of OR clauses

---

build/cqs.tsv
docs/user/cassandra_datastore.rst
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraContentState.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStore.scala
geomesa-cassandra/geomesa-cassandra-dist/pom.xml
geomesa-cassandra/geomesa-cassandra-dist/src/main/assemblies/component.xml
geomesa-cassandra/geomesa-cassandra-tools/bin/geomesa-cassandra
geomesa-cassandra/geomesa-cassandra-tools/conf/geomesa-env.sh
geomesa-cassandra/geomesa-cassandra-tools/conf/log4j.properties
geomesa-cassandra/geomesa-cassandra-tools/pom.xml
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/CassandraDataStoreCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/CassandraParams.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/CassandraRunner.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraDescribeSchemaCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraGetSftConfigCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraGetTypeNamesCommand.scala
geomesa-cassandra/pom.xml
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/Command.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/DescribeSchemaCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/GetSftConfigCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/GetTypeNamesCommand.scala

GEOMESA-1534 Command-line tools for Cassandra

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/package.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala

1.2 - GEOMESA-1527 Deduplicating common parts of OR clauses

---

geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala

GEOMESA-1529 KryoBufferSimpleFeature - caching transform offset check

---

geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala

* Ported other changes from 1.3 to keep files in sync

1.2 - GEOMESA-1529 KryoBufferSimpleFeature - caching transform offset check

---

geomesa-accumulo/geomesa-accumulo-compute/pom.xml

Provides compatibility with Spark >= 2.0.0

GEOMESA-1535 Specify kryo as provided in geomesa-accumulo-compute

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala

GEOMESA-1477 Adding '::string' converter transform

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreDeleteTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/RecordIdxStrategyTest.scala

GEOMESA-1526 Fixing intermittent travis test failures

---

docs/common.py
docs/user/installation_and_configuration.rst
geomesa-archetypes/geomesa-archetypes-gs-plugin/README.md

- download links
- wording in geoserver plugin docs

GEOMESA-1541 fix download links in documentation

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/ConverterIngest.scala

* Created an object pool to reuse converters

GEOMESA-1537 Cache converters in Local Ingest for performance

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/ingest/ConverterIngest.scala

* Created an object pool to reuse converters

1.2 - GEOMESA-1537 Cache converters in Local Ingest for performance

---

geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraBackedMetaData.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStore.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreFactory.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/CassandraRunner.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraCreateSchemaCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraIngestCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraRemoveSchemaCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/CreateSchemaCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/RemoveSchemaCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala

GEOMESA-1542 Cassandra create-schema, remove-schema, and ingest commands

---

geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/GeometrySerialization.scala
geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializerTest.scala

GEOMESA-1478 Serialization of geometries with more than 2 dimensions

---

geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/GeometryReader.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/GeometrySerialization.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/GeometryWriter.scala
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializer.scala
geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializerTest.scala

1.2 - GEOMESA-1478 Serialization of geometries with more than 2 dimensions

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/LiveKafkaConsumerFeatureSource.scala

GEOMESA-1119 Catching exceptions in feature listeners in Kafka DataStore

---

geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/LiveKafkaConsumerFeatureSource.scala

1.2 - GEOMESA-1119 Catching exceptions in feature listeners in Kafka DataStore

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/ConfigureShardsTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/IndexAdapter.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ2Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ3Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z2Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z3Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/SplitArrays.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/GeoMesaSchemaValidator.scala

GEOMESA-1538 Adding configurable shards to index api

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureWriter.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/BackCompatibilityTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureWriter.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/cache/CacheKeyGenerator.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/SafeClose.scala

GEOMESA-1545 Caching FeatureWriter mutators

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryProperties.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreFactory.scala
geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa-site.xml.template

GEOMESA-1556 System property to disable stat generation

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/accumulo.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala

1.2 - GEOMESA-1556 System property to disable stat generation

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyAggregatingIterator.scala

GEOMESA-1557 Resetting deduplication check in KryoLazyAggregatingIterator

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyAggregatingIterator.scala

1.2 - GEOMESA-1557 Resetting deduplication check in KryoLazyAggregatingIterator

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloFeatureIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3WritableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureWriterTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaIndexManager.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ2Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ3Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z2Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z3Index.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/BinnedTime.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/NormalizedDimension.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZ2SFC.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZ3SFC.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZSFC.scala
geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/XZ2SFCTest.scala
geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/XZ3SFCTest.scala
geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/Z2Test.scala
geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/Z3Test.scala

GEOMESA-1551 Fail writing features with invalid geometries or dates

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloConnectorCreator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/BatchMultiScanner.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreAuthTest.scala
geomesa-security/src/main/scala/org/locationtech/geomesa/security/package.scala

1.2 - GEOMESA-1560 Getting authorizations from initial thread in batch multi scan

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloQueryPlan.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/BatchMultiScanner.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreAuthTest.scala
geomesa-security/src/main/scala/org/locationtech/geomesa/security/package.scala

GEOMESA-1560 Getting authorizations from initial thread in batch multi scan

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/audit/AccumuloAuditService.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala

GEOMESA-1361 Method for returning all accumulo table names

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpecParser.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala

GEOMESA-1571 Improved error reporting in simple feature spec parsing

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/QueryPlanner.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala

1.2 - GEOMESA-1558 Not applying transform iterator for identity transforms

---

geomesa-spark/geomesa-spark-accumulo/src/main/scala/org/locationtech/geomesa/spark/accumulo/AccumuloSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-geotools/pom.xml
geomesa-spark/geomesa-spark-geotools/src/main/resources/META-INF/services/org.locationtech.geomesa.spark.SpatialRDDProvider
geomesa-spark/geomesa-spark-geotools/src/main/scala/org/locationtech/geomesa/spark/geotools/GeoToolsSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-geotools/src/test/scala/org/locationtech/geomesa/spark/geotools/GeoToolsSpatialRDDProviderTest.scala
geomesa-spark/pom.xml
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeneralShapefileIngest.scala
pom.xml

* To use add a key "geotools" to the params map.

GEOMESA-1577 Implement a GeoTools DataStore RDD Provider

---

geomesa-spark/geomesa-spark-geotools/pom.xml
geomesa-spark/geomesa-spark-geotools/src/test/scala/org/locationtech/geomesa/spark/geotools/GeoToolsSpatialRDDProviderTest.scala
pom.xml

* Removing duplicate dependency management entry for geomesa-accumulo-compute

GEOMESA-1580 Fixing GeoToolsSpatialRDDProviderTest

---

geomesa-tools/bin/common-functions.sh

GEOMESA-1579 Fixed reference to function that no longer exists

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/VisibilitiesTest.scala

GEOMESA-1582 Enabling visibilities test

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureWriterTest.scala

GEOMESA-1585 Uncommenting FeatureWriter tests

---

geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/ConverterInputFormat.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/FileStreamInputFormat.scala
geomesa-spark/geomesa-spark-converter/pom.xml
geomesa-spark/geomesa-spark-converter/src/main/resources/META-INF/services/org.locationtech.geomesa.spark.SpatialRDDProvider
geomesa-spark/geomesa-spark-converter/src/main/scala/org/locationtech/geomesa/spark/converter/ConverterSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-converter/src/test/resources/example.conf
geomesa-spark/geomesa-spark-converter/src/test/resources/example.csv
geomesa-spark/geomesa-spark-converter/src/test/scala/org/locationtech/geomesa/spark/converter/ConverterSpatialRDDProviderTest.scala
geomesa-spark/pom.xml

* Allows for creating RDDs from files using a GeoMesa simple feature converter
* Added ability to filter inputs by CQL in ConverterInputFormat

GEOMESA-1587 ConverterSpatialRDDProvider implementation

---

geomesa-accumulo/geomesa-accumulo-dist/pom.xml
geomesa-accumulo/geomesa-accumulo-dist/src/main/assemblies/component.xml

* Added geojson to the binary distribution

GEOMESA-1597 Dist should include GeoJSON

---

docs/_static/css/theme_custom.css
docs/user/geojson.rst
docs/user/index.rst
docs/user/installation_and_configuration.rst

Documentation for 1.3

---

docs/user/geojson.rst
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastPropertyName.scala
geomesa-geojson/geomesa-geojson-api/src/test/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndexTest.scala
geomesa-geojson/geomesa-geojson-rest/src/main/scala/org/locationtech/geomesa/geojson/servlet/GeoJsonServlet.scala
geomesa-geojson/geomesa-geojson-rest/src/test/resources/curl-test.txt
geomesa-geojson/geomesa-geojson-rest/src/test/scala/org/locationtech/geomesa/geojson/servlet/GeoJsonServletTest.scala
pom.xml

* Modified GeoJSON servlet to accept GeoJSON in the post body instead of by parameter
* Added tests and docs on querying by property

GEOMESA-1598 Fixing loading of PropertyAccessors in Accumulo iterators

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/Suffixes.scala

GEOMESA-1603 Decrease Suffixes Memory logging

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloBackedMetadata.scala
geomesa-web/geomesa-web-core/pom.xml
geomesa-web/geomesa-web-core/src/main/scala/org/locationtech/geomesa/web/core/GeoMesaDataStoreServlet.scala
geomesa-web/geomesa-web-core/src/test/resources/log4j.xml
geomesa-web/geomesa-web-core/src/test/scala/org/locationtech/geomesa/web/core/GeoMesaDataStoreServletTest.scala
geomesa-web/geomesa-web-stats/pom.xml
geomesa-web/pom.xml

GEOMESA-1604 Masking data store password in GeoMesaDataStoreServlet

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/test/scala/org/locationtech/geomesa/kafka10/consumer/KafkaConsumerTest.scala

Signed-off-by: Charles Kelly <charles.kelly@ccri.com>

GEOMESA-1594 Debugging print outs present in Kafka 10 KafkaConsumerTest

---

geomesa-accumulo/geomesa-accumulo-tools/bin/install-hadoop-accumulo.sh
geomesa-hbase/geomesa-bigtable-tools/bin/install-hbase.sh
geomesa-kafka/geomesa-kafka-tools/bin/install-kafka.sh
geomesa-tools/bin/download-data.sh
geomesa-tools/bin/install-imageio-ext.sh
geomesa-tools/bin/install-jai.sh

* Changed ${errorList} to ${errorList[@]} in relevant locations to show all failed downloads.

GEOMESA-1622 Fix error reporting in tools downloads

---

geomesa-accumulo/geomesa-accumulo-spark/src/main/scala/org/locationtech/geomesa/spark/accumulo/AccumuloSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-core/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSpark.scala
geomesa-spark/geomesa-spark-geotools/src/main/scala/org/locationtech/geomesa/spark/geotools/GeoToolsSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala

GEOMESA-1617 Fix Spark SQL Scala 2.10 build

---

docs/user/geojson.rst
geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndex.scala
geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoJsonIndex.scala
geomesa-geojson/geomesa-geojson-api/src/test/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndexTest.scala
geomesa-geojson/geomesa-geojson-rest/src/main/scala/org/locationtech/geomesa/geojson/servlet/GeoJsonServlet.scala
geomesa-geojson/geomesa-geojson-rest/src/test/resources/curl-test.txt
geomesa-geojson/geomesa-geojson-rest/src/test/scala/org/locationtech/geomesa/geojson/servlet/GeoJsonServletTest.scala

* Added methods to get by feature ID
* Added caching of JSON extractors in GeoJSON index
* Added caching of service objects in GeoJSON servlet
* Fixed bug in deleting features from GeoJSON index
* Updated docs

GEOMESA-1452 Update and delete functionality for GeoJSON servlet

---

geomesa-spark/geomesa-spark-sql/pom.xml
geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLGeometricOutputFunctions.scala
geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLTypes.scala
geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLGeometricOutputsTest.scala

Signed-off-by: Charles Kelly <charles.kelly@ccri.com>

GEOMESA-1619 Implement SQL Geometric Output Functions

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportParams.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypeLoader.scala

GEOMESA-1623 Fixing check for BIN export in tools

---

docs/common.py
docs/tutorials/geomesa-quickstart-storm.rst

* Updated Docs for Storm Quickstart
* Fixed supported Accumulo versions
* Added Accumulo 1.8 profile to geomesa-accumulo-datastore.pom to shade curator to prevent conflicts with Accumulo 1.8 and Storm

GEOMESA-1625 Storm QS Updates

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/BackCompatibilityTest.scala

1.2.7 - GEOMESA-1629 Fixing deletion of z index values from 1.2.5/6

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/BackCompatibilityTest.scala

1.2 - GEOMESA-1629 Fixing deletion of z index values from 1.2.5/6

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3Index.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/BackCompatibilityTest.scala

GEOMESA-1629 Fixing deletion of z index values from 1.2.5/6

---

geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa
geomesa-cassandra/geomesa-cassandra-tools/bin/geomesa-cassandra
geomesa-hbase/geomesa-bigtable-tools/bin/geomesa-bigtable
geomesa-hbase/geomesa-hbase-tools/bin/geomesa-hbase
geomesa-kafka/geomesa-kafka-tools/bin/geomesa-kafka

GEOMESA-1637 Correct Extra Classpaths

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/RecordIdxStrategyTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/XZ2IdxStrategyTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z2IdxStrategyTest.scala
geomesa-metrics/src/test/scala/org/locationtech/geomesa/metrics/reporters/DelimitedFileReporterTest.scala

GEOMESA-1618 Fixing intermittent sampling test failures

---

docs/user/cassandra/install.rst

GEOMESA-1611 Cassandra docs fix redux

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/LiveKafkaConsumerFeatureSource.scala

GEOMESA-1609 Configurable Cleanup Cache Interval for KafkaDataStore

---

geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraBackedMetaData.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala

- add a test to expose bug
- query system table to determine if catalog table exists

GEOMESA-1660 Fix Cassandra getTypeNames bug

---

docs/user/accumulo/commandline_tools.rst
docs/user/accumulo/examples.rst
docs/user/accumulo/raster.rst
docs/user/introduction.rst

GEOMESA-1656 Replace references to convert README to proper docs

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/ExplainCommand.scala

GEOMESA-1655 Fix "geomesa explain" command line tool output

---

geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala
geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLDataTest.scala

GEOMESA-1665 Spark SQL: fix "WHERE __fid__ = 'foo'" queries

---

geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala

GEOMESA-1615 Making FilterHelper.flatten tail recursive

---

geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStore.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala

- add a test
- fix bit operations in CassandraPrimaryKey.unapply

GEOMESA-1670 fix cassandra index bug

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GenerateFeatureWrappers.scala

* Makes generated files consistent between runs

GEOMESA-1681 Sorting classes in GenerateFeatureWrappers

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala

GEOMESA-1671 Clarifying HBase client-side filter code

---

geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XMLConverter.scala
geomesa-convert/geomesa-convert-xml/src/test/resources/bomTest.xml
geomesa-convert/geomesa-convert-xml/src/test/scala/org/locationtech/geomesa/convert/xml/XMLConverterTest.scala

Added support for BOM in xml ingest

GEOMESA-1684 Excluded the BOM in XML files during ingest

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyFilterTransformIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/RecordIdxStrategyTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/visitor/IdExtractingVisitor.scala

* Note: requires iterator jars to be updated

GEOMESA-1685 Fixing NOT ID filters

---

geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala

GEOMESA-1683 - Add support for global JSON variables

---

docs/user/convert/function_usage.rst
geomesa-convert/geomesa-convert-common/src/main/resources/META-INF/services/org.locationtech.geomesa.convert.TransformerFunctionFactory
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala

* Created basic 4 math functions for ingest converters. Nested operations is not supported.
* Documentation

GEOMESA-1678 Create Math functions for ingest converters

---

geomesa-index-api/pom.xml
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/IndexAdapter.scala

@elahrvivaz, this reverts a change that was pulled in with #1339.  Please verify this doesn't introduce a regression.

GEOMESA-1689 scala 2.10 build fixes

---

geomesa-hbase/geomesa-hbase-tools/src/main/resources/org/locationtech/geomesa/hbase/tools/ingest-libjars.list

Signed-off-by: Mutahir <kazmi.mutahir@gmail.com>
Successfully tested ingest with HBase and Yarn. Fixed missing jar issues.

GEOMESA-1690 HBase Distributed Ingest Enabled and Tested

---

geomesa-accumulo/geomesa-accumulo-dist/src/main/assemblies/component.xml

GEOMESA-1704 Exclude spark from tools lib

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureSource.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/BinProcessOutput.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/JoinProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/RouteSearchProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/CloseableIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/resources/process/route-search.xml
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/RouteSearchProcessTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoder.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoderTest.scala
geomesa-process/src/main/scala/org/locationtech/geomesa/process/ProcessFactory.scala
geomesa-process/src/test/resources/log4j.xml
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/FeatureExporter.scala

* Search for points or lines matching a route
* Standardized BIN encoding between iterator and non-iterators

1.2- GEOMESA-1691 Route search WPS

---

geomesa-spark/geomesa-spark-core/src/main/scala/org/locationtech/geomesa/spark/api/java/JavaGeoMesaSpark.scala

GEOMESA-1706 clean up JavaGeoMesaSpark API to removed need for cast in client code

---

geomesa-tools/src/main/resources/org/locationtech/geomesa/tools/ingest-libjars.list

Add parboiled to ingest libjars list

GEOMESA-1502 for 1.2 series

---

geomesa-spark/geomesa-spark-core/src/main/scala/org/apache/spark/geomesa/GeoMesaSparkKryoRegistratorEndpoint.scala
geomesa-spark/geomesa-spark-core/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSpark.scala
geomesa-spark/geomesa-spark-core/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkKryoRegistrator.scala
geomesa-spark/geomesa-spark-core/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkKryoRegistratorEndpoint.scala

GEOMESA-1701 Spark RPC endpoint for kryo schema

---

docs/user/spark/core.rst
docs/user/spark/sparksql.rst

GEOMESA-1659 Docs: Update discussion of Kryo registration for Spark

---

docs/tutorials/shallow-join.rst
docs/tutorials/spark.rst

GEOMESA-1710 Docs: update Spark tutorials for 1.3.x

---

docs/user/datastores/index_config.rst
geomesa-accumulo/geomesa-accumulo-datastore/README.md
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala
geomesa-accumulo/geomesa-accumulo-distributed-runtime/README.md
geomesa-accumulo/geomesa-accumulo-jobs/README.md
geomesa-blobstore/README.md
geomesa-cassandra/README.md
geomesa-convert/README.md
geomesa-hbase/geomesa-hbase-datastore/README.md
geomesa-jobs/README.md
geomesa-kafka/geomesa-kafka-datastore/README.md
geomesa-stream/README.md
geomesa-tools/conf/sfts/nyctaxi/reference.conf
geomesa-tools/conf/sfts/tdrive/reference.conf
geomesa-tools/conf/sfts/twitter/reference.conf
geomesa-web/geomesa-web-data/README.md

* Fix links in stub README.md files when they are rendered on Github.
* "attr_idx" -> "attr" as argument for "geomesa.index.enabled"

GEOMESA-1673 Small (mostly) docs fixes for 1.3.1

---

geomesa-spark/geomesa_pyspark/pom.xml

GEOMESA-1713 Put geomesa_pyspark module packaging behind a build profile

---

CONTRIBUTING.md

GEOMESA-1714 - Update the CONTRIBUTING.md regarding CLA to ECA change

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
pom.xml

I'm pretty sure we need both -C and -s at this point someone should verify

GEOMESA-1708 Require spec and converter args for ingest

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/BinConversionProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/BinConversionProcessTest.scala

GEOMESA-1717 Fixing BinProcess track flag

---

README.md
geomesa-accumulo/geomesa-accumulo-dist/pom.xml

GEOMESA-1718 Moving pyspark dist into profile

---

geomesa-hbase/geomesa-hbase-spark-runtime/pom.xml
geomesa-hbase/geomesa-hbase-spark-runtime/src/test/scala/org/locationtech/geomesa/hbase/spark/HBaseSparkProviderIntegrationTest.scala
geomesa-hbase/geomesa-hbase-spark-runtime/src/test/scala/org/locationtech/geomesa/hbase/spark/HBaseSparkProviderTest.scala

This PR is primarily a test for Anthony's work on implementing Spark in HBase.  
Signed-off-by: Mutahir <kazmi.mutahir@gmail.com>

GEOMESA-1724 HBase Spark Provider Test

---

geomesa-cassandra/geomesa-cassandra-tools/examples/ingest/csv/ingest_csv.sh

Fixing error "Error parsing arguments: Unknown option: --name-space" for ingest command

Fixing Cassandra Example

---

geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/export/FeatureExporterTest.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ConvertCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/BinExportCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportParams.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/DelimitedExporter.scala
geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/export/DelimitedExportImportTest.scala
geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/export/FeatureExporterTest.scala

* 'id' in attribute list can be used to export feature ID

GEOMESA-1630 Tools export only requested attributes

---

geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala

* Note: could not reproduce getCount always returning 0

GEOMESA-1695 Adding unit test for HBase counts

---

docs/tutorials/shallow-join.rst
docs/tutorials/spark.rst

GEOMESA-1729 Point tutorials at geomesa repo

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/visitor/QueryPlanFilterVisitor.scala

GEOMESA-1705 Handling bboxes with out-of-world coordinates

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloIndexAdapter.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/id/RecordQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyDensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z2DensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3DensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala

GEOMESA-1607 Enabling density iterator against AttributeIndex

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/attribute/AttributeQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/id/RecordQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/XZ2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/XZ3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoAttributeKeyValueIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyDensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z2DensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3DensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/legacy/DensityIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala

1.2 - GEOMESA-1607 Enabling density iterator against AttributeIndex

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/ConfigurableIndexesTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaIndexManager.scala

GEOMESA-1722 Adding check for invalid enabled indices

---

pom.xml

GEOMESA-1736 resolve hudson build maven classpath issue

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyStatsIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/stats/StatsIteratorProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/stats/KryoLazyStatsIteratorProcessTest.scala

GEOMESA-1737 - Fix Json output for the StatsIteratorProcess

---

docs/user/geojson.rst

JSONPath CQL filter function docs.

---

docs/user/kafka/consumers.rst
docs/user/kafka/usage.rst
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/consumer/KafkaConsumerFactory.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/test/scala/org/locationtech/geomesa/kafka08/MockKafka.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/consumer/KafkaConsumerFactory.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/test/scala/org/locationtech/geomesa/kafka09/MockKafka.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/consumer/KafkaConsumerFactory.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/test/scala/org/locationtech/geomesa/kafka10/MockKafka.scala

Exposed Kafka auto.offset.reset config as autoOffsetReset data store param.

GEOMESA-1728 Expose Kafka's auto.offset.reset configuration via KafkaDataStore Params

---

geomesa-accumulo/geomesa-accumulo-dist/pom.xml
geomesa-accumulo/geomesa-accumulo-dist/src/main/assemblies/component.xml
geomesa-cassandra/geomesa-cassandra-dist/pom.xml
geomesa-cassandra/geomesa-cassandra-dist/src/main/assemblies/component.xml
geomesa-hbase/geomesa-bigtable-dist/pom.xml
geomesa-hbase/geomesa-bigtable-dist/src/main/assemblies/component.xml
geomesa-hbase/geomesa-hbase-dist/pom.xml
geomesa-hbase/geomesa-hbase-dist/src/main/assemblies/component.xml
geomesa-kafka/geomesa-kafka-dist/assemblies/component.xml
geomesa-kafka/geomesa-kafka-dist/geomesa-kafka-08-dist/pom.xml
geomesa-kafka/geomesa-kafka-dist/geomesa-kafka-09-dist/pom.xml
geomesa-kafka/geomesa-kafka-dist/geomesa-kafka-10-dist/pom.xml
pom.xml

GEOMESA-1738 Include data jar in tools dists

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Histogram.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/MinMax.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Frequency.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Histogram.scala

GEOMESA-1741 Adding exception handling in stat observe

---

geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraFeatureIndex.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala

GEOMESA-1752 - Improve C* Unit test stability

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
geomesa-accumulo/geomesa-accumulo-raster/src/main/scala/org/locationtech/geomesa/raster/iterators/IteratorExtensions.scala
geomesa-features/geomesa-feature-common/pom.xml
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/ScalaSimpleFeature.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/TransformSimpleFeature.scala
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/features/TransformSimpleFeatureTest.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaProducerFeatureStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaProducerFeatureStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaProducerFeatureStore.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/ImmutableFeatureId.scala

GEOMESA-1758 Transform simple feature wrapper

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
geomesa-hbase/geomesa-hbase-dist/pom.xml
geomesa-hbase/geomesa-hbase-dist/src/main/assemblies/component.xml
geomesa-hbase/geomesa-hbase-distributed-runtime/pom.xml
geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/HBaseDataStoreCommand.scala
geomesa-hbase/pom.xml
geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa-site.xml.template
pom.xml

GEOMESA-1753 HBase Distributed Runtime

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/collection/CloseableIterator.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/SafeClose.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/collection/CloseableIteratorTest.scala

GEOMESA-1759 Concatenating closeable iterator, close with resources

---

docs/user/spark/index.rst
docs/user/spark/zeppelin.rst

GEOMESA-1751 Docs: configuring Zeppelin for Spark/Spark SQL

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyStatsIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/stats/StatsIteratorProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTransformsTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/stats/KryoLazyStatsIteratorProcessTest.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/TransformSimpleFeature.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/QueryPlanner.scala

GEOMESA-1757 Enable stats on transformed attribute fields

---

.gitignore
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/stats/KryoLazyStatsIteratorProcessTest.scala
geomesa-utils/pom.xml
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/DescriptiveStats.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/MinMax.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/SimpleMatrixUtils.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Stat.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/StatParser.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/StatSerializer.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/DescriptiveStatsTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/SimpleMatrixUtilsTest.scala
pom.xml

GEOMESA-1763 Implement Descriptive Stats

---

geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/DescriptiveStatsTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/SimpleMatrixUtilsTest.scala

GEOMESA-1770 Fix error in Stats tests

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/DescriptiveStats.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/SimpleMatrixUtils.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/SimpleMatrixUtilsTest.scala

GEOMESA-1772 Add ability to compare matrices w/ absolute and relative tolerances

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/query/QueryProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/stats/StatsIteratorProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/query/QueryProcessTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/stats/KryoLazyStatsIteratorProcessTest.scala

GEOMESA-1773 WPS cannot accept java.util.List

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/stats/KryoLazyStatsIteratorProcessTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/CountStat.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/DescriptiveStats.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/EnumerationStat.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Frequency.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/GroupBy.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Histogram.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/IteratorStackCount.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/MinMax.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/SeqStat.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Stat.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/StatSerializer.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/TopK.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Frequency.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Z3Histogram.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/CountStatTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/EnumerationStatTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/GroupByTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/MinMaxTest.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/StatTestHelper.scala

GEOMESA-1774 Convert all Stat JSON serialization to GSON

---

geomesa-hbase/geomesa-hbase-datastore/src/main/java/org/locationtech/geomesa/hbase/filters/JSimpleFeatureFilter.java
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala

This pull request implements Remote Transforms for HBase.
All tests for the HBase Datastore have passed.
Signed-off-by: Spandan Agrawal <spandanagrawal@gmail.com>

GEOMESA-1767 Remote Transforms for HBase

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/StatParser.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/BasicParser.scala

GEOMESA-1776 Recursively parse groupBy stats

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreStatsTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/StatsBasedEstimator.scala

GEOMESA-1790 Fixing estimated counts for schemas without dates

---

docs/user/datastores/index_config.rst
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/DateIndexTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/GeoMesaSchemaValidator.scala

GEOMESA-1786 Adding flag to disable indexing of default dates

---

geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ2Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ3Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z2Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z3Index.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/NormalizedDimension.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/Z2SFC.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/Z3SFC.scala

GEOMESA-1789 Improved error messages for feature indexing validation

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/collection/CloseableIterator.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/SafeClose.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/io/SafeCloseTest.scala

GEOMESA-1796 Fixing WithClose for errors in initialization of closeables

---

geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureStore.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/collection/CloseableIterator.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/SafeClose.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/io/SafeCloseTest.scala

GEOMESA-1792 Improved error handling for featureStore.addFeatures

---

geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/GeoMesaHBaseInputFormat.scala

GEOMESA-1800 Fixing HBase input format next

---

geomesa-accumulo/geomesa-accumulo-datastore/pom.xml
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/query/QueryProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/stats/StatsIteratorProcess.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/process/unique/UniqueProcess.scala

Fix ReTypingFeatureCollection Issue with some WPS Processors

GEOMESA-1798 Fix ReTypingFeatureCollection Issue with some WPS Processors

---

geomesa-convert/geomesa-convert-avro/src/main/scala/org/locationtech/geomesa/convert/avro/AvroSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/LineMode.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureValidator.scala
geomesa-convert/geomesa-convert-fixedwidth/src/main/scala/org/locationtech/geomesa/convert/fixedwidth/FixedWidthConverters.scala
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-osm/src/main/scala/org/locationtech/geomesa/convert/osm/OsmNodesConverter.scala
geomesa-convert/geomesa-convert-osm/src/main/scala/org/locationtech/geomesa/convert/osm/OsmWaysConverter.scala
geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/ValidatorTest.scala
geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XMLConverter.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/BinnedTime.scala

Needs testing of two features:
1. Converter validators
2. Transaction aka Commit Mode - stream is processed all together or not.

GEOMESA-1793 Converter validation

---

.travis.yml
.travisbuild.sh

GEOMESA-1814 Improve Travis caching

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyDensityIterator.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/KryoLazyDensityUtils.scala

GEOMESA-1795 Move density iterator result to user data

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyDensityIterator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/KryoLazyDensityCoprocessor.scala
geomesa-hbase/geomesa-hbase-native-api/src/test/java/org/locationtech/geomesa/hbase/nativeapi/GeoMesaQueryTest.java

GEOMESA-1821 Fix issue with Density Process build

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/CompositeConverter.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/EvaluationContext.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
geomesa-convert/geomesa-convert-fixedwidth/src/main/scala/org/locationtech/geomesa/convert/fixedwidth/FixedWidthConverters.scala
geomesa-convert/geomesa-convert-fixedwidth/src/test/resources/sft_testsft.conf
geomesa-convert/geomesa-convert-fixedwidth/src/test/scala/org/locationtech/geomesa/convert/fixedwidth/FixedWidthConverterTest.scala

GEOMESA-1831 clear evaluation context between records

---

geomesa-convert/geomesa-convert-avro/src/main/scala/org/locationtech/geomesa/convert/avro/AvroPathFunctionFactory.scala
geomesa-convert/geomesa-convert-avro/src/main/scala/org/locationtech/geomesa/convert/avro/AvroSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-avro/src/test/scala/org/locationtech/geomesa/convert/avro/AvroTransformersTest.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/EvaluationContext.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonFunctionFactory.scala
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-osm/src/main/scala/org/locationtech/geomesa/convert/osm/OsmField.scala
geomesa-convert/geomesa-convert-osm/src/main/scala/org/locationtech/geomesa/convert/osm/OsmNodesConverter.scala
geomesa-convert/geomesa-convert-osm/src/main/scala/org/locationtech/geomesa/convert/osm/OsmWaysConverter.scala
geomesa-convert/geomesa-convert-scripting/src/main/scala/org/locationtech/geomesa/convert/scripting/ScriptingFunctionFactory.scala
geomesa-convert/geomesa-convert-scripting/src/test/scala/org/locationtech/geomesa/convert/scripting/ScriptingFunctionFactoryTest.scala
geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala
geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XMLConverter.scala
geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlFunctionFactory.scala
geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/ConverterInputFormat.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ConvertCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/ConverterIngest.scala

GEOMESA-1836 Fix EvaluationContext.clear()

---

.travis.yml
.travisbuild.sh
pom.xml

GEOMESA-1839 Fix Travis CI build timeouts

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala

GEOMESA-1816 Fixing z-ordering of intervals with duration less than 2 seconds

---

docs/pom.xml
geomesa-hbase/geomesa-hbase-tools/bin/geomesa-hbase
geomesa-test/bin/common-functions.sh
geomesa-test/bin/geomesa-test-accumulo.sh
geomesa-test/bin/geomesa-test-hbase.sh
geomesa-test/pom.xml
geomesa-test/src/main/assemblies/binary-release.xml
geomesa-test/src/main/assemblies/component.xml
pom.xml

GEOMESA-1842 Move GM Test to geomesa-test module

---

geomesa-process/src/main/scala/org/locationtech/geomesa/process/DensityProcess.scala

GEOMESA-1848 Clean room implementation of DensityProcess.flipXY

---

geomesa-process/src/main/scala/org/geotools/process/vector/BBOXExpandingVisitor.scala
geomesa-process/src/main/scala/org/locationtech/geomesa/process/DensityProcess.scala

GEOMESA-1849 Using geotools BBOXExpandingFilterVisitor in DensityProcess

---

geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/HBaseSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-core/src/main/scala/org/locationtech/geomesa/spark/DataStoreConnector.scala

* Created DataStoreConnector that handles caching calls to DataStoreFinder.getDataStore
* Created unsafe save method in HBaseSpatialRDDProvider that does not check the schema
* Modified save and rdd methods from HBaseSpatialRDDPRovider to use DataStoreConnector to use cached data stores

GEOMESA-1840 Limit listing hbase/bigtable tables

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/analytic/StatsProcessTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/analytic/UniqueProcessTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/query/ProximitySearchProcessTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/query/QueryProcessTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/package.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterPackageObjectTest.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/GeoMesaProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/DensityProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/Point2PointProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/SamplingProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/StatsProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/UniqueProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/query/JoinProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/query/ProximitySearchProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/query/QueryProcess.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/query/RouteSearchProcess.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/DensityProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/Point2PointProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/SamplingProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/StatsProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/UniqueProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/query/ProximitySearchProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/query/QueryProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/query/RouteSearchProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcessTest.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/transform/BinConversionProcessTest.scala
geomesa-utils/pom.xml
pom.xml

* Note: does not fix KNN or TubeSelect
note: stacks on top of #1537

GEOMESA-1845 Ensuring processes can be visited locally

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala

GEOMESA-1647 Parsing literal negative doubles/floats in converters

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/EvaluationContext.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala

GEOMESA-1851 Propagate failed json parsing errors in JsonConverter

---

geomesa-hbase/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/index/BigtableFeatureIndex.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/java/org/locationtech/geomesa/hbase/filters/JSimpleFeatureFilter.java
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/HBaseZFilters.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBasePlatform.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ2Index.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ3Index.scala

GEOMESA-1804 Ordering priority for HBase filters

---

geomesa-accumulo/geomesa-accumulo-distributed-runtime/pom.xml
geomesa-accumulo/geomesa-accumulo-jobs/pom.xml
geomesa-hbase/geomesa-hbase-gs-plugin/pom.xml
geomesa-test/bin/common-functions.sh
pom.xml

* Relocating fasterxml classes to avoid conflict with hadoop

GEOMESA-1859 Fixing arrow accumulo distributed export

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloIndexAdapter.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/ArrowFileIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyFilterTransformIterator.scala
geomesa-index-api/pom.xml
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowBatchScan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowFileScan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/DensityScan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/SamplingIterator.scala

GEOMESA-1866 Refactoring Arrow scans for shared use

---

geomesa-accumulo/geomesa-accumulo-dist/pom.xml
geomesa-accumulo/geomesa-accumulo-dist/src/main/assemblies/component.xml
geomesa-accumulo/geomesa-accumulo-raster-distributed-runtime/README.md
geomesa-accumulo/geomesa-accumulo-raster-distributed-runtime/pom.xml
geomesa-accumulo/pom.xml
pom.xml

GEOMESA-1870 Separating raster runtime jar into separate module

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/ArrowBatchAggregator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/ArrowFileAggregator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/utils/CoprocessorConfig.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureCollection.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseArrowTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseTestRunnerTest.scala

GEOMESA-1871 HBase distributed Arrow queries

---

docs/user/process.rst
geomesa-process/geomesa-process-vector/src/main/resources/META-INF/services/org.locationtech.geomesa.process.GeoMesaProcess
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/TrackLabelProcess.scala
geomesa-process/geomesa-process-vector/src/test/resources/track-select.sld
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/TrackLabelProcessTest.scala

GEOMESA-1860 Track label process

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BaseAggregatingIterator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/ArrowBatchAggregator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/ArrowFileAggregator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseAggregator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseBinAggregator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseDensityAggregator.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala

GEOMESA-1872 Not allocating per-row objects in aggregating scans

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryStrategyDeciderTest.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/AttributeFilterStrategy.scala

GEOMESA-1762 De-prioritize range attribute queries in query planning

---

geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseArrowTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseBinAggregatorTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDensityFilterTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseTestRunnerTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseVisibilityTest.scala

GEOMESA-1873 Share catalogTableName in HBase tests

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureCollection.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala

GEOMESA-1875 Wire up the HBase coprocessor supported visitors 
GEOMESA-1876 Add Coprocessor and Filter info to the HBase query explainer

GEOMESA-1875 and GEOMESA-1876 

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala

GEOMESA-1877 Fix coprocessorConfig name change in HBase query explainer.

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/BinAggregatingScan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/DensityScan.scala

GEOMESA-1879 Fixing configuration of BIN and density queries with transforms

---

docs/user/hbase/kerberos.rst
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/GeoMesaHBaseInputFormat.scala

GEOMESA-1880 Refactor HBase Kerberos support and add logging

---

docs/user/accumulo/commandline_tools.rst
docs/user/kafka/commandline.rst
geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/AccumuloRunner.scala
geomesa-arrow/geomesa-arrow-tools/src/main/scala/org/locationtech/geomesa/arrow/tools/ArrowRunner.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/CassandraRunner.scala
geomesa-hbase/geomesa-bigtable-tools/src/main/scala/org/locationtech/geomesa/bigtable/tools/BigtableRunner.scala
geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/HBaseRunner.scala
geomesa-kafka/geomesa-kafka-tools/geomesa-kafka-08-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaRunner.scala
geomesa-kafka/geomesa-kafka-tools/geomesa-kafka-09-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaRunner.scala
geomesa-kafka/geomesa-kafka-tools/geomesa-kafka-10-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaRunner.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/ClasspathCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/ConfigureCommand.scala

* Documented classpath command
* Documented configure command

GEOMESA-1810 GeoMesa 'classpath' command is not documented

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/LiveKafkaConsumerFeatureSource.scala

GEOMESA-1897 Add try/catch to live kafka consumer

---

geomesa-hbase/geomesa-bigtable-spark/src/main/scala/org/locationtech/geomesa/bigtable/spark/BigtableSparkRDDProvider.scala

GEOMESA-1898 Fixing compile in BigtableSparkRDDProvider

---

geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/AttributeIndex.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/InMemoryMetadata.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala

GEOMESA-1902 Fixing secondary upper ranges in attribute index

---

docs/user/spark/sparksql.rst
geomesa-memory/geomesa-cqengine-datastore/src/main/scala/org/locationtech/geomesa/memory/cqengine/datastore/GeoCQEngineFeatureStore.scala
geomesa-spark/geomesa-spark-geotools/src/main/scala/org/locationtech/geomesa/spark/geotools/GeoToolsSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-geotools/src/test/scala/org/locationtech/geomesa/spark/geotools/GeoToolsSpatialRDDProviderTest.scala
geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLDataTest.scala
geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLTestUtils.scala

Fixes GeoCQEngine write. Adds docs and tests.

GEOMESA-1904 Spark SQL Write

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/ConverterConfigResolver.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/CommonParams.scala
geomesa-utils/pom.xml
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/classpath/PathUtils.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/ArgResolver.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/ConfConversions.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SftArgResolver.scala

GEOMESA-1908 Support for loading configs from distributed file systems

---

geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaQueryRunner.scala
geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/LambdaDataStoreTest.scala

GEOMESA-1914 Fixing LDS persistent/transient query hints from view params

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcessTest.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcess.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcessTest.scala

GEOMESA-1918 Adding sort to arrow WPS

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/tube/TubeSelectProcessTest.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/tube/TubeBuilder.scala

GEOMESA-1922 Fixing tube select for empty inputs

---

geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/ZookeeperOffsetManager.scala
geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/InMemoryOffsetManager.scala

GEOMESA-1923 LDS - Parallelizing offset listeners

---

docs/_templates/footer.html
docs/common.py

GEOMESA-1925 Adding license to docs footer

---

docs/_static/css/theme_custom.css
docs/user/accumulo/data_management.rst
docs/user/architecture.rst
docs/user/datastores/analytic_queries.rst
docs/user/datastores/index.rst
docs/user/datastores/index_basics.rst
docs/user/datastores/index_config.rst
docs/user/datastores/index_overview.rst
docs/user/datastores/query_config.rst

GEOMESA-1679 Updating indexing docs

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/GeoMesaSchemaValidator.scala

GEOMESA-1883 Override of schema checks via system properties

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloIndexAdapter.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcessTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryHints.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geoserver/ViewParams.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowBatchScan.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaQueryRunner.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaQueryRunner.scala
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcess.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/transform/ArrowConversionProcessTest.scala

GEOMESA-1924 Adding arrow option to always calculate dictionaries

---

geomesa-security/src/main/scala/org/locationtech/geomesa/security/VisibilityEvaluator.scala
geomesa-security/src/test/scala/org/locationtech/geomesa/security/VisibilityEvaluatorTest.scala

GEOMESA-1926 Fixing bounds for valid visibility chars

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala

Spawning thread to periodically renew Kerberos TGT if needed

GEOMESA-1919 Periodically renew Kerberos TGT

---

geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala

GEOMESA-1927 Allowing override of kafka consumer group

---

geomesa-features/geomesa-feature-avro/src/main/scala/org/locationtech/geomesa/features/avro/serialization/AvroUserDataSerialization.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/ImmutableSimpleFeature.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/ScalaSimpleFeature.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/SerializationOption.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/GenericMapSerialization.scala
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializer.scala
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/serialization/KryoUserDataSerialization.scala
geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializerTest.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaFeatureWriter.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/ImmutableFeatureId.scala

GEOMESA-1930 Lambda data store - using immutable features

---

geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsIngestCommand.scala
geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetConverterIngest.scala
geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetConverterJob.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/AbstractIngest.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/AbstractIngestJob.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/AutoIngest.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/ConverterIngest.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/text/TextTools.scala

~note: stacks on top of #1605~

GEOMESA-1912 Adding progress indicator for reduce phase of fs ingest

---

geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/ZookeeperOffsetManager.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/DataStorePersistence.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/SharedState.scala
geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/InMemoryOffsetManager.scala
geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/ZookeeperOffsetManagerTest.scala

Reduces memory footprint of cache to a hashmap and a priority queue. I ran overnight and it seemed fine.
@jnh5y what do you think?

GEOMESA-1941 Lambda data store - reducing offset state memory footprint

---

geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoder.scala

GEOMESA-1946 Encode Feature Iterator

---

geomesa-hbase/geomesa-hbase-dist/src/main/assemblies/component.xml

GEOMESA-1949 Add autocomplete to hbase tools dist

---

docs/user/spark/index.rst
docs/user/spark/jupyter.rst
docs/user/spark/pyspark.rst
geomesa-spark/geomesa_pyspark/src/main/python/setup.py

Signed-off-by: Jason T. Brown <jason.brown@ccri.com>

GEOMESA-1943 PySpark setup documentation.

---

geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/DataStorePersistence.scala

GEOMESA-1950 Lambda ds - shuffle partition processing

---

geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureIterator.scala
geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/storage/converter/ConverterStorage.scala
geomesa-fs/geomesa-fs-storage-api/src/main/java/org/locationtech/geomesa/fs/storage/api/FileSystemStorage.java
geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
geomesa-fs/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/ParquetFSTest.scala

GEOMESA-1953 Conf objects per query

---

geomesa-fs/geomesa-fs-dist/pom.xml
geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh

GEOMESA-1945 Install FS Hadoop deps

---

geomesa-fs/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageUtils.scala
geomesa-fs/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/StorageUtilsTest.scala
geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetConverterJob.scala

GEOMESA-1957 Faster Metadata Generation and DistCP

---

geomesa-hbase/geomesa-bigtable-datastore/src/main/scala/org/locationtech/geomesa/bigtable/data/BigtableDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala

GEOMESA-1958 Fixing cluster check for Bigtable data store

---

geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/FilterConverter.scala
geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoMesaIndexPropertyTransformer.scala
pom.xml

* Fixed a couple scala_2.10 method calls

GEOMESA-1955 Adding default scala version property to support sbt builds

---

docs/user/filesystem/partition_schemes.rst
geomesa-fs/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/PartitionScheme.scala
geomesa-fs/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/PartitionSchemeTest.scala

GEOMESA-1961 FSDS Weekly Partition Scheme

---

docs/user/filesystem/partition_schemes.rst
geomesa-fs/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/PartitionScheme.scala
geomesa-fs/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/PartitionSchemeConfTest.scala

GEOMESA-1962 Use default DTG and Geom fields for parition scheme opts

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/attribute/AttributeQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/FilterHelperTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/MultiIteratorTest.scala
geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/SimpleFeatureArrowFileReader.scala
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureValidator.scala
geomesa-filter/pom.xml
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/Bounds.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-filter/src/test/resources/log4j.xml
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/BoundsTest.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala
geomesa-fs/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/PartitionScheme.scala
geomesa-fs/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/PartitionSchemeTest.scala
geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/FilterConverter.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/AttributeIndex.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/XZ3Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z3Index.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/StatsBasedEstimator.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/AttributeFilterStrategy.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/SpatioTemporalFilterStrategy.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/BinnedTime.scala

* Modified FilterHelper.extractAttributeBounds to track inclusivity of each side of bounds

GEOMESA-1969,GEOMESA-1939 Fixing unbounded date queries, FileSystem DS partition schema edge cases

---

geomesa-archetypes/geomesa-archetypes-gs-plugin/pom.xml
geomesa-kafka/geomesa-kafka-gs-plugin/pom.xml
geomesa-web/pom.xml

GEOMESA-1964 Fixing HBase assembly poms

---

docs/tutorials/geodocker-geomesa/geodocker-geomesa-local.rst
docs/tutorials/geodocker-geomesa/geodocker-geomesa-spark-on-aws.rst
docs/tutorials/geodocker-geomesa/index.rst
docs/tutorials/index.rst

GEOMESA-1967 Add docs for geodocker-geomesa on local machine.

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/AttributeIndexFilteringIteratorTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/StatsBasedEstimator.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/Frequency.scala

Signed-off-by: Emilio Lahr-Vivaz elahrvivaz@ccri.com

GEOMESA-1360 Accounting for error rates in attribute equals count estimation

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/Bounds.scala
geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/BoundsTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaIndexManager.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/StatsBasedEstimator.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/AttributeFilterStrategy.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala

~note: stacks on top of #1641~

GEOMESA-1971 Not merging attribute ranges during query planning

---

geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-json/src/test/scala/org/locationtech/geomesa/convert/json/JsonConverterTest.scala

GEOMESA-1975 Support for parsing complex geojson geometries in converters

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geoserver/ViewParams.scala

GEOMESA-1977 Support 'STRATEGY' for 'QUERY_INDEX' view params

---

geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraAttributeIndex.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala

GEOMESA-1979 Cassandra fixing secondary attribute ranges

---

docs/user/spark/pyspark.rst

GEOMESA-1981 Fix PySpark Docs createOrReplaceTempView

---

build/mvn

GEOMESA-1991 Allow users to specify zinc location

---

geomesa-tools/conf/sfts/geonames/reference.conf
geomesa-tools/conf/sfts/gtd/reference.conf
geomesa-tools/conf/sfts/nyctaxi/reference.conf
geomesa-tools/conf/sfts/osm-gpx/reference.conf
geomesa-tools/conf/sfts/osm/reference.conf
geomesa-tools/conf/sfts/tdrive/reference.conf
geomesa-tools/conf/sfts/twitter/reference.conf

* Standardizing type-name/fields/table sharing

GEOMESA-1994 Fixing index spec in predefined schemas

---

geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/CassandraDataStoreCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/CassandraRunner.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraCreateSchemaCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraDescribeSchemaCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraExplainCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraGetSftConfigCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraGetTypeNamesCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraIngestCommand.scala
geomesa-cassandra/geomesa-cassandra-tools/src/main/scala/org/locationtech/geomesa/cassandra/tools/commands/CassandraRemoveSchemaCommand.scala

GEOMESA-1978 Adding explain command for Cassandra tools

---

geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala

GEOMESA-1999 Lambda data store handling errors in initial offset seek

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala

GEOMESA-2007 Exposing fields in ToSimpleFeatureConverter to subclasses

---

geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
geomesa-convert/geomesa-convert-text/src/test/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterTest.scala

GEOMESA-2001 Allowing arbitrary delimiter in delimited converter

---

geomesa-arrow/geomesa-arrow-jts/pom.xml
geomesa-blobstore/geomesa-blobstore-accumulo/src/main/java/org/locationtech/geomesa/blob/accumulo/AccumuloGeoMesaBlobStore.java
geomesa-blobstore/geomesa-blobstore-api/src/main/java/org/locationtech/geomesa/blob/api/GeoMesaIndexedBlobStore.java
geomesa-convert/geomesa-convert-scripting/pom.xml
geomesa-fs/geomesa-fs-datastore/pom.xml
geomesa-fs/geomesa-fs-storage-common/pom.xml
geomesa-fs/geomesa-fs-storage-parquet/pom.xml
geomesa-hbase/geomesa-bigtable-spark/pom.xml
geomesa-hbase/geomesa-hbase-datastore/src/main/java/org/locationtech/geomesa/hbase/filters/JSimpleFeatureFilter.java
geomesa-hbase/geomesa-hbase-spark/pom.xml
geomesa-jupyter/geomesa-jupyter-leaflet/pom.xml
geomesa-security/src/main/java/org/locationtech/geomesa/security/SecurityUtils.java
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportParams.scala
pom.xml

* Use the 'central' profile to deploy to ossrh, then manually release from the sonatype UI

GEOMESA-1992 Pom changes for publishing to maven central

---

docs/user/convert/premade/index.rst
docs/user/convert/premade/osm.rst
docs/user/geojson.rst
geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonFunctionFactory.scala
geomesa-convert/geomesa-convert-osm/src/main/scala/org/locationtech/geomesa/convert/osm/OsmField.scala
geomesa-convert/geomesa-convert-osm/src/main/scala/org/locationtech/geomesa/convert/osm/OsmWaysConverter.scala
geomesa-tools/conf/sfts/osm/reference.conf

GEOMESA-2004 Using JSON for OSM tags

---

docs/common.py
docs/user/download.rst
docs/versions.py

GEOMESA-2009 - Fix download links in GeoMesa nightly documentation

---

.travisbuild.sh
geomesa-spark/geomesa-spark-sql/pom.xml
pom.xml

GEOMESA-2012 Updating maven plugin versions, fixing travis build script

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/attribute/AttributeQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/id/RecordQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/BackCompatibilityTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowFileIteratorTest.scala

* Fixes bug with attribute + index arrow accumulo queries

GEOMESA-2010 Arrow queries for old index implementations

---

docs/user/filesystem/commandline.rst
docs/user/index.rst
geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/FilteringIterator.scala
geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
geomesa-fs/geomesa-fs-storage-parquet/src/test/resources/log4j.xml
geomesa-fs/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/ParquetFSTest.scala

GEOMESA-2000 Supporting projecting transforms in file system data store

---

docs/user/hbase/install.rst

GEOMESA-2005 - Fix small typo in GeoMesa HBase docs

---

docs/user/hbase/install.rst

1.3 - GEOMESA-2005 - Fix small typo in GeoMesa HBase docs

---

geomesa-arrow/geomesa-arrow-datastore/src/main/scala/org/locationtech/geomesa/arrow/data/ArrowDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseVisibilityTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/NoOpMetadata.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/DistributedRunnableStats.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/KryoLazyStatsUtils.scala

GEOMESA-2022 Remote stats execution for hbase

---

geomesa-arrow/geomesa-arrow-datastore/src/main/scala/org/locationtech/geomesa/arrow/data/ArrowDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseVisibilityTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/NoOpMetadata.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/DistributedRunnableStats.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/KryoLazyStatsUtils.scala

1.3 - GEOMESA-2022 Remote stats execution for hbase

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/package.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala

GEOMESA-2015 Not registering coprocessors if remote filtering is disabled

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/package.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala

1.3 - GEOMESA-2015 Not registering coprocessors if remote filtering is disabled

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureCollection.scala
geomesa-hbase/geomesa-hbase-gs-plugin/pom.xml

* Added QueryVisitor to matched HBaseFeatureCollection

GEOMESA-2028 Fix HBase visitors

---

geomesa-accumulo/geomesa-accumulo-jobs/src/main/resources/org/locationtech/geomesa/jobs/accumulo-libjars.list

GEOMESA-2027 Fixing libjars for accumulo tools

---

geomesa-accumulo/geomesa-accumulo-jobs/src/main/resources/org/locationtech/geomesa/jobs/accumulo-libjars.list

1.3 - GEOMESA-2027 Fixing libjars for accumulo tools

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala

GEOMESA-2029 More Geometry Transformers

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala

GEOMESA-2030 Improve HBase query planning

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/resources/process/min-max.xml
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreStatsTest.scala
geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/ingest/ShpIngestTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseFeatureCollection.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/GeoMesaStats.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/MetadataBackedStats.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/NoopStats.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaStats.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/stats/TransientStats.scala
geomesa-process/geomesa-process-vector/src/main/resources/META-INF/services/org.locationtech.geomesa.process.GeoMesaProcess
geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/MinMaxProcess.scala
geomesa-process/geomesa-process-vector/src/test/scala/org/locationtech/geomesa/process/analytic/MinMaxProcessTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/MinMax.scala

1.3 - GEOMESA-2014 Attribute bounds WPS

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowBatchScan.scala

1.3 - GEOMESA-2034 Fixing cached batch size in arrow scans

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3Iterator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/HBaseZFilters.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ3Index.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseTestRunnerTest.scala

GEOMESA-2040 HBase - fixing z3 filter configuration

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3Iterator.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/HBaseZFilters.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ3Index.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseTestRunnerTest.scala

1.3 - GEOMESA-2040 HBase - fixing z3 filter configuration

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreFactory.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreFactory.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStoreFactory.scala
geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/LambdaDataStoreTest.scala

GEOMESA-2045 Adding namespace parameters to fix geoserver gml3 output

---

geomesa-accumulo/pom.xml
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala
geomesa-convert/geomesa-convert-simplefeature/pom.xml
geomesa-convert/geomesa-convert-simplefeature/src/main/resources/META-INF/services/org.locationtech.geomesa.convert.SimpleFeatureConverterFactory
geomesa-convert/geomesa-convert-simplefeature/src/main/scala/org/locationtech/geomesa/convert/simplefeature/SimpleFeatureSimpleFeatureConverter.scala
geomesa-convert/geomesa-convert-simplefeature/src/main/scala/org/locationtech/geomesa/convert/simplefeature/SimpleFeatureSimpleFeatureConverterFactory.scala
geomesa-convert/geomesa-convert-simplefeature/src/test/resources/reference.conf
geomesa-convert/geomesa-convert-simplefeature/src/test/scala/org/locationtech/geomesa/convert/simplefeature/SimpleFeatureSimpleFeatureConverterTest.scala
geomesa-convert/pom.xml

* Created a new converter that takes as input a SimpleFeature and
returns a new SimpleFeature based on a transformation specified
in a conf file.

GEOMESA-2044 Create a SimpleFeature to SimpleFeature converter

---

docs/user/geoserver.rst

GEOMESA-2026 Clarifying time enabled layer presentation in docs

---

docs/user/geoserver.rst

1.3 - GEOMESA-2026 Clarifying time enabled layer presentation in docs

---

geomesa-kafka/geomesa-kafka-datastore/pom.xml
geomesa-kafka/geomesa-kafka-dist/pom.xml
geomesa-kafka/geomesa-kafka-dist/src/main/assemblies/component.xml

GEOMESA-1829 Adding wps jars to kafka dist

---

geomesa-convert/geomesa-convert-redis-cache/src/main/scala/org/locationtech/geomesa/convert/redis/RedisEnrichmentCache.scala
geomesa-convert/geomesa-convert-redis-cache/src/test/scala/org/locationtech/geomesa/convert/redis/RedisEnrichmentCacheTest.scala

* Using JedisPool to manage connections
Signed-off-by: Anthony Fox <anthony.fox@ccri.com>

1.3 - GEOMESA-2047 Jedis is not thread safe

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloIndexAdapter.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/attribute/AttributeQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/id/RecordQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyStatsIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowDictionary.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowBatchScan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/KryoLazyStatsUtils.scala

GEOMESA-2046 Fixing arrow dictionary generation for attribute queries

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloIndexAdapter.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/attribute/AttributeQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/id/RecordQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyStatsIterator.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowDictionary.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/ArrowBatchScan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/KryoLazyStatsUtils.scala

1.3 - GEOMESA-2046 Fixing arrow dictionary generation for attribute queries

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/attribute/AttributeQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/IteratorTrigger.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexValuesTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/KryoLazyStatsUtils.scala

GEOMESA-2052 Fixing schema of attribute join index stat queries

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/attribute/AttributeQueryableIndex.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/IteratorTrigger.scala
geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexValuesTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/KryoLazyStatsUtils.scala

1.3 - GEOMESA-2052 Fixing schema of attribute join index stat queries

---

geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowDictionary.scala

GEOMESA-2053 Not using random long stream for dictionary ids

---

geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/ConverterInputFormat.scala
geomesa-spark/geomesa-spark-converter/src/main/scala/org/locationtech/geomesa/spark/converter/ConverterSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-converter/src/test/scala/org/locationtech/geomesa/spark/converter/ConverterSpatialRDDProviderTest.scala

GEOMESA-2043 Add projection support to Converter RDD Provider

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeWriter.scala
geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/vector/SimpleFeatureVectorTest.scala
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractLineStringVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiLineStringVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiPointVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiPolygonVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractPointVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractPolygonVector.java

1.3 - GEOMESA-2056 Fixing arrow null encoding

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeWriter.scala
geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/vector/SimpleFeatureVectorTest.scala
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractLineStringVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiLineStringVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiPointVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractMultiPolygonVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractPointVector.java
geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/impl/AbstractPolygonVector.java

GEOMESA-2056 Fixing arrow null encoding

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaDataStore.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/LiveKafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/main/scala/org/locationtech/geomesa/kafka/LiveFeatureCache.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/main/scala/org/locationtech/geomesa/kafka/LiveFeatureCacheCQEngine.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/main/scala/org/locationtech/geomesa/kafka/LiveFeatureCacheGuava.scala

1.3 - GEOMESA-2033 Adding consistency checker for kafka feature cache

---

docs/tutorials/geomesa-hbase-s3-on-aws.rst

GEOMESA-2042 Fixing link to HBase distro in AWS tutorial

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-datastore-common/src/main/scala/org/locationtech/geomesa/kafka/LiveFeatureCacheGuava.scala

1.3 - GEOMESA-2057 Making kafka cache removal check more lenient

---

geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCache.scala

GEOMESA-2057 Making kafka cache removal check more lenient

---

geomesa-arrow/geomesa-arrow-datastore/src/main/scala/org/locationtech/geomesa/arrow/data/ArrowDataStore.scala
geomesa-arrow/geomesa-arrow-tools/src/main/scala/org/locationtech/geomesa/arrow/tools/status/ArrowDescribeSchemaCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/DescribeSchemaCommand.scala

GEOMESA-2055 Adding dictionary output to arrow tools

---

geomesa-arrow/geomesa-arrow-datastore/src/main/scala/org/locationtech/geomesa/arrow/data/ArrowDataStore.scala
geomesa-arrow/geomesa-arrow-tools/src/main/scala/org/locationtech/geomesa/arrow/tools/status/ArrowDescribeSchemaCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/DescribeSchemaCommand.scala

1.3 - GEOMESA-2055 Adding dictionary output to arrow tools

---

docs/user/spark/sparksql.rst

GEOMESA-1916 Docs - Spatial UDTs are incorrect

---

geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/Z3Filter.scala

1.3 - GEOMESA-2058 Fixing serialization of HBase z-filter

---

docs/tutorials/geomesa-hbase-s3-on-aws.rst
docs/user/accumulo/ageoff.rst
docs/user/accumulo/install.rst
docs/user/hbase/install.rst
geomesa-hbase/geomesa-hbase-tools/bin/bootstrap-geomesa-hbase-aws.sh
geomesa-hbase/geomesa-hbase-tools/bin/geomesa-hbase
geomesa-hbase/geomesa-hbase-tools/bin/install-hbase.sh
geomesa-tools/bin/common-functions.sh
geomesa-tools/conf/geomesa-env.sh

* Infer classpath from 'hadoop classpath' and 'hbase classpath' commands
* Better doc for AWS setup

GEOMESA-2051 Classpath Documentation for AWS

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParam.scala

GEOMESA-2062 GeoServer data store page fails to load

---

build/cqs.tsv
pom.xml

GEOMESA-2060 Upgrade to caffeine 2.5.6

---

geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/AbstractSimpleFeature.scala
geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/ScalaSimpleFeature.scala
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializer.scala
geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/impl/LazyDeserialization.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/collection/AtomicBitSet.scala
geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/collection/AtomicBitSetTest.scala

GEOMESA-2070 Adding synchronization around lazy feature deserialization

---

docs/tutorials/geomesa-hbase-s3-on-aws.rst
docs/user/hbase/install.rst
geomesa-hbase/geomesa-hbase-tools/bin/bootstrap-geomesa-hbase-aws.sh
geomesa-hbase/geomesa-hbase-tools/src/main/resources/org/locationtech/geomesa/hbase/tools/ingest-libjars.list

GEOMESA-2065 Add json4s to HBase libjars

---

geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/GeometrySerialization.scala
geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/GeoMesaHBaseInputFormat.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/ClientSideFiltering.scala

GEOMESA-2078 Catching and logging errors in HBaseGeoMesaRecordReader

---

geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreFactory.scala
geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala

GEOMESA-2079 Better exceptions for invalid Cassandra contact point

---

docs/user/convert/xml.rst
geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XMLConverter.scala
geomesa-convert/geomesa-convert-xml/src/test/scala/org/locationtech/geomesa/convert/xml/XMLConverterTest.scala

GEOMESA-2077 Namespace handling for Saxon XML convert

---

geomesa-accumulo/geomesa-accumulo-spark-runtime/pom.xml
geomesa-hbase/geomesa-bigtable-spark-runtime/pom.xml

GEOMESA-2072 Excluding json4s from spark-runtime jars

---

pom.xml

GEOMESA-2066 Not publishing javadocs to locationtech due to Hudson failures

---

README.md
build/README.md
docs/tutorials/geomesa-raster.rst
docs/user/accumulo/raster.rst
docs/user/datastores/attributes.rst
docs/user/datastores/explaining.rst
docs/user/datastores/index.rst
docs/user/download.rst
geomesa-accumulo/geomesa-accumulo-raster/README.md
pom.xml

* Updating versions in main README
* Pointing to GitHub for downloads

GEOMESA-2067 Docs - enumerating attribute types

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloQueryPlan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/Explainer.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/utils/ExplainerTest.scala

GEOMESA-2083 Fixing lazy explain logging

---

geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-08-datastore/src/main/scala/org/locationtech/geomesa/kafka08/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-09-datastore/src/main/scala/org/locationtech/geomesa/kafka09/KafkaConsumerFeatureSource.scala
geomesa-kafka/geomesa-kafka-datastore/geomesa-kafka-10-datastore/src/main/scala/org/locationtech/geomesa/kafka10/KafkaConsumerFeatureSource.scala

GEOMESA-2082 Filter binding for Kafka data store

---

docs/user/convert/xml.rst
geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XMLConverter.scala
geomesa-convert/geomesa-convert-xml/src/test/scala/org/locationtech/geomesa/convert/xml/XMLConverterTest.scala

1.3 - GEOMESA-2077 Namespace handling for Saxon XML convert

---

geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloQueryPlan.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/Explainer.scala
geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/utils/ExplainerTest.scala

1.3 - GEOMESA-2083 Fixing lazy explain logging

---

geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/CreateSchemaCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/ConverterIngest.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala

GEOMESA-2036 CLI ingest - not requiring sft spec for existing types

---

docs/user/spark/sparksql.rst
geomesa-spark/geomesa-spark-converter/src/main/scala/org/locationtech/geomesa/spark/converter/ConverterSpatialRDDProvider.scala
geomesa-spark/geomesa-spark-converter/src/test/scala/org/locationtech/geomesa/spark/converter/ConverterSpatialRDDProviderTest.scala
geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala

GEOMESA-2080 General improvements to Spark SQL

---

build/cqs.tsv
docs/common.py
geomesa-kafka/geomesa-kafka-datastore/pom.xml
geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/EmbeddedKafka.scala
geomesa-kafka/geomesa-kafka-tools/bin/install-kafka.sh
geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerVersions.scala
geomesa-kafka/pom.xml
geomesa-lambda/pom.xml
pom.xml

GEOMESA-2085 Support for Kafka 1.0.0

---

geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala

GEOMESA-1583 Handle Query.ALL

---

docs/user/convert/function_overview.rst
docs/user/convert/function_usage.rst
geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala

GEOMESA-2097 Converter function to set empty strings null

---

geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/Transformers.scala
geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/TransformersTest.scala

1.3 - GEOMESA-2097 Converter function to set empty strings null

---

docs/user/accumulo/commandline_tools.rst
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/CommonParams.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ConvertCommand.scala
geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/AbstractIngest.scala
geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/ConvertCommandTest.scala
geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/fs/LocalDelegate.scala

GEOMESA-2087 Command line ingest from stdin

---

build/mvn

GEOMESA-2102 Updating zinc version to avoid raster compile errors

---

geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParam.scala

GEOMESA-2094 Fixing conversion of deprecated Duration parameters
