locationtech/geomesa

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerFeatureSource.scala
- geomesa-utils/pom.xml
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/ContentFeatureSourceSupport.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/TypeUpdatingFeatureReader.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/TypeUpdatingFeatureReaderTest.scala
KafkaConsumerFeatureSource now canRetype.
Signed-off-by: Michael Matz <mmatz@ccri.com>
> GEOMESA-777 add retyping support to KafkaConsumerFeatureSource

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/SimpleFeatureConverterFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/KafkaDataStoreTest.scala
- geomesa-kafka/pom.xml
* Bumped Kafka version to 0.8.2.1
* Changed conversion parse error logging to warn instead of debug
Signed-off-by: Anthony Fox <anthony.fox@ccri.com>
> GEOMESA-779 Bump Kafka version to 0.8.2.1

- geomesa-core/src/main/scala/org/locationtech/geomesa/core/index/AttributeIdxStrategy.scala
- geomesa-core/src/main/scala/org/locationtech/geomesa/core/index/FilterHelper.scala
- geomesa-core/src/test/scala/org/locationtech/geomesa/core/index/AttributeIndexStrategyTest.scala
- geomesa-core/src/test/scala/org/locationtech/geomesa/core/index/FilterHelperTest.scala
AttributeIdxStrategy now selects the best (lowest cost) attribute filter as the scan range.
Signed-off-by: Michael Matz <mmatz@ccri.com>
> GEOMESA-782 improve query plan for multiple attribute queries

- geomesa-core/src/main/scala/org/locationtech/geomesa/core/index/QueryPlanner.scala
- geomesa-core/src/test/scala/org/locationtech/geomesa/core/index/LazySortedIteratorTest.scala
- geomesa-core/src/test/scala/org/locationtech/geomesa/core/index/QueryPlannerTest.scala
* Queries with a sort by clause now perform sorting lazily.  This moves the buffer and sort time from the "planning" part of Explain Query to the first "hasNext" (or "next" if "hasNext" is skipped).
Signed-off-by: Michael Matz <mmatz@ccri.com>
> GEOMESA-784 Explain Query functionality does not work correctly with a sortBy clause

- geomesa-jobs/README.md
- geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/analytics/HistogramJob.scala
- geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/scalding/AccumuloSourceOptions.scala
Attribute histogram job results can now be written back to accumulo in a {feature-name}_stats table by setting the "geomesa.hist.write.to.accumulo" to true.
> GEOMESA-795 Write attribute histogram results to accumulo "_stats" table

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/process/knn/GenerateKNNQueryTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/package.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterPackageObjectTest.scala
Added quick unit tests and a function to decompose ANDs.
Modified unit test with decomposeBinary.
> GEOMESA-817 Function partitionSubFilters does not handle nested ANDs

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/package.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/AvailableTables.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/GeoMesaTable.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/SftBuilder.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/ConfigurableIndexesTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryFilterSplitterTest.scala
- geomesa-plugin/src/main/scala/org/locationtech/geomesa/plugin/GeoMesaStoreEditPanel.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
* Store configurable tables in metadata
* Create only tables for specified indexes
* Modify SFT spec to allow arbitrary feature kv pairs in SFT
> GEOMESA-875 Configurable index tables

- README.md
- docs/pom.xml
- pom.xml
* Having docs be an included module will handle pom versions during releases
* Docs will not actually be built unless you use the 'docs' profile
> GEOMESA-1104 Adding docs to default build

- docs/common.py
- docs/user/installation_and_configuration.rst
- pom.xml
* Integrates with the Eclipse signing service.
This service is (and can) only used by the LocationTech build server.
* Adds documentation for the LocationTech downloads page.
> GEOMESA-1204 Use LocationTech/Eclipse Jar signing

- docs/_static/css/theme_custom.css
- docs/common.py
- docs/tutorials/geomesa-quickstart-kafka.rst
- docs/user/installation_and_configuration.rst
- geomesa-tools/README.md
* Update settings in common.py.
* Remove references to vecmath.
* Update Kafka tutorial with feature listener and load tester.
> GEOMESA-1175 Doc fixes for 1.2.2 release.

- geomesa-gs-plugin/geomesa-hbase-gs-plugin/README.md
- geomesa-gs-plugin/geomesa-hbase-gs-plugin/pom.xml
Restores the shaded Guava version, and updates installation
instructions.
> GEOMESA-1213 Fix HBase GeoServer plugin deployment

- docs/user/installation_and_configuration.rst
Signed-off-by: Nathan Zimmerman <npzimmerman@gmail.com>
This should bring the documentation up to date with what I needed to do to bring up a a geomesa extended geoserver instance for accumulo 1.7
> Add documentation for the use of htrace

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/AttributeTable.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/AttributeTableV5.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/AvailableTables.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/GeoMesaTable.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/HighCardinalityAttributeOrQueryTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/ConfigurableIndexesTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryFilterSplitterTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
> GEOMESA-1198 Changing attribute table suffix

- docs/user/data_management.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureWriter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/AttributeTable.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/AttributeTableV5.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/GeoMesaTable.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/RecordTable.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/SpatioTemporalTable.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/Z2Table.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/tables/Z3Table.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AttributeIdxStrategy.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/RecordIdxStrategy.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/Z2IdxStrategy.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategy.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoVisibilityRowEncoder.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreAttributeVisibilityTest.scala
- geomesa-features/geomesa-feature-avro/src/main/scala/org/locationtech/geomesa/features/avro/AvroFeatureSerializer.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/SimpleFeatureSerializer.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializer.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/VisibilityLevel.scala
* Enable in the sft with the user data: geomesa.visibility.level='attribute'
* Put comma-delimited visibilities in the simple feature user data corresponding to each attribute
* WARNING: Experimental, does not support all query types and compatibility is not gauranteed going forward
> GEOMESA-1253 Initial support for attribute level visibility

- docs/README.md
- docs/build.xml
- docs/common.py
- docs/pom.xml
(Mostly) fixes LaTeX build of docs, which was not changed when we
reorganized how the different manuals were built with HTML.
> GEOMESA-1297 Fix LaTeX build

- docs/user/hbase_datastore.rst
- geomesa-hbase/README.md
* Fixed link formatting from using Markdown-style to reStructuredText-style so
that it renders properly, both on GitHub and on geomesa.org HTML pages
* Added code formatting for parameter names
* Fixed capitalization of Bigtable, added link to home page
> Fixes for HBase/Bigtable data stores docs

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/GeoMesaMetadata.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/GeoMesaMetadataStats.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/StatsCombiner.scala
* Metadata is split into multiple rows instead of a single row
* First time a schema is read in the single-row format, it will be converted to multi-row
> GEOMESA-1306 Splitting stats table

- docs/build.xml
- docs/common.py
- docs/pom.xml
- docs/versions.py
- pom.xml
Setting versions via Sphinx command line was not doing all of the
other substitions properly. This solution sets the versions via
the maven-resources-plugin prior to Sphinx invocation.
> GEOMESA-1108 Pull version for docs from pom.xml properly

- geomesa-tools/README.md
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/FeatureExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/accumulo/commands/ExportCommand.scala
* Adds a --without-types parameter to be used with delimited text formats (csv|tsv) to omit type headers on export.
Signed-off-by: Charles Kelly <charles.kelly@ccri.com>
> GEOMESA-1264 Change csv export to have with-types flag

- README.md
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerFeatureSource.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/KafkaDataStoreTest.scala
* Fixes issue where bbox is large and polygon is small for live AND queries
* Adds unit test for large bbox with small polygon
* Fixes other disabled unit tests
Signed-off-by: David Seapy <ddseapy@ccri.com>
> GEOMESA-1389 - Kafka Live Queries don't work for small polygons with big bboxes

- docs/tutorials/geomesa-examples-gdelt.rst
- docs/tutorials/geomesa-quickstart-accumulo.rst
- docs/tutorials/geomesa-quickstart-hbase.rst
- docs/tutorials/geomesa-tubeselect.rst
- docs/user/accumulo_datastore.rst
- docs/user/geoserver.rst
- docs/user/installation_and_configuration.rst
- docs/user/process.rst
Geoserver.org changed the structuring of some of their documentation, breaking the relative (/stable/) links in the geomesa docs. I've corrected these and standardized all the links to point to 'stable' docs rather than a mix of 'stable' and 'latest'.
> GEOMESA-1392 Fix Geoserver Docs links in Geomesa Docs

- geomesa-compute/pom.xml
This PR is intended to alleviate some issues using the `geomesa-compute` module in some Apache Spark environments.  In particular, those with hierarchical ClassLoaders (e.g. the Apache Toree Jupyter Spark Kernel).  The presence of some classes in a parent ClassLoader will preclude loading of interface implementations present in child ClassLoaders due to visibility issues.
To deal with this we can either:
- Include interface implementations in the the compute module.  This fixes the sent of implementations that may be used.
- Exclude classes that load interfaces from the compute module.  This requires explicit or deferred loading of the jar responsible for loading the interface implementation and all the desired implementations.
This PR _includes_ the GeoTools `gt-epsg-wkt` module so that …
> Update compute module dependencies and shaded jar exclusions

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
Added error handling for invalid SFT type with information on accepted values.
> GEOMESA-1072 Invalid types in SFT parsing are not handled well

- build/mvn
- pom.xml
It appears the placement of `scala.binary.version` inside a profile precludes its use in the resolution of transitive dependencies when geomesa modules are used in sbt builds.  This commit resolves this by pulling the `scala.binary.version` outside of the scala version-specific profiles.  The spark version change script will update the property value as needed.
> GEOMESA-1443 Update parent pom to work around sbt/ivy artifact resolution issue

- geomesa-memory/src/main/java/org/locationtech/geomesa/memory/cqengine/attribute/SimpleFeatureAttribute.java
SimpleNullableAttribute, not SimpleAttribute, which by CQEngine
contract should not return nulls.
> GEOMESA-1471 SimpleFeatureAttribute should inherit from

- geomesa-accumulo/geomesa-accumulo-distributed-runtime/pom.xml
looked over build, issue is isolated to `geomesa-accumulo-distributed-runtime`
> GEOMESA-1487 proper generation of accumulo runtime jars for scala 2.10 build

- docs/_static/css/theme_custom.css
- docs/tutorials/geohash-substrings.rst
- docs/tutorials/geomesa-examples-authorizations.rst
- docs/tutorials/geomesa-examples-avro.rst
- docs/tutorials/geomesa-examples-featurelevelvis.rst
- docs/tutorials/geomesa-examples-gdelt.rst
- docs/tutorials/geomesa-examples-transformations.rst
- docs/tutorials/geomesa-quickstart-accumulo.rst
- docs/tutorials/geomesa-quickstart-hbase.rst
- docs/tutorials/geomesa-quickstart-kafka.rst
- docs/tutorials/geomesa-quickstart-storm.rst
- docs/tutorials/geomesa-raster.rst
- docs/tutorials/index.rst
- docs/user/accumulo_datastore.rst
- docs/user/kafka_datastore.rst
- docs/user/web_data.rst
* Add docs about feature events.
* Fix query planner links in Accumulo chapter.
* Fix Spark properties links.
* Fix link to GS install docs, link for XZ tools.
* Fix links in authorizations tutorials.
* Fix link in geohash "tutorial".
* Fix Kafka link.
* RST-ify geomesa-raster tutorial.
* Add a note about using the proper GeoMesa tutorials release.
* Add note about Hadoop 2.6 version.
> GEOMESA-1536, GEOMESA-1525, GEOMESA-1227 Docs fixes

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyFilterTransformIterator.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala
* Avoid calling `contains`
* Use a mutable buffer for the offsets and lengths
> GEOMESA-1550 Improve performance of KryoBufferSimpleFeature

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyFilterTransformIterator.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/KryoBufferSimpleFeature.scala
* Avoid calling `contains`
* Use a mutable buffer for the offsets and lengths
> 1.2 - GEOMESA-1550 Improve performance of KryoBufferSimpleFeature

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/attribute/AttributeQueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/encoders/BinEncoder.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/BinLineStringTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/RecordIdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/XZ2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIteratorTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoder.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/Convert2ViewerFunction.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoderTest.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/function/Convert2ViewerFunctionTest.scala
* Changing trackId to be an Int in case classes to remove inconsistency with BinAggregatingIterator
> 1.2 - GEOMESA-1552 Fixing check for join query against BIN non-default geometries

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/attribute/AttributeQueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/encoders/BinEncoder.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/BinLineStringTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/RecordIdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/XZ2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/BinAggregatingIteratorTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoder.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/Convert2ViewerFunction.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/function/BinaryOutputEncoderTest.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/function/Convert2ViewerFunctionTest.scala
* Changing trackId to be an Int in case classes to remove inconsistency with BinAggregatingIterator
> GEOMESA-1552 Fixing check for join query against BIN non-default geometries

- geomesa-accumulo/geomesa-accumulo-tools/bin/setup-namespace.sh
before this change script would fail if called as `./setup-namespace.sh`
> GEOMESA-1559 execute correctly independent of pwd

- geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/FeatureSpecificReaderTest.scala
- geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/serde/Version1BackwardsCompatTest.scala
Fix issue with failing avro serialization unit tests on systems where default file encoding was something other than UTF-8
> GEOMESA-1567 Explicitly use UTF-8 for avro serialization test files.

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z2/Z2QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z2Iterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3Iterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/Z3IteratorTest.scala
* Avoids boxing of primitives
* Reduces calculations in 'init'
* Note: contains iterator configuration changes, client and server jars must match
> GEOMESA-1553 Performance improvements for z-iterators

- docs/user/examples.rst
The removeschema example had the incorrect parameter -fn.  Changed to -f.
In "Setting up an Ingest Converter" the example incorrectly says to execute "geomesa env".  Without any parameters this just describes the usage.  Added command parameters and split into two commands.
> Updates documentation user examples

- geomesa-accumulo/geomesa-accumulo-spark/src/main/scala/org/locationtech/geomesa/spark/accumulo/AccumuloSpatialRDDProvider.scala
- geomesa-accumulo/geomesa-accumulo-spark/src/test/scala/org/locationtech/geomesa/accumulo/spark/AccumuloSparkProviderTest.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala
- geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLTestUtils.scala
* Better handling of FIDs on write
> GEOMESA-1612 Spark SQL should reuse FIDs on write if available

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloFeatureIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/z3/Z3WritableIndex.scala
- geomesa-accumulo/geomesa-accumulo-spark/src/test/scala/org/locationtech/geomesa/accumulo/spark/AccumuloSparkProviderTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaSparkSQL.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/ConvertCommandTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypeLoader.scala
* Second attempt at fixing AccumuloDataStoreDeleteTest
* Removed feature-level synchronization in AccumuloDataStore -
Catalog-level synchronization would need to also obtain each feature lock
* Turned down various test logging
> GEOMESA-1526 Synchronizing calls to delete mock accumulo tables

- docs/user/spark/index.rst
- docs/user/spark/jupyter.rst
Adds a section to the Spark chapter describing how to set up Jupyter + Toree to run GeoMesa Spark.
> GEOMESA-1536 Document Jupyter deployment

- docs/common.py
- docs/developer/introduction.rst
- docs/tutorials/geomesa-examples-gdelt.rst
- docs/tutorials/geomesa-quickstart-accumulo.rst
- docs/tutorials/geomesa-raster.rst
- docs/tutorials/geomesa-tubeselect.rst
- docs/tutorials/spark.rst
- docs/user/accumulo/commandline_tools.rst
- docs/user/accumulo/examples.rst
- docs/user/accumulo/install.rst
- docs/user/bigtable/geoserver.rst
- docs/user/bigtable/index.rst
- docs/user/convert/premade/gdelt.rst
- docs/user/convert/premade/geolife.rst
- docs/user/convert/premade/geonames.rst
- docs/user/convert/premade/gtd.rst
- docs/user/convert/premade/index.rst
- docs/user/convert/premade/nyctaxi.rst
- docs/user/convert/premade/osm-gpx.rst
- docs/user/convert/premade/tdrive.rst
- docs/user/convert/premade/twitter.rst
- docs/user/convert/usage_tools.rst
* Fix numerous bad links detected via automated link checking
* Change references to GEOMESA_HOME environment variable
to GEOMESA_ACCUMULO_HOME.
This will be backported to the 1.3.0 docs rendered on geomesa.org.
> GEOMESA-1650 Docs: fix broken links and other issues

- docs/user/accumulo/commandline_tools.rst
- docs/user/accumulo/jobs.rst
Make it clear that it (effectively) creates separate indexes for each
attribute listed, not a compound index of all attributes listed.
> GEOMESA-1662 Clarify description of add-attribute-index command

- geomesa-accumulo/geomesa-accumulo-tools/bin/setup-namespace.sh
* Fixed bug in setup-namespace that didn't terminate when provided with insufficient parameters.
> GEOMESA-1672 Bug in setup namespace

- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/accumulo/AccumuloJobUtils.scala
- geomesa-accumulo/geomesa-accumulo-spark/src/main/scala/org/locationtech/geomesa/spark/accumulo/AccumuloSpatialRDDProvider.scala
Extend ``AccumuloSpatialRDDProvider#rdd()`` to efficiently support
OR filters that produce query plans with multiple BatchScanPlan
components, by generating a separate RDD for each component and
returning their union.
> GEOMESA-1680 More efficiently handle OR filters in Accumulo Spark

- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/accumulo/AccumuloJobUtils.scala
- geomesa-accumulo/geomesa-accumulo-spark/src/main/scala/org/locationtech/geomesa/spark/accumulo/AccumuloSpatialRDDProvider.scala
* Don't do a union if there's only one component in the query plan.
* Remove unneccessary comparison and misleading comment.
> GEOMESA-1680 Fix Accumulo Spark query plans containing ORs redux

- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/EnvironmentCommand.scala
* Changes the 'env' command to output the list of SFTs and Converters by default.
> GEOMESA-1693 GeoMesa env command without arguments returns a poor error

- docs/user/accumulo/configuration.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/package.scala
- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/GeoMesaAccumuloInputFormat.scala
- geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/GeoMesaConfigurator.scala
- geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa-site.xml.template
... be configurable
* Added two new geomesa-site.xml config options:
** geomesa.mapreduce.split.count.absolute set the exact number of splits to use regardless of tserver count or accumulo-site.xml setting
** geomesa.mapreduce.split.count.tablet set the number of splits per tserver to use. Number of splits falls back to default accumulo splits computed by the job context.
> GEOMESA-731 GeoMesaInputFormat - Allow number of mappers per shard to

- build/cqs.tsv
- pom.xml
* Version 1.0.5 of the Scala parsers library addresses a memory leak.
> GEOMESA-1698 Address Scala parsers memory leak

- geomesa-jupyter/geomesa-jupyter-leaflet/src/main/scala/org/locationtech/geomesa/jupyter/Leaflet.scala
geomesa-jupyter-leaflet generates bad GeoJSON when attribute values
contain single quotes, which are not escaped by StringEscapeUtils.escapeJson,
causing Leaflet to fail to render.
> GEOMESA-1734 Fix bad GeoJSON when attributes contain single quotes

- geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndex.scala
- geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/GeoMesaIndexPropertyTransformer.scala
- geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/query/GeoJsonQuery.scala
- geomesa-geojson/geomesa-geojson-api/src/main/scala/org/locationtech/geomesa/geojson/query/PropertyTransformer.scala
- geomesa-geojson/geomesa-geojson-api/src/test/scala/org/locationtech/geomesa/geojson/GeoJsonGtIndexTest.scala
- geomesa-geojson/geomesa-geojson-api/src/test/scala/org/locationtech/geomesa/geojson/query/GeoJsonQueryTest.scala
* Updated GeoJsonQuery to allow parsing from json4s ast objects instead of just strings
* Adding support for DWithin queries through the geo json query parser
* GeoJsonQuery case classes no longer store a Seq[PathAttribute], but instead us a string. That string is verified to be a valid PathAttribute in the case that it starts with "$."
> GEOMESA-1824 GeoJsonQuery updates

- geomesa-hbase/geomesa-hbase-spark-runtime/pom.xml
> GEOMESA-1885 Exclude netty and json4s from hbase-spark-runtime.

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2WritableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3IndexV1.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3IndexV2.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3IndexV3.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3WritableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z2DensityIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z2Iterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3DensityIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/Z3IteratorTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ2Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z2Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/Z3Index.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/TrackLabelProcess.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/stats/BinnedArray.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/stats/Z3HistogramTest.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/uuid/Z3FeatureIdGeneratorTest.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/LegacyZ2SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/LegacyZ3SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/NormalizedDimension.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/Z2SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/Z3SFC.scala
- geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/NormalizedDimensionTest.scala
- geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/Z2Test.scala
- geomesa-z3/src/test/scala/org/locationtech/geomesa/curve/Z3Test.scala
* Old binning code moved to LegacyZ*Curve
* Existing code uses the legacy implementations for back-compatibility
* Precision is specified as bits (per dimension) instead of number of bins
> GEOMESA-1899 Fixing binning in z-curves, adding configurable precision

- geomesa-fs/geomesa-fs-spark-runtime/pom.xml
Allows the spark runtime to work in Zeppelin. Has also been tested with spark-submit to make sure it's not a breaking change.
> GEOMESA-1951 Exclude json4s in geomesa-fs-spark-runtime

- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/GmlExporter.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/export/GmlExportTest.scala
* This patch adds a quick namespace for GML exports.
NB: Temporarily disabling the Arrow Geometry Test.
> GEOMESA-1825 - GML Export test fails locally

- build/cqs.tsv
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/DictionaryBuildingWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/SimpleFeatureVector.scala
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/LineStringFloatVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/LineStringVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/MultiLineStringFloatVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/MultiLineStringVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/MultiPointFloatVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/MultiPointVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/MultiPolygonFloatVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/MultiPolygonVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/PointFloatVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/PointVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/PolygonFloatVector.java
- geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/PolygonVector.java
- pom.xml
* Using .setSafe in mutators instead of reAlloc (which doesn't work)
* Fixes offset alignment in arrow output files
> GEOMESA-1976 Upgrade to Arrow 0.6

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/tube/TubeBinTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/process/tube/TubeSelectProcessTest.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/tube/TubeBuilder.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/tube/TubeSelectProcess.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeometryUtils.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/GeometryUtilsTest.scala
This PR combines changes from the previous PR#1659 as well as the following updates:
GEOMESA-1986 TubeSelect Modified to Properly Handle IDL by segmenting lines crossing the IDL into two lines with proper times that stop at the IDL.
GEOMESA-1987 Fixed binning behavior to be more intuitive. If maxBins is 0 then don't bin the features, if 1 then make one bin, otherwise calculate number of bins based on numFeatures and maxBins
GEOMESA-1993 Added an interpolated gap fill which divides longer gaps into smaller space time interpolated segments based on the passed in buffer size.
> GEOMESA-1986,GEOMESA-1987,GEOMESA-1993 IDL Safe TubeSelect, Interpolated GapFill, Binning Fix 

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloQueryPlanner.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z2DensityIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3DensityIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/DensityIteratorTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDensityFilterTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/DensityScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryRunner.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/DensityProcess.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GridSnap.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/BucketIndex.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/GridSnapTest.scala
* Discarding grid snap points outside the image envelope, instead of moving to the nearest edge
* Using approximated raster instead of centroid for geometries with extents
> GEOMESA-2013 Buffering heatmap image generation to avoid edge effects

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloQueryPlanner.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z2DensityIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3DensityIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/DensityIteratorTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDensityFilterTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/DensityScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryRunner.scala
- geomesa-process/geomesa-process-vector/src/main/scala/org/locationtech/geomesa/process/analytic/DensityProcess.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GridSnap.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/BucketIndex.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/GridSnapTest.scala
* Discarding grid snap points outside the image envelope, instead of moving to the nearest edge
* Using approximated raster instead of centroid for geometries with extents
> 1.3 - GEOMESA-2013 Buffering heatmap image generation to avoid edge effects

- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/storage/converter/ConverterStorage.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/BucketVsLeafStorageTest.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
- geomesa-fs/geomesa-fs-storage-api/src/main/java/org/locationtech/geomesa/fs/storage/api/FileSystemStorage.java
- geomesa-fs/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/FileMetadata.scala
- geomesa-fs/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageUtils.scala
- geomesa-fs/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/StorageUtilsTest.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/SimpleFeatureReadSupport.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/CompactionTest.scala
- geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh
- geomesa-fs/geomesa-fs-tools/pom.xml
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/FsDataStoreCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/FsRunner.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/CompactCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/ParquetCompactionJob.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsIngestCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetConverterJob.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetJobUtils.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/SchemeOutputFormat.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/status/FSGetFilesCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/status/FsGetPartitionsCommand.scala
- geomesa-fs/geomesa-fs-tools/src/test/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetJobUtilsTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpecConfig.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
* Distributed and Local compactions for Parquet FSDS
* Option to compact all or compact specific partitions
* Get-partitions and get-files commands for FSDS tools
* Rolling metadata file backups
* Parquet filenames are now include random UUID instead of sequence numbers
* Parquet filenames include a type character (e.g. C = compaction, W = written, etc)
> GEOMESA-1910 Compactions for Parquet FSDS

- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/storage/converter/ConverterStorage.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/BucketVsLeafStorageTest.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
- geomesa-fs/geomesa-fs-storage-api/src/main/java/org/locationtech/geomesa/fs/storage/api/FileSystemStorage.java
- geomesa-fs/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/FileMetadata.scala
- geomesa-fs/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageUtils.scala
- geomesa-fs/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/StorageUtilsTest.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/SimpleFeatureReadSupport.scala
- geomesa-fs/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/CompactionTest.scala
- geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh
- geomesa-fs/geomesa-fs-tools/pom.xml
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/FsDataStoreCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/FsRunner.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/CompactCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/ParquetCompactionJob.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/FsIngestCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetConverterJob.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetJobUtils.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/ingest/SchemeOutputFormat.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/status/FSGetFilesCommand.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/status/FsGetPartitionsCommand.scala
- geomesa-fs/geomesa-fs-tools/src/test/scala/org/locationtech/geomesa/fs/tools/ingest/ParquetJobUtilsTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpecConfig.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
* Distributed and Local compactions for Parquet FSDS
* Option to compact all or compact specific partitions
* Get-partitions and get-files commands for FSDS tools
* Rolling metadata file backups
* Parquet filenames are now include random UUID instead of sequence numbers
* Parquet filenames include a type character (e.g. C = compaction, W = written, etc)
* Fixed quoted user-data serialization for Typesafe config
> 1.3 - GEOMESA-1910 Compactions for Parquet FSDS

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/Z2Index.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/Z3Index.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2IndexV3.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3IndexV4.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z2Iterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3Iterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/Z3IteratorTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterValues.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/HBaseZFilters.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ2Index.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ3Index.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/Z2Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/Z3Filter.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/filters/Z2FilterTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/filters/Z3FilterTest.scala
* Moves z filters configuration into index-api
* Includes a breaking change in the Accumulo z-iterator config
* Removes z-iterator from deprecated non-point z2/z3 indices
> GEOMESA-2058 Fixing serialization of HBase z-filter

- docs/user/kafka/usage.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/FeatureCacheCqEngine.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/FeatureCacheGuava.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCache.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheTest.scala
* Added 'kafka.cache.consistency' data store parameter to enable consistency checks
> GEOMESA-2033 Adding consistency checker for kafka feature cache

- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/data/AddIndexCommand.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/export/FeatureExporterTest.scala
- geomesa-arrow/geomesa-arrow-tools/src/main/scala/org/locationtech/geomesa/arrow/tools/export/ArrowExportCommand.scala
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaRunner.scala
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/export/KafkaExportCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/CommonParams.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ConvertCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/DeleteFeaturesCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ExportParams.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/ArrowExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/AvroExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/BinExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/DelimitedExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/FeatureExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/GeoJsonExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/GmlExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/NullExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/formats/ShapefileExporter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/stats/StatsBoundsCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/stats/StatsCountCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/stats/StatsHistogramCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/stats/StatsTopKCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/ExplainCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/utils/ParameterConverters.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/ConvertCommandTest.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/export/DelimitedExportImportTest.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/export/FeatureExporterTest.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/export/GmlExportTest.scala
* FeatureExporter split into 'start', 'encode', 'close' lifecyle
* Kafka will export current features in a batch, then listen for new features
> GEOMESA-2037 Kafka export command

- docs/user/datastores/index_config.rst
- docs/user/hbase/index.rst
- docs/user/hbase/index_config.rst
- docs/user/hbase/usage.rst
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
- geomesa-hbase/geomesa-hbase-tools/src/main/scala/org/locationtech/geomesa/hbase/tools/data/HBaseCreateSchemaCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/CreateSchemaCommand.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
* Users can enable compression either programmatically via
SimpleFeatureType userData or via the command line
> GEOMESA-2116 Allow users to configure compression on HBase tables

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseAttributeIndex.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseXZ2Index.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseXZ3Index.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ2Index.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseZ3Index.scala
* Enabled FAST_DIFF encoding on all but the id table
> GEOMESA-2117 Enable FAST_DIFF encoding on HBase tables

- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheTest.scala
* Causes frequent build failures in travis
> GEOMESA-2149 Disabling Kafka consistency test

- geomesa-spark/geomesa-spark-jts/src/main/scala/org/apache/spark/sql/jts/JTSTypes.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/SQLFunctionHelper.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/SQLGeometricCastFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/SQLGeometricConstructorFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/SQLGeometricOutputFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/SQLSpatialAccessorFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/SQLSpatialFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/SparkDefaultEncoders.scala
- geomesa-spark/geomesa-spark-jts/src/test/resources/log4j.xml
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/BlankDataFrame.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/SparkSQLGeometricCastTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/SparkSQLGeometricConstructorsTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/SparkSQLGeometricOutputsTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/SparkSQLGeometryAccessorsTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/SparkSQLSpatialRelationshipsTest.scala
Added testing parity between SQL and DataFrame tests of UDFs.
Also refactored mapping between string names and UDFs so we can
be more DRY and programmatically invoke DataFrame tests along with
SQL tests.
Signed-off-by: Simeon H.K. Fitch <fitch@astraea.io>
> GEOMESA-2173 Fix return type of TypedColumn spatial functions.

- geomesa-spark/geomesa-spark-jts/pom.xml
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/SpatialRelationFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/util/SQLFunctionHelper.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/TestEnvironment.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/GeometricCastFunctionsTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/GeometricConstructorFunctionsTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/SpatialRelationFunctionsTest.scala
Removes column functions where literal variant is non-sensical or of questionable usefulness. Added utility functions for generating geometry literals of specific types. Added tests to increase code coverage those remaining.
> GEOMESA-2190 Readdress handling of geometric literals in DataFrame DSL.

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTransformsTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/IndexPackageObjectTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryPlannerTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/XZ2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/AttributeIndexIteratorTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/IteratorTriggerTest.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/export/FeatureExporterTest.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpecParser.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
* Will return all properties for null array
* Will return no properties for empty array
* No longer always add default geometry as a return property
* Returns property in the order they are passed in
> GEOMESA-2193 Fixing behavior for Query.NO_PROPERTIES

- docs/user/datastores/runtime_config.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/id/RecordQueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryHints.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryProperties.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/StatsProperties.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreFactory.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/BaseFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/IdIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z2/XZ2IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z2/Z2IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3IndexKeySpace.scala
- geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa-site.xml.template
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/GeoMesaSystemProperties.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParam.scala
* Set 'geomesa.scan.block-full-table=true'
* Global behavior can be overridden for individual schemas with 'geomesa.scan.<type-name>.block-full-table'
> GEOMESA-2191 System property to prevent full-table scans

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/DictionaryBuildingWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeReader.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/vector/SimpleFeatureVectorTest.scala
* Previously the index vector held nulls and the dictionary vector never had nulls
* With this change, the dictionary vector holds nulls and the index vector will never have nulls
> GEOMESA-2195 Arrow - keep null dictionary values in the dictionary vector

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowBatchIteratorTest.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/io/DictionaryBuildingWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeReader.scala
- geomesa-arrow/geomesa-arrow-gt/src/main/scala/org/locationtech/geomesa/arrow/vector/ArrowAttributeWriter.scala
- geomesa-arrow/geomesa-arrow-gt/src/test/scala/org/locationtech/geomesa/arrow/vector/SimpleFeatureVectorTest.scala
* Previously the index vector held nulls and the dictionary vector never had nulls
* With this change, the dictionary vector holds nulls and the index vector will never have nulls
> 1.3 - GEOMESA-2195 Arrow - keep null dictionary values in the dictionary vector

- docs/user/kafka/usage.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerVersions.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/ThreadedConsumer.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaCacheLoader.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala
* If 'kafka.consumer.from-beginning', features will not be available
to query until consumers have caught up, although listeners will be
called as normal
> GEOMESA-2206 Kafka - don't index features during initial bulk load

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreTransformsTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/IndexPackageObjectTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryPlannerTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/XZ2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z2IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/Z3IdxStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/AttributeIndexIteratorTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/IteratorTriggerTest.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/export/FeatureExporterTest.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpecParser.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
* Will return all properties for null array
* Will return no properties for empty array
* No longer always add default geometry as a return property
* Returns property in the order they are passed in
> 1.3 - GEOMESA-2193 Fixing behavior for Query.NO_PROPERTIES

- build/cqs.tsv
- docs/user/kafka/install.rst
- geomesa-kafka/geomesa-kafka-datastore/pom.xml
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/EmbeddedKafka.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/ThreadedConsumer.scala
- geomesa-lambda/geomesa-lambda-datastore/pom.xml
- geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/EmbeddedKafka.scala
- geomesa-lambda/pom.xml
- pom.xml
* 0.10 and 0.9 are still supported
> GEOMESA-2224 Updating default kafka version to 1.0.1

- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheTest.scala
- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/utils/CQEngineQueryVisitor.scala
- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/utils/QueryBuilder.scala
* Geotools supports these queries against strings in general so users
have come to expect them
* Added support for the queries to cqengine
> GEOMESA-2234 Support gt,gteq,lt,lteq,between queries on strings in CQEngine

- .travis.yml
- .travisbuild.sh
- build/mvn
* Two phase build due to memory limitations - build first with zinc, then test without
* build/mvn wrapper now shuts down zinc after running
> GEOMESA-2247 Using zinc for travis build

- docs/user/datastores/runtime_config.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/GeoMesaCoprocessor.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseQueryPlan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureReader.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/utils/ThreadManagement.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/collection/CloseableIterator.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/collection/CloseableIteratorTest.scala
* ThreadManagement now interrupts the query thread before closing the result
> GEOMESA-2271 HBase - support query timeout for coprocessor calls

- .travisbuild.sh
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
- geomesa-spark/geomesa-spark-sql/src/test/scala/org/locationtech/geomesa/spark/SparkSQLDataTest.scala
* Supports date queries without a cast to timestamp
* e.g "dtg between '2016-01-01T00:00:00Z' and '2016-01-01T01:00:00Z'"
> GEOMESA-2281 SparkSQL - handling push-down casts

- docs/user/accumulo/install.rst
- docs/user/cli/filesystems.rst
- docs/user/convert/extending.rst
- docs/user/convert/function_overview.rst
- docs/user/convert/premade/osm-gpx.rst
- docs/user/filesystem/architecture.rst
- docs/user/hbase/install.rst
- geomesa-tools/conf/sfts/osm-gpx/README.md
- geomesa-tools/conf/sfts/osm-gpx/reference.conf
* Updated osm-gpx converter to work with Saxon
* Fixing references to 'mapreduce' as 'map-reduce'
* Adding note on support for ORC in FSDS
> GEOMESA-1730,GEOMESA-1479 GPX tutorial shouldn't depend on external code, docs fixes

- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/utils/CQEngineQueryVisitor.scala
- geomesa-memory/geomesa-cqengine/src/test/scala/org/locationtech/geomesa/memory/cqengine/utils/GeoCQEngineTest.scala
- geomesa-memory/geomesa-cqengine/src/test/scala/org/locationtech/geomesa/memory/cqengine/utils/SampleFeatures.scala
* Handles the cases around (in)equalities.
> GEOMESA-2291 CQEngine - handle filter functions, etc

- geomesa-spark/geomesa_pyspark/pom.xml
- geomesa-spark/geomesa_pyspark/src/test/python/test_types.py
... also cleaned up some test method naming
> GEOMESA-2331 allow geomesa_pyspark unit tests to be skipped

- geomesa-bigtable/geomesa-bigtable-tools/conf/hbase-site.xml
This fix is for the sample `hbase-site.xml` in the bigtable binaries. Since `pom.xml` and `hbase-site.xml` are looking for different versions of `bigtable.hbase`.
> Fix incorrect version in hbase-site.xml

- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/FileSystemDataStoreTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-api/src/main/java/org/locationtech/geomesa/fs/storage/api/FileMetadata.java
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/pom.xml
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/FileMetadata.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/MetadataObservingFileSystemWriter.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-convert/src/main/scala/org/locationtech/geomesa/fs/storage/converter/ConverterStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemWriter.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/test/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemWriterTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
* Computes bounds and feature count during ingest.
* NB: There is no concurrency checking.  Multiple writers may clobber the metadata.
> GEOMESA-2368 Compute bounds while ingesting data into the FSDS

- docs/user/datastores/index_config.rst
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/SerializationOption.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/DimensionalBounds.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/TwkbSerialization.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/VarIntEncoding.scala
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/serialization/WkbSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/impl/KryoFeatureSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/serialization/KryoGeometrySerialization.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoFeatureSerializerTest.scala
- geomesa-features/geomesa-feature-kryo/src/test/scala/org/locationtech/geomesa/features/kryo/KryoGeometrySerializerTest.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/schema/KuduColumnAdapter.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geometry/GeometryPrecision.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
* TWKB serialization can be enabled on geometry attributes (opt-in)
* Serialization precision can be specified with the per-attribute user data 'precision' flag
* Both TWKB and WKB serialization are supported, even within a single schema
> GEOMESA-2314 TWKB geometry serialization

- docs/user/hbase/configuration.rst
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBasePlatform.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/package.scala
- geomesa-utils/src/main/resources/org/locationtech/geomesa/geomesa-site.xml.template
* Ranges are sorted, so by default all our threads operate on ranges
close to each other, likely on the same region server
> GEOMESA-2378 HBase - shuffle range groups to improve scan parallelism

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
GeoMesa Datastore should use Lenient SymVer so users that are not familiar with symver encounter unexpected version errors less often.
> GEOMESA-2380 GeoMesa Datastore should use Lenient SymVer

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/OrHashEquality.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/OrSequentialEquality.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
1. Add an OR query to a Kafka unit test that.
2. Children of OrHashEquality and OrSequentialEquality filters should not be
lazy. The FastFilterFactory.sfts must be available when children are
evaluated.
Signed-off-by: Kevin Hobbs <khobbs@ccri.com>
> GEOMESA-2381 Test and fix OR

- docs/user/datastores/runtime_config.rst
- docs/user/upgrade.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseTestRunnerTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/SchemaProperties.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/GeoMesaSystemProperties.scala
* Especially in large HBase clusters
> GEOMESA-2394 Disabling auto distributed runtime check, as it can be slow

- geomesa-convert/geomesa-convert-all/src/test/scala/org/locationtech/geomesa/convert/URLConfigProviderTest.scala
- geomesa-fs/geomesa-fs-spark-runtime/pom.xml
- geomesa-fs/geomesa-fs-spark-runtime/src/test/scala/org/locationtech/geomesa/fs/spark/FSSparkProviderTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/jobs/OrcSimpleFeatureInputFormat.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/utils/OrcInputFormatReader.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureSpecParser.scala
* Creates Spark+FSDS test framework and applies it to ORC format.
* Handles count(*) projection case.
* Fixes various ORC MR format reading bugs.
* Allows SimpleFeatureSpecs to have -'s in userData (without attributes).
> GEOMESA-2404 Fixes bugs with FSDS Orc Mapreduce Formats

- geomesa-accumulo/geomesa-accumulo-spark-runtime/pom.xml
- geomesa-bigtable/geomesa-bigtable-spark-runtime/pom.xml
- geomesa-fs/geomesa-fs-spark-runtime/pom.xml
- geomesa-hbase/geomesa-hbase-spark-runtime/pom.xml
- geomesa-kudu/geomesa-kudu-spark-runtime/pom.xml
* Removes io.netty from all 5 Spark runtimes.
> GEOMESA-2400 Remove netty from spark-runtime jars

- geomesa-convert/geomesa-convert-all/src/test/scala/org/locationtech/geomesa/convert/testing/CompositeTextConverterTest.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/composite/CompositeConverter.scala
> GEOMESA-2397 CompositeConverter - allow for calling `next` without `hasNext`

- docs/user/spark/sparksql_functions.rst
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/GeometricCastFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/GeometricCastFunctionsTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/udf/GeometricConstructorFunctionsTest.scala
- geomesa-spark/geomesa-spark-jts/src/test/scala/org/locationtech/geomesa/spark/jts/util/util.scala
This allows Geometry subclasses to be treated as Geometries in Dataset domain-specific objects.
> GEOMESA-2454 Introduce st_castToGeometry

- CONTRIBUTING.md
- README.md
- build/README.md
- geomesa-accumulo/geomesa-accumulo-tools/pom.xml
- geomesa-fs/geomesa-fs-tools/pom.xml
- geomesa-lambda/geomesa-lambda-tools/pom.xml
- pom.xml
See the messages on the individual commits.  I'd recommend leaving them separate because they each address slightly different concerns and there's a chance you might want to revert one or the other in the future -- but I'm happy to squash them if you prefer.
The main way I tested these changes was to compare the output of a full "build/mvn clean install" before and after each change.  The only non-trivial differences in the output were in some tests, e.g. org.locationtech.geomesa.hbase.nativeapi.GeoMesaIndexTest and GeoMesaQueryTest.  There were differences in the kinds of errors that these tests report, e.g. "caught end of stream exception" vs "Connection refused" -- but these differences seemed random, not related to the changes I was making.
I did all this work on a Mac with a Oracle …
> GEOMESA-2478 Update Maven plugins to current versions

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/KryoLazyDensityIteratorTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryRunner.scala
* Only use the density envelope to trim existing spatial filters
> GEOMESA-886 Fix spatial filter for density queries

- docs/user/datastores/runtime_config.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/id/RecordQueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z2/Z2QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/legacy/z3/Z3QueryableIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/index/CassandraFeatureIndex.scala
- geomesa-hbase/geomesa-hbase-datastore/src/test/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryHints.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryProperties.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/BaseFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryRunner.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/index/KuduFeatureIndex.scala
* `geomesa.scan.block-full-table.threshold` controls the threshold
(default 1000)
> GEOMESA-2503 Don't block full table scans when max-features is specified

- build/cqs.tsv
- docs/user/datastores/runtime_config.rst
- geomesa-accumulo/geomesa-accumulo-compute/pom.xml
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/util/ZookeeperLocking.scala
- geomesa-hbase/geomesa-hbase-datastore/pom.xml
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/package.scala
- geomesa-zk-utils/src/main/scala/org/locationtech/geomesa/utils/zk/ZookeeperLocking.scala
- pom.xml
* Use `geomesa.distributed.lock.timeout` as a duration
* Add zookeeper distributed locking to HBase data store
* Standardize version of curator to 4.0.1
> GEOMESA-2486 Add system property for distributed lock timeout

- docs/user/kafka/index_config.rst
- docs/user/kafka/usage.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaDataStoreCommand.scala
- geomesa-kafka/geomesa-kafka-tools/src/main/scala/org/locationtech/geomesa/kafka/tools/KafkaParams.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/KafkaConsumerVersions.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/AbstractIngest.scala
* Use `kafka.consumer.read-back` to specify how far back a consumer will start reading
* Kafka versions prior to 0.10.1 do not support time-based lookups, so the entire topic will be read
* `kafka.consumer.from-beginning` is deprecated, use `Inf` for the read-back value instead
> GEOMESA-2473 Kafka - support initial load from a given time offset

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreQueryTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureSource.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
simple fix, not sure on use of mutation on Query instance, but consistent w/ other mutations in rest of implementation
> GEOMESA-2521 Handle null TypeName in Query from GS querylayer extension

- geomesa-tools/bin/manage-geoserver-plugins.sh
Helps with using the script within other scripts to ensure the same
ordering with each run of the script
> GEOMESA-2527 Sort `manage-geoserver-plugins.sh` options

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryPlannerTest.scala
- geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/AvroSimpleFeatureFactoryTest.scala
- geomesa-features/geomesa-feature-avro/src/test/scala/org/locationtech/geomesa/features/avro/AvroSimpleFeatureTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/expression/FastTemporalOperator.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/factory/FastFilterFactory.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/converters/FastConverter.scala
* FastDuring, FastAfter and FastBefore
* GeoTools temporal filters try to convert every value into
a Period, which fails every time for our common use cases
> GEOMESA-2518 Add fast temporal filter implementations

- docs/user/filesystem/sql.rst
- docs/user/spark/providers.rst
- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/FileSystemFeatureStore.scala
- geomesa-fs/geomesa-fs-spark-runtime/src/test/scala/org/locationtech/geomesa/fs/spark/FSSparkProviderTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-api/src/main/java/org/locationtech/geomesa/fs/storage/api/StorageMetadata.java
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/MetadataFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/StorageMetadata.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/compact/CompactCommand.scala
- geomesa-tools/conf/log4j.properties
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/fs/LocalDelegate.scala
- pom.xml
* Using FileContext.utils() is orders of magnitudes slower with large
numbers of files
* Fix USE_PROVIDED_FID behavior for FSDS FeatureStore
* Add docs on setting user.timezone for spark sql
> GEOMESA-2524 Hand-walk FSDS metadata directory

- geomesa-tools/conf/sfts/osm/reference.conf
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypesTest.scala
* 'records' is no longer supported, replaced by 'id'
* Fix osm provided converter
> GEOMESA-2533 Remove remaining references to 'records' index

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/index/HBaseFeatureIndex.scala
* Set column descriptors to bloom type of none.
> GEOMESA-2536 HBase - Disable bloom filters by default

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryFilterSplitterTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/visitor/FilterExtractingVisitor.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/Z3Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/AttributeFilterStrategy.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/SpatioTemporalFilterStrategy.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/FeatureStateFactory.scala
* Update Z3/XZ3IndexKeySpace to return bin-only ranges for unbounded dates
> GEOMESA-2402 Use one-sided date filters in z-range planning

- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
* Invalid metadata will result in an exception with the
message 'Invalid index metadata'
> GEOMESA-2543 Error-handling to validate future schema metadata

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/function/ProxyIdFunction.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/function/ProxyIdFunctionTest.scala
* Allows it to be visited by SimplifyingFilterVisitor without
being replaced or throwing exceptions
> GEOMESA-2557 ProxyId function extends VolatileFunction

- docs/user/kafka/usage.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
* Use `kafka.producer.clear` set to `true`
> GEOMESA-2542 Kafka - provide option to clear topic on startup

- geomesa-accumulo/geomesa-accumulo-tools/src/main/resources/org/locationtech/geomesa/accumulo/tools/ingest-libjars.list
- geomesa-bigtable/geomesa-bigtable-tools/src/main/resources/org/locationtech/geomesa/bigtable/tools/ingest-libjars.list
- geomesa-fs/geomesa-fs-tools/src/main/resources/org/locationtech/geomesa/fs/tools/ingest-libjars.list
- geomesa-hbase/geomesa-hbase-tools/src/main/resources/org/locationtech/geomesa/hbase/tools/ingest-libjars.list
- geomesa-kafka/geomesa-kafka-tools/src/main/resources/org/locationtech/geomesa/kafka/tools/ingest-libjars.list
- geomesa-kudu/geomesa-kudu-tools/src/main/resources/org/locationtech/geomesa/kudu/tools/ingest-libjars.list
Per https://geomesa.atlassian.net/browse/GEOMESA-2573
Added 'core' to all ingest-libjars.list occurrences. First commit incorrectly added hsqldb.
>  GEOMESA-2573 Add ejml core to ingest libjars

- docs/user/merged_view.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/index/view/MergedDataStoreViewTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedDataStoreView.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedDataStoreViewFactory.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedFeatureSourceView.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedQueryRunner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/package.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParam.scala
* Use `geomesa.merged.store.filter` to apply a filter to each store
> GEOMESA-2493 Configurable query filtering for merged data store view

- docs/user/convert/parsing_and_validation.rst
- geomesa-convert/geomesa-convert-avro/src/main/scala/org/locationtech/geomesa/convert/avro/AvroConverterFactory.scala
- geomesa-convert/geomesa-convert-avro/src/test/scala/org/locationtech/geomesa/convert/avro/AvroConverterTest.scala
- geomesa-convert/geomesa-convert-common/src/main/resources/base-converter-defaults.conf
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverter.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/AbstractConverterFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/package.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert/common/EnrichmentCacheTest.scala
- geomesa-convert/geomesa-convert-json/src/main/scala/org/locationtech/geomesa/convert/json/JsonConverterFactory.scala
- geomesa-convert/geomesa-convert-shp/src/main/scala/org/locationtech/geomesa/convert/shp/ShapefileConverterFactory.scala
- geomesa-convert/geomesa-convert-shp/src/test/scala/org/locationtech/geomesa/convert/shp/ShapefileConverterTest.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverter.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterFactory.scala
- geomesa-convert/geomesa-convert-xml/src/main/resources/xml-converter-defaults.conf
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverter.scala
- geomesa-convert/geomesa-convert-xml/src/main/scala/org/locationtech/geomesa/convert/xml/XmlConverterFactory.scala
- geomesa-fs/geomesa-fs-datastore/src/test/resources/reference.conf
- geomesa-fs/geomesa-fs-datastore/src/test/scala/org/locationtech/geomesa/fs/converter/ConverterDataStoreTest.scala
* Logging configured at 'info' level will just show the field
* Logging configured at the 'debug' level will show the field,
the inputs, and the stack trace of the underlying exception
> GEOMESA-2560 Remove verbose flag from converters

- docs/user/kafka/usage.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
* Use `"kafka.consumer.start-on-demand" -> false`
> GEOMESA-2574 Start Kafka load on datastore creation

- docs/user/upgrade.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloIndexAdapter.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraIndexAdapter.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/test/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreTest.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/IndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/data/KuduIndexAdapter.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisIndexAdapter.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/ManagePartitionsCommand.scala
* Cassandra does not support names longer than 48 chars
> GEOMESA-2589 Cassandra - limit table names to 48 characters

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/partition/TablePartition.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/partition/TimePartition.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/conf/partition/TablePartitionTest.scala
* TablePartition.partitions changed to return an Option[Seq[String]] to
indicate disjoint filters
> GEOMESA-2628 Table partitioning indicates if no tables can match a filter

- pom.xml
* Fix intermittent build failures due to version range in geotools poms
> GEOMESA-2652 Set explicit EMF dependency version

- docs/user/cli/ingest.rst
- docs/user/datastores/runtime_config.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/stats/AccumuloGeoMesaStats.scala
- geomesa-accumulo/geomesa-accumulo-tools/src/main/scala/org/locationtech/geomesa/accumulo/tools/ingest/AccumuloIngestCommand.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/CachedLazyMetadata.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/GeoMesaMetadata.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/metadata/NoOpMetadata.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/stats/MetadataBackedStats.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/InMemoryMetadata.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentMetadata.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/LocalConverterIngest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/CloseablePool.scala
* Flush each writer every 20k features
* Configurable via `geomesa.ingest.local.batch.size`
* New scala-friendly object pool impl:
`org.locationtech.geomesa.utils.io.CloseablePool`
> GEOMESA-2656 Cache writers during local ingest

- docs/user/stream.rst
* Improve geomesa-stream docs readability for newer users
* Rename "Usage" section to "Using GeoMesa Stream" and add subsections for clarity
Signed-off-by: Matthew Foreman <mforeman@ccri.com>
> GEOMESA-2669 Docs - improve Stream DataStore documentation

- docs/user/filesystem/install.rst
- geomesa-fs/geomesa-fs-tools/bin/install-hadoop.sh
- geomesa-fs/geomesa-fs-tools/bin/install-s3.sh
Separated out aws s3 jars into its own install script.
Updated documentation to more closely match the jars required for
operation.
Signed-off-by: Michael Linsinbigler <malinsinbigler@gmail.com>
> GEOMESA-2682 Updated fsds documentation and install scripts

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseBackedMetadata.scala
> GEOMESA-2693 HBase - GeoMesa metadata table should be held in memory

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/DensityIterator.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/coprocessor/aggregators/HBaseDensityAggregator.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/DensityScan.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/LocalQueryRunner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryRunner.scala
- geomesa-kudu/geomesa-kudu-datastore/src/main/scala/org/locationtech/geomesa/kudu/result/DensityAdapter.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeometryUtils.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GridSnap.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/RenderingGrid.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/geotools/GeometryUtilsTest.scala
* Geometries are translated to overlap the rendering envelope
* Filters extracted from the envelope are split for AntiMeridian handling
* Translation logic consolidated in org.locationtech.geomesa.utils.geotools.RenderingGrid
> GEOMESA-2688 Fix heatmap rendering outside [-180,180] longitude

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/AttributeIndexStrategyTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/AttributeIndexFilteringIteratorTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/attribute/AttributeIndexKeySpace.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
* Handle '_' and '%' in attribute indices
* Handle non-trailing wildcards
> GEOMESA-2624 Improve wildcard handling

- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/data/ManagePartitionsCommand.scala
Make the mapping of indexes to user provided tables strict by
1. Reversing the direction of the match from table -> index to
index -> table.
2. Matching the index with the longest attribute string first.
3. Match only if the table has not already been matched.
4. Match only if all of the index name, version and attributes
are included in the table name.
Signed-off-by: Kevin Hobbs <khobbs@ccri.com>
> GEOMESA-2708 Strict index to table for adopt

- docs/tutorials/geomesa-quickstart-cassandra.rst
* Updates the instructions for running bin/geomesa-cassandra export
to be aligned with the 2.11-2.4.0-SNAPSHOT version.
Signed-off-by: Ray Zeng <zeng.j.ray@gmail.com>
> GEOMESA-2709 Update Cassandra Quickstart Tutorials

- docs/user/convert/function_overview.rst
- docs/user/convert/function_usage.rst
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/DateFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert2/transforms/MiscFunctionFactory.scala
- geomesa-convert/geomesa-convert-common/src/test/scala/org/locationtech/geomesa/convert2/transforms/ExpressionTest.scala
* Date parsing methods pass through nulls instead of throwing exceptions
* Fix the anti-pattern of `try(date($0), null)`, which is expensive
* `require` function added to preserve old behavior if desired
> GEOMESA-2707 Converters - check for nulls in date parsing methods

- build/cqs.tsv
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/S2HBaseFilter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/filters/S3HBaseFilter.scala
- geomesa-index-api/pom.xml
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryProperties.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/S2Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/S3Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/DefaultFeatureIndexFactory.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s2/S2Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s2/S2IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s2/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s3/S3Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s3/S3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s3/package.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/ByteArrays.scala
- geomesa-z3/pom.xml
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/S2SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/S3SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/SpaceFillingCurve.scala
The implementation of S2 is completely implemented by Google's algorithm; s3 I use epoch+S2+Time to encode, so although the 3D is not uniformly coded, the performance of the actual test is very good. We also analyzed the reasons, mainly in the 64-bit encoding. If the accuracy of each dimension is 3, the accuracy of each dimension will be 21, and the number of results of the scan will be more. More than the final result, through the above S3 encoding, we have tested this scan+mutiRowFilter to extract data from HBase with a higher accuracy than Z3, of course not absolute, most of the scenarios we tested.
In addition, very excited, this is the first time I submitted a PR to the open source community. If there is something wrong, please correct me.
> add the application of Google S2 algorithm in point data

- geomesa-jupyter/geomesa-jupyter-leaflet/src/main/scala/org/locationtech/geomesa/jupyter/Leaflet.scala
- geomesa-jupyter/geomesa-jupyter-leaflet/src/test/scala/org/locationtech/geomesa/jupyter/LeafletTest.scala
API change so that path is a Scala Option
If specified, uses that path
If not specified, uses CDN links so works out of the box
Renamed countries.geo.json
to
countries.geo.js
to match MIME type of actual content
Safe handling of absence of countries.geo.js(on)
Basic unit tests for CDN
Tested in Jupyter 5.7.8 w Toree 0.3.0
> GEOMESA-2731 geomesa-jupyter-leaflet assumes availability of Leaflet etc

- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
* Non-system level users can't view their own labels, so the check always fails
> GEOMESA-2738 HBase - change authorization mismatch to warning

- docs/user/appendix/memory.rst
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/AbstractGeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/BucketGeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/GeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/GeoIndexType.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/QuadTreeGeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/STRtreeGeoIndex.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/param/BucketIndexParam.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/param/GeoIndexParams.java
- geomesa-memory/geomesa-cqengine/src/main/java/org/locationtech/geomesa/memory/cqengine/index/param/STRtreeIndexParam.java
- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/GeoCQEngine.scala
- geomesa-memory/geomesa-cqengine/src/main/scala/org/locationtech/geomesa/memory/cqengine/GeoIndexFactory.scala
- geomesa-memory/geomesa-cqengine/src/test/scala/org/locationtech/geomesa/memory/cqengine/utils/CQIndexingOptionsTest.scala
- geomesa-memory/geomesa-cqengine/src/test/scala/org/locationtech/geomesa/memory/cqengine/utils/GeoCQEngineIndexChoiseTest.scala
- geomesa-memory/geomesa-cqengine/src/test/scala/org/locationtech/geomesa/memory/cqengine/utils/SampleFeatures.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/WrappedSTRtree.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/index/WrapperIndex.scala
- pom.xml
I provided the new features just via API, is not possible to configure them in the sft schema. This  avoids using them as indexes for the GeoCQEngineDataStore
Signed-off-by: Rodolfo Totaro <rodolfo_totaro@yahoo.it>
> GEOMESA-2737 GeoCQEngine STRtree and Quadtree indexes support

- docs/user/filesystem/index_config.rst
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/java/org/locationtech/geomesa/fs/storage/common/interop/ConfigurationUtils.java
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/AbstractFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/observer/FileSystemObserver.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/observer/FileSystemObserverFactory.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/package.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/ConfigurationTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-convert/src/main/scala/org/locationtech/geomesa/fs/storage/converter/ConverterStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/main/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemWriter.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/test/scala/org/locationtech/geomesa/fs/storage/orc/OrcFileSystemStorageTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-orc/src/test/scala/org/locationtech/geomesa/fs/storage/orc/TestObserverFactory.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/ParquetFileSystemStorage.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/ParquetStorageTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/TestObserverFactory.scala
* SimpleFeatureTypes can define file writer callbacks
* User data key is `geomesa.fs.observers`
* Trait is `org.locationtech.geomesa.fs.storage.common.observer.FileSystemObserverFactory`
> GEOMESA-2743 FSDS - Custom file callbacks

- docs/user/spark/sparksql_functions.rst
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/DataFrameFunctions.scala
- geomesa-spark/geomesa-spark-jts/src/main/scala/org/locationtech/geomesa/spark/jts/udf/SpatialRelationFunctions.scala
We've have many methods for geometry in spark.  We can judge if geometies intersects or disjoint. However, getting the intersection or difference part is unsupported in spark now. It is expected to add support for getting intersection and difference geometries are often required.
I add support for getting intersection and difference of geometries in spark. The intersection and difference can be accessed using SQL queries of spark SQL, as follows.
> GEOMESA-2754 Support intersection and difference of geometries in spark 

- geomesa-fs/geomesa-fs-datastore/src/main/scala/org/locationtech/geomesa/fs/data/FileSystemDataStoreFactory.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-security/src/main/scala/org/locationtech/geomesa/security/package.scala
* geomesa.security.auths
* geomesa.security.visibilities
* hbase.config.xml
* fs.config.xml
> GEOMESA-2758 Additional NiFi expression language support

- docs/user/datastores/runtime_config.rst
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/ScalaSimpleFeatureFactory.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/impl/KryoFeatureDeserialization.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/impl/KryoFeatureDeserializationV2.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/impl/KryoFeatureSerialization.scala
- geomesa-features/geomesa-feature-kryo/src/main/scala/org/locationtech/geomesa/features/kryo/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/IteratorCache.scala
- geomesa-jobs/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/SimpleFeatureSerialization.scala
- geomesa-utils/pom.xml
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/cache/ThreadLocalCache.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/cache/ThreadLocalCacheTest.scala
* `geomesa.filter.remote.cache.expiry` for setting filter expiration
* `geomesa.serializer.cache.expiry` for setting serializer expiration
> GEOMESA-2769 Add expiry for cached filters in distributed runtimes

- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStore.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/Runner.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/status/HelpCommand.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/ObjectType.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/sft/SimpleFeatureSpec.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/sft/SimpleFeatureSpecParser.scala
* `GeoMesaDataStore.checkSchemaCompatibility` can be used to create
and update schemas with complicated checks
> GEOMESA-2914 Provide simplified schema management

- geomesa-tools/conf-filtered/geomesa-env.sh
bin/geomesa-hbase: line 24: geomesa_configure: command not found
/opt/geomesa/conf/geomesa-env.sh: line 390: ~/.bash_completion: No such file or directory
> GEOMESA-2922 Fix bugs in geomesa-env script

- docs/user/datastores/query_config.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloIndexAdapter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/FilterTransformIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/Z3Iterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/FilterTransformIteratorTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/Z3IteratorTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/QueryHints.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/conf/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
* Use QueryHints.FILTER_COMPAT = "1.3"
* Supports basic non-strict date time queries against z3 index
* Supports basic queries against xz3 index
* Does not support transforms or advanced queries
> GEOMESA-2977 Option to query z-filters in 1.3 Accumulo installs

- docs/user/datastores/index_basics.rst
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/DefaultFeatureIndexFactory.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3Index.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/legacy/XZ3IndexV1.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/legacy/XZ3IndexV2.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/legacy/Z3IndexV5.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/legacy/Z3IndexV6.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/XZ3IndexTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/Z3IndexTest.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/BinnedTime.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/LegacyYearXZ3SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/LegacyYearZ3SFC.scala
- geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZ3SFC.scala
* Does not fix z3 index versions < 5 (created with GeoMesa versions < 2.0.0)
> GEOMESA-2973 Fix indexing for yearly z3 epoch

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/MetadataMigration.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
> GEOMESA-2983 Fix Kafka metadata migration from 1.x for reserved words

- docs/user/datastores/runtime_config.rst
- docs/user/upgrade.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/index/AccumuloJoinIndex.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreStatsTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryFilterSplitterTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/QueryStrategyDeciderTest.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/iterators/ArrowDeltaIteratorTest.scala
- geomesa-accumulo/geomesa-accumulo-jobs/src/main/scala/org/locationtech/geomesa/jobs/accumulo/AccumuloJobUtils.scala
- geomesa-hbase/geomesa-hbase-rpc/src/main/scala/org/locationtech/geomesa/hbase/rpc/filter/CqlTransformFilter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/package.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/id/IdIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/FilterSplitter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/StrategyDecider.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/AttributeFilterStrategy.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/IdFilterStrategy.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/SpatialFilterStrategy.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/strategies/SpatioTemporalFilterStrategy.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreTest.scala
* Separate filter plan cost into a base cost and a multiplier
** Multiplier reflects the priority/ranking of the filter plan
* Check cross-attribute OR filters for simple filter plans
* Only return best "tier" of filter plans from FilterSplitter
* Add `geomesa.query.processing.or.threshold` to enable expensive
OR processing
> GEOMESA-3027 Better handling of complex OR queries

- docs/user/datastores/index_config.rst
- docs/user/datastores/security.rst
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStore.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloIndexAdapter.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/VisibilityIterator.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/VisibilitiesTest.scala
- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/IndexAdapter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaFeatureWriter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaFeatureWriter.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaFeatureWriter.scala
- geomesa-redis/geomesa-redis-datastore/src/main/scala/org/locationtech/geomesa/redis/data/index/RedisIndexAdapter.scala
- geomesa-security/src/main/java/org/locationtech/geomesa/security/VisibilityChecker.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/Conversions.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SimpleFeatureTypes.scala
* New index configuration `geomesa.vis.required`
* Writes are blocked in the API, so not 100% foolproof
* Accumulo will also apply the ReqVisFilter on all tables
> GEOMESA-2991 Configuration to require visibilities on write

- README.md
- build/README.md
- geomesa-features/geomesa-feature-common/src/main/java/org/locationtech/geomesa/features/interop/SerializationOptions.java
- geomesa-features/geomesa-feature-common/src/main/scala/org/locationtech/geomesa/features/SerializationOption.scala
* Java classes for SerializationOptions changed from SerializationOption$.Value to Enumeration.Value.
* Optimizes imports.
* Points to build artifacts with the tag structure.
> Address issues found during GeoMesa 3.2.0 release

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/KryoVisibilityRowEncoder.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreNullAttributeVisibilityTest.scala
Correctly populate null bitset when merging serialised features according to visibilities
Tested via new unit test, as well as manually on an Accumulo 1.7 cluster
Signed-off-by: James Srinivasan <jsrinivasan@dstl.gov.uk>
> GEOMESA-3091 Attribute level visibilities error with null attribute values

- geomesa-tools/bin/geomesa-tools
* Fix nailgun start script remaining open in the background, which
prevents shell from exiting when run from a script
> GEOMESA-3093 Fix nailgun script exit after startup

- geomesa-cassandra/geomesa-cassandra-datastore/src/main/scala/org/locationtech/geomesa/cassandra/data/CassandraDataStoreFactory.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/utils/PartitionSchemeArgResolver.scala
- geomesa-fs/geomesa-fs-tools/src/main/scala/org/locationtech/geomesa/fs/tools/data/FsCreateSchemaCommand.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStore.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/GeoMesaDataStoreFactory.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStoreFactory.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStoreParams.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStoreTest.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/FeatureUtils.scala
* Separate Lambda data store config parsing from Accumulo
* Move PartitionSchemeArgResolver to data store module
* Handle check for FeatureIdImpl to avoid proxy errors in NiFi
> GEOMESA-3092 Support Lambda NiFi processor

- build/copyright/ccri-dstl-mitre.txt
- build/copyright/ccri-mitre.txt
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloClientConfig.scala
- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/data/AccumuloDataStoreFactory.scala
- geomesa-convert/geomesa-convert-avro-schema-registry/src/test/scala/org/locationtech/geomesa/convert/avro/registry/AvroSchemaRegistryConverterTest.scala
- pom.xml
Despite the best efforts of GEOMESA-2800 only a handful of Accumulo client settings were actually loaded at runtime. This meant that Accumulo client settings like TLS or instance.id were ignored. Worse, there was no way for a user to specify them because TLS settings are not available as command line options for tools like `geomesa-accumulo ingest`.
Other related changes (originally separate commits, but squashed together to meet coding standards):
* New license headers for MITRE 2021 contributions. This is fairly brittle, but AFAICT this is a limitation of the license-maven-plugin.
* AvroSchemaRegistryConverterTest now uses a random Jetty port, not 8089. (Necessary for the unit tests to complete successfully when port 8089 is in use by another process.)
* Error message in accumulo config …
> GEOMESA-3162: Geomesa client configuration file properly loaded.

- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/geotools/MetadataBackedDataStore.scala
The dtg information is set during the verification. If  not verified, the default dtg information is changed and the update fails.
> GEOMESA-3177 Schema update - validate new schema before compare old and new

- docs/user/postgis/index_config.rst
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreFactory.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/functions/LogCleaner.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/package.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/AnalyzePartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/DropAgedOffPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/MergeWriteAheadPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionMaintenance.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionSort.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/RollWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/AnalyzeQueueTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/MainView.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/PartitionTables.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/PartitionTablespacesTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/PrimaryKeyTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/SortQueueTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/UserDataTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/WriteAheadTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/DeleteTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/InsertTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/UpdateTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/WriteAheadTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/test/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreTest.scala
- geomesa-gt/geomesa-gt-partitioning/src/test/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/EscapeTest.scala
* Feature type user data is persisted and populated on `getSchema`
* Tablespaces are modifiable though a SQL update statement
* Remove TableSpace trait
* Fix delegation of methods with prepared statements enabled
* Add trait for triggers
* Drop duplicate feature ids on insert instead of raising error
> GEOMESA-3173,GEOMESA-3174 Partitioned PostGIS improvements

- geomesa-convert/geomesa-convert-common/src/main/scala/org/locationtech/geomesa/convert/EnrichmentCache.scala
- geomesa-tools/conf/sfts/adsbx/reference.conf
* Loading once stops log spam about loading caches from different classloaders
* Move adsbx caches into converter definition to avoid them being universally loaded
> GEOMESA-3140 Only load converter caches once

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/Bounds.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterValues.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/FilterHelperTest.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/partitions/PartitionSchemeTest.scala
GeoTools filters were transformed to ranges of values when running queries on indexed attributes. When value ranges overlap with each other, running the query would yield duplicated results.
For example, the CQL query `a < 1 OR a < 2` will be transformed to attribute value ranges `[(-inf, 1), (-inf, 2)]`. These value ranges would be transformed into index key ranges, thus leading to a redundant range scan on the index table.
This patch prevents overlapping attribute value ranges from being populated, thus preventing queries from generating duplicated results.
> GEOMESA-3200 Make filter bounds union and intersection produce non overlapping bounds

- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/factory/FastFilterFactory.scala
- geomesa-filter/src/test/scala/org/locationtech/geomesa/filter/factory/FastFilterFactoryTest.scala
The semantics of [GeoTools binary comparison operator](https://github.com/geotools/geotools/blob/main/modules/library/main/src/main/java/org/geotools/filter/CompareFilterImpl.java#L126) is quite strange: when both sides of the operator are string and can be parsed as a number, then it would compare them as if they were numbers. GeoMesa filter optimizer would often replace these filters with a fast version, which always compares strings by lexicographical order.
The default value of binary comparison operators' `matchCase` property is not consistent, the checks for the value of the `matchCase` property in `FastFilterFactory` sometimes prevent from GeoTools filters being replaced with fast filters. Removing these checks makes the behavior of binary comparison operators more consistent. …
> [GEOMESA-3199] String comparison should always comform to lexicographical order

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/index/FilterHelperTest.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/Bounds.scala
- geomesa-filter/src/main/scala/org/locationtech/geomesa/filter/FilterHelper.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/api/GeoMesaFeatureIndex.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/attribute/AttributeIndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/attribute/DateIndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s2/S2IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/s3/S3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z2/Z2IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/XZ3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/index/z3/Z3IndexKeySpace.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/TestGeoMesaDataStore.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/conf/partition/TablePartitionTest.scala
- geomesa-index-api/src/test/scala/org/locationtech/geomesa/index/index/AttributeIndexTest.scala
* Return no ranges for disjoint scans
* Check for no secondary ranges in tiered scans
* Fix edge cases in filter intersections
* Make test data store scan more realistically
> GEOMESA-3203 Short-circuit disjoint filters in index scans

- build/test/resources/log4j.xml
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisPsDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/package.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/AnalyzePartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/CompactPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/DropAgedOffPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/MergeWriteAheadPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/MainView.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/PartitionTables.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/PartitionTablespacesTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/UserDataTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/WriteAheadTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/DeleteTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/UpdateTrigger.scala
- geomesa-gt/geomesa-gt-partitioning/src/test/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreTest.scala
- geomesa-gt/geomesa-gt-tools/pom.xml
- geomesa-gt/geomesa-gt-tools/src/main/scala/org/locationtech/geomesa/geotools/tools/GeoToolsRunner.scala
- geomesa-gt/geomesa-gt-tools/src/main/scala/org/locationtech/geomesa/geotools/tools/data/PostgisUpgradeSchemaCommand.scala
* Add "spill" table for time-latent data
* Add "compact" procedure to merge and re-sort the spill table
* Add "upgrade" command-line tool to update existing tables and procedures
* Make table and procedure creation work cleanly even if some things exist already
* Improve "sort" procedure to replace the partition instead of truncate/insert
> GEOMESA-3221 PostGIS partitioning improvements

- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/MergeWriteAheadPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/RollWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/SequenceTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/WriteAheadTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/triggers/WriteAheadTrigger.scala
* Use rolling _wa tables for writes instead of renaming _wa_writes,
avoiding ACCESS EXCLUSIVE lock for rename
> GEOMESA-3222 PostGIS - Reduce locking during ingest

- docs/user/postgis/index_config.rst
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/PartitionedPostgisDialect.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/package.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/CompactPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/MergeWriteAheadPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionSort.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionWriteAheadLog.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/PartitionTables.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/tables/UserDataTable.scala
- geomesa-gt/geomesa-gt-partitioning/src/test/scala/org/locationtech/geomesa/gt/partition/postgis/PartitionedPostgisDataStoreTest.scala
* Sort by Hilbert curve instead of geohash
* Support configuring pages per index range with `pg.partitions.pages-per-range`
> GEOMESA-3223 PostGIS - improve BRIN indexing

- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/CompactPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/MergeWriteAheadPartitions.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionSort.scala
- geomesa-gt/geomesa-gt-partitioning/src/main/scala/org/locationtech/geomesa/gt/partition/postgis/dialect/procedures/PartitionWriteAheadLog.scala
* Explicitly using sortable hash improves sort performance for large tables
> GEOMESA-3224 Partitioned Postgis - sort with _st_sortablehash

- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/Aggregates.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
If we use spark geomesa library while running in Databricks Runtime (which is the most popular provider of Spark at the moment) via
```scala
spark.withJTS
```
And execute any aggregation or group by operation, there will be the following error:
```
NoSuchMethodException: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.plans.logical.Aggregate.<init>
```
The thing is - Geomesa is using Spark private API which does not guarantee any contract stability and turned out that Databricks maintains a fork of the planner and for Aggregate constructor has 4 instead of 3 arguments.
The fix is to allow to the relaxed way of calling that constructor which would work in both cases.
We use that patch for more than a year in production and looks like that is the only issue we noticed so far.
> GEOMESA-3247 Fix Databricks Spark aggregation/grouping

- docs/user/hbase/configuration.rst
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseConnectionPool.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseDataStoreFactory.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/HBaseIndexAdapter.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/data/LoginUserProvider.scala
- geomesa-hbase/geomesa-hbase-datastore/src/main/scala/org/locationtech/geomesa/hbase/package.scala
- geomesa-hbase/geomesa-hbase-jobs/src/main/scala/org/locationtech/geomesa/hbase/jobs/GeoMesaHBaseInputFormat.scala
- geomesa-hbase/geomesa-hbase-jobs/src/main/scala/org/locationtech/geomesa/hbase/jobs/Security.scala
- geomesa-hbase/geomesa-hbase-spark/src/main/scala/org/locationtech/geomesa/spark/hbase/HBaseSpatialRDDProvider.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/Aggregates.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql/SQLRules.scala
- geomesa-spark/geomesa-spark-sql/src/main/scala/org/locationtech/geomesa/spark/GeoMesaDataSource.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/concurrent/ExitingExecutor.scala
- geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/HadoopUtils.scala
- geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/concurrent/ExitingExecutorTest.scala
Once we started using Geomesa with Kerberos-secured HBase on different runtimes (regular APIs in docker, Flink, Spark on Databricks) we faced a number of issues that prevented Geomesa to work at all. The issues are:
- While running on managed env such as Databricks there is already a current user present on the workers. And simply running `HBaseConnectionPool.configureSecurity` which does `UserGroupInformation.loginUserFromKeytab` does not set the current user as logged-in user and current authorization basically does nothing. There are 2 ways to make a fix:
- The most simple which affects less code which I applied. Switch from `UserGroupInformation.getCurrentUser` to `UserGroupInformation.getLoginUser` which always would used logged-in user.
- The best way, yet will require lots of …
> GEOMESA-3249 HBase - Fix Spark Kerberos authentication

- geomesa-hbase/geomesa-hbase-tools/bin/bootstrap-geomesa-hbase-aws.sh
Update the bootstrap script with correct scala version and hbase version. Since we drop the support for 2.11 and we are moving towards hbase 2, I just change it to two by default.
> Update the aws bootstrap script with correct version

- docs/user/upgrade.rst
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentFeatureSerializer.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-confluent/src/main/scala/org/locationtech/geomesa/kafka/confluent/SchemaParser.scala
- geomesa-kafka/geomesa-kafka-confluent/src/test/scala/org/locationtech/geomesa/kafka/confluent/ConfluentKafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-confluent/src/test/scala/org/locationtech/geomesa/kafka/confluent/SchemaParserTest.scala
- geomesa-kafka/geomesa-kafka-tools/conf-filtered/confluent-dependencies.sh
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/SchemaBuilder.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/sft/SimpleFeatureSpec.scala
* Deprecated org.locationtech.geomesa.kafka.confluent.SchemaParser.GeoMesaAvroDeserializableEnumProperty
* Include date format in feature type attribute user data
* Fix SchemaBuilder to properly escape attribute user data
> GEOMESA-3276 Confluent Kafka - support logical date types

- geomesa-accumulo/geomesa-accumulo-datastore/src/test/scala/org/locationtech/geomesa/accumulo/data/AccumuloFeatureReaderTest.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/planning/QueryPlanner.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/view/MergedQueryRunner.scala
* Threaded hints are not working as intended, and usages should be replaced
> GEOMESA-3299 Deprecate query planner threaded hints

- geomesa-accumulo/geomesa-accumulo-datastore/src/main/scala/org/locationtech/geomesa/accumulo/iterators/FilterTransformIterator.scala
- geomesa-hbase/geomesa-hbase-rpc/src/main/scala/org/locationtech/geomesa/hbase/rpc/filter/CqlTransformFilter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/Z2Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/filters/Z3Filter.scala
- geomesa-index-api/src/main/scala/org/locationtech/geomesa/index/iterators/AggregatingScan.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/conf/IndexId.scala
Eventually we may be able to support older clients talking to newer distributed runtimes - this makes sure that our older clients are at least sending the version info (which is currently disregarded by the receiver)
> GEOMESA-3306 Send client version info with distributed processing calls

- README.md
- build/README.md
- build/cqs.tsv
- pom.xml
Bumping testcontainers version to support build on OS X
Adding doc for non-default Docker Desktop config.
> GEOMESA-3316: Tests fail on OS X with Docker Desktop

- docs/tutorials/geomesa-quickstart-nifi.rst
In going through the NiFi quickstart, I ran into a couple of shell commands in the instructions that produced errors. I corrected those commands, and these work when used with bash on ubuntu 22.04.
NiFi Quickstart documentation:
- Under "Download the Geomesa NiFi NARs", any use of the variable `$nar` was surrounded in curly brackets (`${nar}`) as the variable would substitute with an empty string otherwise (I assume it was getting parsed as `$nar_` instead, which is undefined).
- Under "Obtain GDELT data", change the flags in the `wget` commands from `-O -` to `-qO-`. `wget` would throw an output error otherwise.
- In "Run NiFi with Docker", add a missing backslash to the `docker run` command.
> Correct shell script errors in geomesa-nifi-quickstart

- docs/user/cli/export.rst
- docs/user/convert/function_usage.rst
- docs/user/convert/usage_tools.rst
- geomesa-accumulo/geomesa-accumulo-tools/src/test/resources/examples/example1.csv
- geomesa-accumulo/geomesa-accumulo-tools/src/test/resources/examples/example2.csv
- geomesa-accumulo/geomesa-accumulo-tools/src/test/scala/org/locationtech/geomesa/accumulo/tools/ingest/IngestCommandTest.scala
- geomesa-convert/geomesa-convert-text/src/main/scala/org/locationtech/geomesa/convert/text/DelimitedTextConverterFactory.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/export/ConvertCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/IngestCommand.scala
- geomesa-tools/src/main/scala/org/locationtech/geomesa/tools/ingest/LocalConverterIngest.scala
- geomesa-tools/src/test/scala/org/locationtech/geomesa/tools/export/ConvertCommandTest.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/CopyingInputStream.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/io/fs/LocalDelegate.scala
- geomesa-utils-parent/geomesa-utils/src/test/scala/org/locationtech/geomesa/utils/io/fs/LocalFileHandleTest.scala
* Cache any bytes that the schema inference functions read from the `stdin` input stream - preventing those functions from consuming those bytes and leaving behind nothing for the actual ingest to read
* Create a new wrapper class for `StdInHandle`
* Create a new wrapper class for `CopyingInputStream`, which overrides the `close()` method and prevents `stdin` from being prematurely closed
* Mark the starting position of the `stdin` stream before starting schema inference, and reset the stream back to that point after the inference is complete, so that the ingest can re-read those bytes
* Change unit tests in the `IngestCommandTest` class to use buffered input streams, replicating how the CLI tools process command-line input
Minor changes:
* Flip the lat/lon columns - this fixes a bug …
> GEOMESA-3326 Ingest from stdin even if an SFT and converter are not specified

- build/cqs.tsv
- docs/user/upgrade.rst
- geomesa-hbase/geomesa-hbase-tools/conf-filtered/dependencies.sh
- pom.xml
* zookeeper `3.9.1` -> `3.9.2`
* spring-security `5.8.9` -> `5.8.11`
* jna `4.5.2` -> `5.14.0`
* exclude old netty version used by hadoop
> Bump dependency versions

- geomesa-spark/geomesa_pyspark/src/main/python/geomesa_pyspark/__init__.py
* Fix for SQLTypes package move in Geomesa 4.0.
* Fix for PySpark 3.3+ removing the JVM SQLContext (https://github.com/apache/spark/commit/88696ebcb72fd3057b1546831f653b29b7e0abb2#diff-896993d91855da90bd5a11f9d43008bc053eabc3bf540bcd253dab86e92fb732L323).
> GEOMESA-3345 Fix PySpark init_sql

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreParams.scala
* This isn't actually used, but is updated for consistency
> GEOMESA-3348 Kafka - set ConsumerConfig param to ReadWrite

- geomesa-tools/conf-filtered/geomesa-env.sh
* The warning in RHEL8 is "find: warning you have specified the -maxdepth option after a non-argument -type"
> GEOMESA-3378 Fix CLI "find" warning output

- geomesa-accumulo/geomesa-accumulo-dist/pom.xml
* The 3.7 maven assembly plugin behaves differently than previous versions
* This fix restores the dist tar.gzs to match the old assembly plugin behavior
> Fix jars included in Accumulo distribution lib

- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheImpl.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/index/KafkaFeatureCacheTest.scala
Fixes an issue where if features with null geometries exist in the kafka topic, geoserver will error out on this layer and the KDS cache will be corrupt until the next geoserver restart.
> GEOMESA-3385 Kafka - Check for features with null geometries loaded into cache

- .github/dependabot.yml
* Jobs are timing out due to complex dependency tree
> Disable dependabot dependency updates

- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/utils/PathCache.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/utils/PathCacheTest.scala
* Use Caffeine 2.x-compatible API calls
> GEOMESA-3436 NiFi - Fix FSDS path cache classpath

- docs/user/filesystem/partition_schemes.rst
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/main/scala/org/locationtech/geomesa/fs/storage/common/partitions/AttributeScheme.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-common/src/test/scala/org/locationtech/geomesa/fs/storage/common/partitions/PartitionSchemeTest.scala
- Added the ability to provided a comma separated list of allowed paths to AttributeScheme
- Allows AttributeScheme to be configured to only partition specific pre-defined allowed paths in FSDS
> GEOMESA-3447 FSDS - Support allow-list for attribute partition scheme

- docs/user/kafka/usage.rst
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaCacheLoader.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStore.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreFactory.scala
- geomesa-kafka/geomesa-kafka-datastore/src/main/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreParams.scala
- geomesa-kafka/geomesa-kafka-datastore/src/test/scala/org/locationtech/geomesa/kafka/data/KafkaDataStoreTest.scala
- geomesa-kafka/geomesa-kafka-utils/src/main/scala/org/locationtech/geomesa/kafka/consumer/ThreadedConsumer.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/data/LambdaDataStoreParams.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaCacheLoader.scala
- geomesa-lambda/geomesa-lambda-datastore/src/main/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStore.scala
- geomesa-lambda/geomesa-lambda-datastore/src/test/scala/org/locationtech/geomesa/lambda/stream/kafka/KafkaStoreTest.scala
- geomesa-utils-parent/geomesa-utils/src/main/scala/org/locationtech/geomesa/utils/geotools/GeoMesaParam.scala
* Update `kafka.consumer.offset-commit-interval-ms` to `kafka.consumer.offset-commit-interval`
> GEOMESA-3462 Kafka - Fix initial load sometimes hanging indefinitely (#3310)

- build/cqs.tsv
- docs/user/upgrade.rst
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/fs/storage/parquet/ParquetPathReader.scala
- geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/ParquetStorageTest.scala
- pom.xml
* Allows for hadoop `parquet.hadoop.vectored.io.enabled` flag
> GEOMESA-3467 Upgrade to Parquet 1.15.1
